### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ywecur** [romanz/trezor-agent#11]
`$ trezor-agent ywecur@wunderkinder.io`

```
Traceback (most recent call last):
  File "/usr/local/bin/trezor-agent", line 9, in <module>
    load_entry_point('trezor-agent==0.6.5', 'console_scripts', 'trezor-agent')()
  File "/usr/local/lib/python3.5/site-packages/trezor_agent/__main__.py", line 131, in run_agent
    with client_factory(curve=args.ecdsa_curve_name) as conn:
  File "/usr/local/lib/python3.5/site-packages/trezor_agent/client.py", line 22, in __init__
    client_wrapper = loader()
  File "/usr/local/lib/python3.5/site-packages/trezor_agent/factory.py", line 86, in load
    device_list.extend(loader())
  File "/usr/local/lib/python3.5/site-packages/trezor_agent/factory.py", line 48, in _load_trezor
    from trezorlib.client import TrezorClient, CallException
  File "/usr/local/lib/python3.5/site-packages/trezorlib/client.py", line 7, in <module>
    import mapping
ImportError: No module named 'mapping'
```

I then tried `$ pip install mapping` which returned:

`Collecting mapping
  Could not find a version that satisfies the requirement mapping (from versions: )
No matching distribution found for mapping`

Mac OS X El Capitan 10.11.4
Trezor on the latest firmware

**Comment by romanz** [comment]
Thanks for reporting this issue!
Could you please try to run it with Python 2? 
I think that there may be a problem with Python 3.

**Comment by romanz** [comment]
As far as I understand, this happens due to non-relative `import` statement at `trezorlib.client`.
In Python 3, it should be written as:

```python
from . import mapping
```

**Comment by ywecur** [comment]
@romanz How do I do that?

**Comment by romanz** [comment]
Sorry for the inconvenience, I will try to prepare a PR to python-trezor to add support for Python 3.
Meanwhile, you can install Python 2 on your machine, and use it to run  trezor-agent...

**Comment by romanz** [comment]
https://github.com/trezor/python-trezor/issues/56

**Comment by slush0** [comment]
romanz: Please give it a try and tell me back, branch "python3" might work for you already.

**Comment by romanz** [comment]
Thanks a lot for the fixes! 
There was a small issue at `transport_hid` (fixed by https://github.com/trezor/python-trezor/pull/57) and after installing `protobuf==3.0.0b2.post2` dependency (since `protobuf==2.6.1` isn't compatible with Python 3), `trezor-agent` works like a charm :)

**Comment by romanz** [comment]
@ywecur `trezor-agent` should work now on Python 3.
Please try it and tell me if it works for you.

```
python3 -m venv /tmp/v3
. /tmp/v3/bin/activate
pip install protobuf==3.0.0b2.post2      # needed for Python 3 support for protobuf
pip install Cython                       # needed to build python-trezor
pip install git+https://github.com/trezor/python-trezor.git@python3
pip install git+https://github.com/romanz/trezor-agent.git@python3

trezor-agent -vv localhost               # should print you NIST256 SSH public key
```

**Comment by romanz** [comment]
@ywecur ?

**Comment by romanz** [comment]
Somehow, the latest `hidapi` package fails to build on Python3:

```
$ pip install hidapi==0.7.99.post16
Downloading/unpacking hidapi==0.7.99.post16
  Using download cache from /home/roman/.pip_download_cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2F35%2Fe0%2Fc6b3da6999043d96cda6a1c44d5f1054058cc6e5c05b1139886444b31bb0%2Fhidapi-0.7.99.post16.tar.gz
  Running setup.py (path:/tmp/pip-build-fbriuxzv/hidapi/setup.py) egg_info for package hidapi
    
Installing collected packages: hidapi
  Found existing installation: hidapi 0.7.99.post15
    Uninstalling hidapi:
      Successfully uninstalled hidapi
  Running setup.py install for hidapi
    building 'hid' extension
    error: unknown file type '.pyx' (from 'hid.pyx')
    Complete output from command /media/oldhome/roman/Code/trezor/trezor-agent/v3/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-fbriuxzv/hidapi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-7ybd1pqu-record/install-record.txt --single-version-externally-managed --compile --install-headers /media/oldhome/roman/Code/trezor/trezor-agent/v3/include/site/python3.4:
    running install

running build

running build_ext

building 'hid' extension

error: unknown file type '.pyx' (from 'hid.pyx')
```

**Comment by romanz** [comment]
@prusnak Could you please take a look on this issue?

**Comment by slush0** [comment]
What version of Cython do you use? I had similar issue and fixed it by installing older Cython version. I did not dig into the problem more as I needed to focus to another thing, but if this will fix problem for you, we should stick the version and report it to cython.

**Comment by prusnak** [comment]
setuptools is usually the culprit. make sure you have at least version 19.

**Comment by romanz** [comment]
Thanks! I will retry the installation :)

**Comment by romanz** [comment]
It works!
The correct installation for Python 3 is:

```
python3 -m venv /tmp/v3
. /tmp/v3/bin/activate
pip install 'setuptools>=19.0.0'
pip install protobuf==3.0.0b2.post2      # needed for Python 3 support for protobuf
pip install Cython                       # needed to build python-trezor
pip install git+https://github.com/trezor/python-trezor.git@python3
pip install git+https://github.com/romanz/trezor-agent.git@python3
```

**Comment by romanz** [comment]
Now the installation should be even simpler:

```
python3 -m venv /tmp/v3
. /tmp/v3/bin/activate
pip install -U setuptools Cython
pip install git+https://github.com/romanz/trezor-agent.git
```

**Comment by ecdsa** [comment]
hello, I'm having the same issue as @romanz when trying to install hidapi with python3:
`error: unknown file type '.pyx' (from 'hid.pyx')` 
it works with hidapi==0.7.99.post15, and it fails with any ulterior version.

**Comment by prusnak** [comment]
Old setuptools, upgrade to latest

**Comment by ecdsa** [comment]
```Downloading/unpacking hidapi
  Downloading hidapi-0.7.99.post20.tar.gz (51kB): 51kB downloaded
  Running setup.py (path:/tmp/pip_build_root/hidapi/setup.py) egg_info for package hidapi
    
Downloading/unpacking setuptools>=19.0 (from hidapi)
  Downloading setuptools-34.2.0-py2.py3-none-any.whl (389kB): 389kB downloaded
Requirement already satisfied (use --upgrade to upgrade): six>=1.6.0 in /usr/local/lib/python3.4/dist-packages (from setuptools>=19.0->hidapi)
Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.4.0 in /usr/local/lib/python3.4/dist-packages (from setuptools>=19.0->hidapi)
Requirement already satisfied (use --upgrade to upgrade): packaging>=16.8 in /usr/local/lib/python3.4/dist-packages (from setuptools>=19.0->hidapi)
Installing collected packages: hidapi, setuptools
  Running setup.py install for hidapi
    building 'hid' extension
    error: unknown file type '.pyx' (from 'hid.pyx')
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/hidapi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-8f18cgdt-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_ext

building 'hid' extension

error: unknown file type '.pyx' (from 'hid.pyx')
```

**Comment by ecdsa** [comment]
@prusnak I am running the latest setuptools, see above

**Comment by prusnak** [comment]
Do you have Cython installed? Preferably also latest

**Comment by ecdsa** [comment]
@prusnak I have Cython-0.25.2, installed with pip3
