### ISSUE TITLE
Using Ledger Nano: Invalid status 6e00 or Invalid channel

### ISSUE THREAD

**Issue by knocte** [romanz/trezor-agent#119]
Tried this, and first time I got:

```
$ ledger-agent andres@localhost
Traceback (most recent call last):
  File "/usr/local/bin/ledger-agent", line 9, in <module>
    load_entry_point('ledger-agent==0.9.0', 'console_scripts', 'ledger-agent')()
  File "/usr/local/bin/ledger_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 130, in wrapper
    return func(*args, **kwargs)
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 221, in main
    for pk in conn.public_keys():
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 165, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/device/interface.py", line 110, in __enter__
    self.conn = self.connect()
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/device/ledger.py", line 45, in connect
    '{} not connected: "{}"'.format(self, e))
libagent.device.interface.NotFoundError: LedgerNanoS not connected: "Exception : No dongle found"
```

Then, of course, I connected the Ledger, then:

```
andres@ulises:~/Documents/Code/OpenSource/gwallet$ ledger-agent andres@localhost
Traceback (most recent call last):
  File "/usr/local/bin/ledger-agent", line 9, in <module>
    load_entry_point('ledger-agent==0.9.0', 'console_scripts', 'ledger-agent')()
  File "/usr/local/bin/ledger_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 130, in wrapper
    return func(*args, **kwargs)
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 221, in main
    for pk in conn.public_keys():
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 165, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/ssh/client.py", line 26, in export_public_keys
    pubkey = self.device.pubkey(identity=i)
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/device/ledger.py", line 59, in pubkey
    result = bytearray(self.conn.exchange(bytes(apdu)))[1:]
  File "/home/andres/.local/lib/python2.7/site-packages/ledgerblue/comm.py", line 130, in exchange
    raise CommException("Invalid status %04x" % sw, sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6e00
```

If in the ledger I open the FIDO app, then I get:

```
andres@ulises:~/Documents/Code/OpenSource/gwallet$ ledger-agent andres@localhost
Traceback (most recent call last):
  File "/usr/local/bin/ledger-agent", line 9, in <module>
    load_entry_point('ledger-agent==0.9.0', 'console_scripts', 'ledger-agent')()
  File "/usr/local/bin/ledger_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 130, in wrapper
    return func(*args, **kwargs)
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 221, in main
    for pk in conn.public_keys():
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 165, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/ssh/client.py", line 26, in export_public_keys
    pubkey = self.device.pubkey(identity=i)
  File "/home/andres/.local/lib/python2.7/site-packages/libagent/device/ledger.py", line 59, in pubkey
    result = bytearray(self.conn.exchange(bytes(apdu)))[1:]
  File "/home/andres/.local/lib/python2.7/site-packages/ledgerblue/comm.py", line 116, in exchange
    response = unwrapResponseAPDU(0x0101, result, 64)
  File "/home/andres/.local/lib/python2.7/site-packages/ledgerblue/ledgerWrapper.py", line 69, in unwrapResponseAPDU
    raise CommException("Invalid channel")
ledgerblue.commException.CommException: Exception : Invalid channel
```
How to use the Ledger with this?

**Comment by romanz** [comment]
Please make sure that your device has 'SSH/PGP Agent' app [installed](https://cloud.githubusercontent.com/assets/9900/26453575/e1910726-416c-11e7-9731-ec16de67b2d4.png) and running.
It can be installed by clicking 'Show developer items' (in the bottom-right corner of the [Ledger Manager](https://chrome.google.com/webstore/detail/ledger-manager/beimhnaefocolcplfimocfiaiefpkgbf?utm_source=chrome-ntp-icon)):
![image](https://cloud.githubusercontent.com/assets/9900/26451846/60678f68-4166-11e7-890f-7f74c6069ecb.png)

**Comment by romanz** [comment]
@knocte ping?

**Comment by knocte** [comment]
Yeah that was it. Thanks for updating the documentation.
