### ISSUE TITLE
scripts/gpg-init fails to create new key

### ISSUE THREAD

**Issue by rcamera** [romanz/trezor-agent#121]
Just got my first Trezor, trying to generate a GPG key, but the script is failing, throwing me this error:

```
[rcs@ranis scripts]$ DEVICE=trezor ./gpg-init "John Doe <oh@noes.com>"
2017-06-05 16:53:12,946 WARNING      This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility! [__init__.py:79]
2017-06-05 16:53:12,948 WARNING      NOTE: in order to re-generate the exact same GPG key later, run this command with "--time=1496681592" commandline flag (to set the timestamp of the GPG key manually). [__init__.py:30]
Traceback (most recent call last):
  File "/usr/bin/trezor-gpg", line 11, in <module>
    load_entry_point('trezor-agent==0.9.0', 'console_scripts', 'trezor-gpg')()
  File "/usr/bin/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/usr/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 145, in main
    return args.func(device_type=device_type, args=args)
  File "/usr/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 86, in run_create
    export_public_key(device_type, args)
  File "/usr/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 33, in export_public_key
    verifying_key = c.pubkey(ecdh=False)
  File "/usr/lib/python3.6/site-packages/libagent/gpg/client.py", line 23, in pubkey
    with self.device:
  File "/usr/lib/python3.6/site-packages/libagent/device/interface.py", line 110, in __enter__
    self.conn = self.connect()
  File "/usr/lib/python3.6/site-packages/libagent/device/trezor.py", line 36, in connect
    for d in self._defs.Transport.enumerate():
  File "/usr/lib/python3.6/site-packages/libagent/device/trezor.py", line 19, in _defs
    from . import trezor_defs
  File "/usr/lib/python3.6/site-packages/libagent/device/trezor_defs.py", line 8, in <module>
    from trezorlib.transport_bridge import BridgeTransport
  File "/usr/lib/python3.6/site-packages/trezorlib/transport_bridge.py", line 24, in <module>
    from . import protobuf_json
  File "/usr/lib/python3.6/site-packages/trezorlib/protobuf_json.py", line 116, in <module>
    FD.TYPE_INT64: long,
NameError: name 'long' is not defined

```

I don't understand that error. I have all dependencies installed correctly, according to the README. Do you need any more information?

**Comment by rcamera** [comment]
I think I got what is happening, I am running archlinux, which defaults the python command, to use Python3, but apparently this script is only compatible with Python2, as there is (apparently) no `long` in python3. Is that correct?

**Comment by rcamera** [comment]
Ok, got it working now that I used python2 instead. Closing the issue.

**Comment by romanz** [comment]
Thanks for reporting this!

It seems that `trezorlib` don't have full Python 3 support :(
I've opened https://github.com/trezor/python-trezor/pull/112 to fix some of the issues...

**Comment by rcamera** [comment]
No worries, thanks for the great work of making this =)

I will follow that PR and help with testing whenever needed.
