### ISSUE TITLE
Unicode support for user id

### ISSUE THREAD

**Issue by B3QL** [romanz/trezor-agent#125]
I spot a problem with unicode encoding while creating new identity.
```
./trezor-gpg create -v -e ed25519 "Bartłomiej Kurzeja <me@example.org>"
```
```
Traceback (most recent call last):
  File "./trezor-gpg", line 11, in <module>
    load_entry_point('trezor-agent==0.9.0', 'console_scripts', 'trezor-gpg')()
  File "/home/b3ql/.asdf/installs/python/3.6.0/bin/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/home/b3ql/.asdf/installs/python/3.6.0/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 145, in main
    return args.func(device_type=device_type, args=args)
  File "/home/b3ql/.asdf/installs/python/3.6.0/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 86, in run_create
    export_public_key(device_type, args)
  File "/home/b3ql/.asdf/installs/python/3.6.0/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 33, in export_public_key
    verifying_key = c.pubkey(ecdh=False)
  File "/home/b3ql/.asdf/installs/python/3.6.0/lib/python3.6/site-packages/libagent/gpg/client.py", line 24, in pubkey
    pubkey = self.device.pubkey(ecdh=ecdh, identity=self.identity)
  File "/home/b3ql/.asdf/installs/python/3.6.0/lib/python3.6/site-packages/libagent/device/trezor.py", line 68, in pubkey
    addr = identity.get_bip32_address(ecdh=ecdh)
  File "/home/b3ql/.asdf/installs/python/3.6.0/lib/python3.6/site-packages/libagent/device/interface.py", line 79, in get_bip32_address
    addr = index + identity_to_string(self.identity_dict).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\u0142' in position 10: ordinal not in range(128)
```

**Comment by romanz** [comment]
Thanks for reporting the issue :)

**Comment by romanz** [comment]
Since TREZOR UI does not support Unicode, we should "normalize" the identity back to ASCII before sending it to the device (https://pypi.python.org/pypi/Unidecode/)

**Comment by romanz** [comment]
Now it should work:
"Bartłomiej Kurzeja <me@example.org>" will be stored as GPG identity but the key derivation will use "Bartlomiej Kurzeja <me@example.org>" (note the `l` instead of `ł`).
Thanks again :)
