### ISSUE TITLE
pkg_resources.ContextualVersionConflict with protobuf

### ISSUE THREAD

**Issue by WyseNynja** [romanz/trezor-agent#15]
```
trezor-agent --help
Traceback (most recent call last):
  File "/Users/bwstitt/.virtualenvs/trezor-agent/bin/trezor-agent", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Users/bwstitt/.virtualenvs/trezor-agent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/Users/bwstitt/.virtualenvs/trezor-agent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/Users/bwstitt/.virtualenvs/trezor-agent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/bwstitt/.virtualenvs/trezor-agent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/bwstitt/.virtualenvs/trezor-agent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/bwstitt/.virtualenvs/trezor-agent/lib/python2.7/site-packages/pkg_resources/__init__.py", line 834, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (protobuf 3.0.0b3 (/Users/bwstitt/.virtualenvs/trezor-agent/lib/python2.7/site-packages), Requirement.parse('protobuf==2.6.1'), set(['trezor']))
```

I searched through everything for ==2.6.1 and found two places: keepkey-0.7.0.dist-info/METADATA and trezor-0.6.12.post1.dist-info/METADATA

I think trezor-agent's setup.py needs to stick with 2.6.1 until these bump their versions

**Comment by romanz** [comment]
Thanks for reporting this issue!

**Comment by romanz** [comment]
BTW, protobuf version 3.0.0 was released two days ago: https://github.com/google/protobuf/releases/tag/v3.0.0
It supports both Python 2 & 3, so it should help us to port `trezor`'s Python code to Python 3.
