### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5'

### ISSUE THREAD

**Issue by galuszkak** [romanz/trezor-agent#152]
Am I doing something wrong here?

```
kamil@whatever $ trezor-agent -s my@identity.com
kamil@whatever $ git pull origin master
2017-10-15 14:36:05,525 WARNING      error: No module named 'PyQt5'                                                                       [server.py:63]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/libagent/server.py", line 58, in handle_connection
    reply = handler.handle(msg=msg)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/protocol.py", line 103, in handle
    reply = method(buf=buf)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/protocol.py", line 111, in list_pubs
    keys = self.conn.parse_public_keys()
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 178, in parse_public_keys
    for pk in self.public_keys()]
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 172, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/usr/local/lib/python3.6/site-packages/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/usr/local/lib/python3.6/site-packages/libagent/device/trezor.py", line 80, in connect
    connection.ping(msg='', pin_protection=True)  # unlock PIN
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 129, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 144, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 587, in ping
    return self.call(msg)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 158, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 201, in call
    msg = handler(resp)
  File "/usr/local/lib/python3.6/site-packages/libagent/device/trezor.py", line 43, in qt_handler
    from PyQt5.QtWidgets import QApplication, QInputDialog, QLineEdit
ModuleNotFoundError: No module named 'PyQt5'
Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by romanz** [comment]
Thanks for reporting this issue!

I forgot to add the dependency on `PyQt5` (used for PIN entry when no TTY is available) to the `libagent` package.

**Comment by galuszkak** [comment]
@romanz It doesn't work.

```
kamil@Kamils-MacBook-Pro:~/Projects/example (dev$%<>) % trezor-agent kamil@flyrlabs.com -s
kamil@Kamils-MacBook-Pro:~/Projects/example (dev$%<>) % git pull origin dev
2017-10-17 11:15:09.756 Python[82628:6043250] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1443.14/Misc.subproj/NSUndoManager.m:361
2017-10-17 11:15:09.763 Python[82628:6043250] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff5475e0fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7b04cc76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff54763e92 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff5683c690 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   Foundation                          0x00007fff567cb614 +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 469
	5   AppKit                              0x00007fff51ce98ee -[NSApplication run] + 997
	6   libqcocoa.dylib                     0x00000001070ab9bf qt_plugin_instance + 133407
	7   QtCore                              0x000000010661a631 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 401
	8   QtCore                              0x000000010661f099 _ZN16QCoreApplication4execEv + 393
	9   QtWidgets.so                        0x00000001056356d2 _ZL23meth_QApplication_exec_P7_objectS0_ + 82
	10  Python                              0x0000000102fb3b49 _PyCFunction_FastCallDict + 166
	11  Python                              0x00000001030181da call_function + 489
	12  Python                              0x00000001030110a7 _PyEval_EvalFrameDefault + 4811
	13  Python                              0x000000010301893c _PyEval_EvalCodeWithName + 1719
	14  Python                              0x000000010301903f fast_function + 218
	15  Python                              0x00000001030181b1 call_function + 448
	16  Python                              0x00000001030110a7 _PyEval_EvalFrameDefault + 4811
	17  Python                              0x000000010301893c _PyEval_EvalCodeWithName + 1719
	18  Python                              0x000000010300fda1 PyEval_EvalCodeEx + 57
	19  Python                              0x0000000102f9c106 function_call + 339
	20  Python                              0x0000000102f7bdf2 PyObject_Call + 101
	21  Python                              0x0000000103011310 _PyEval_EvalFrameDefault + 5428
	22  Python                              0x000000010301893c _PyEval_EvalCodeWithName + 1719
	23  Python                              0x000000010301903f fast_function + 218
	24  Python                              0x00000001030181b1 call_function + 448
	25  Python                              0x00000001030110a7 _PyEval_EvalFrameDefault + 4811
	26  Python                              0x000000010301893c _PyEval_EvalCodeWithName + 1719
	27  Python                              0x000000010300fda1 PyEval_EvalCodeEx + 57
	28  Python                              0x0000000102f9c106 function_call + 339
	29  Python                              0x0000000102f7bdf2 PyObject_Call + 101
	30  Python                              0x0000000103011310 _PyEval_EvalFrameDefault + 5428
	31  Python                              0x000000010301893c _PyEval_EvalCodeWithName + 1719
	32  Python                              0x000000010300fda1 PyEval_EvalCodeEx + 57
	33  Python                              0x0000000102f9c106 function_call + 339
	34  Python                              0x0000000102f7bdf2 PyObject_Call + 101
	35  Python                              0x0000000103011310 _PyEval_EvalFrameDefault + 5428
	36  Python                              0x000000010301893c _PyEval_EvalCodeWithName + 1719
	37  Python                              0x000000010301903f fast_function + 218
	38  Python                              0x00000001030181b1 call_function + 448
	39  Python                              0x0000000103011140 _PyEval_EvalFrameDefault + 4964
	40  Python                              0x000000010301893c _PyEval_EvalCodeWithName + 1719
	41  Python                              0x000000010301903f fast_function + 218
	42  Python                              0x00000001030181b1 call_function + 448
	43  Python                              0x00000001030110a7 _PyEval_EvalFrameDefault + 4811
	44  Python                              0x00000001030192df _PyFunction_FastCall + 121
	45  Python                              0x0000000102f7bf71 _PyObject_FastCallDict + 196
	46  Python                              0x0000000102f7c094 _PyObject_Call_Prepend + 156
	47  Python                              0x0000000102f7bf3c _PyObject_FastCallDict + 143
	48  Python                              0x0000000102f78da2 PyObject_CallFunctionObjArgs + 210
	49  Python                              0x0000000103010da0 _PyEval_EvalFrameDefault + 4036
	50  Python                              0x00000001030192df _PyFunction_FastCall + 121
	51  Python                              0x00000001030181b1 call_function + 448
	52  Python                              0x00000001030110a7 _PyEval_EvalFrameDefault + 4811
	53  Python                              0x00000001030192df _PyFunction_FastCall + 121
	54  Python                              0x00000001030181b1 call_function + 448
	55  Python                              0x00000001030110a7 _PyEval_EvalFrameDefault + 4811
	56  Python                              0x00000001030192df _PyFunction_FastCall + 121
	57  Python                              0x00000001030181b1 call_function + 448
	58  Python                              0x00000001030110a7 _PyEval_EvalFrameDefault + 4811
	59  Python                              0x000000010301893c _PyEval_EvalCodeWithName + 1719
	60  Python                              0x000000010301903f fast_function + 218
	61  Python                              0x00000001030181b1 call_function + 448
	62  Python                              0x0000000103011140 _PyEval_EvalFrameDefault + 4964
	63  Python                              0x000000010301893c _PyEval_EvalCodeWithName + 1719
	64  Python                              0x000000010301903f fast_function + 218
	65  Python                              0x00000001030181b1 call_function + 448
	66  Python                              0x0000000103011140 _PyEval_EvalFrameDefault + 4964
	67  Python                              0x000000010301893c _PyEval_EvalCodeWithName + 1719
	68  Python                              0x000000010301920f _PyFunction_FastCallDict + 449
	69  Python                              0x0000000102f7bf71 _PyObject_FastCallDict + 196
	70  Python                              0x00000001030633b7 partial_call + 258
	71  Python                              0x0000000102f7bdf2 PyObject_Call + 101
	72  Python                              0x0000000103011310 _PyEval_EvalFrameDefault + 5428
	73  Python                              0x00000001030192df _PyFunction_FastCall + 121
	74  Python                              0x00000001030181b1 call_function + 448
	75  Python                              0x00000001030110a7 _PyEval_EvalFrameDefault + 4811
	76  Python                              0x00000001030192df _PyFunction_FastCall + 121
	77  Python                              0x00000001030181b1 call_function + 448
	78  Python                              0x00000001030110a7 _PyEval_EvalFrameDefault + 4811
	79  Python                              0x00000001030192df _PyFunction_FastCall + 121
	80  Python                              0x0000000102f7bf71 _PyObject_FastCallDict + 196
	81  Python                              0x0000000102f7c094 _PyObject_Call_Prepend + 156
	82  Python                              0x0000000102f7bdf2 PyObject_Call + 101
	83  Python                              0x000000010304d8cb t_bootstrap + 70
	84  libsystem_pthread.dylib             0x00007fff7bec56c1 _pthread_body + 340
	85  libsystem_pthread.dylib             0x00007fff7bec556d _pthread_body + 0
	86  libsystem_pthread.dylib             0x00007fff7bec4c5d thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    82628 abort      trezor-agent kamil@flyrlabs.com -s
```

**Comment by romanz** [comment]
Did you installed `PyQt5` via `pip` or via `homebrew`?

**Comment by galuszkak** [comment]
@romanz via pip.

**Comment by galuszkak** [comment]
Hi @romanz . I think issue still persists here.
```
kamil@Kamils-MacBook-Pro:~/Projects/ (feature/example $=) % git pull origin feature/example
2017-10-19 09:18:18.113 Python[58214:9246558] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1443.14/Misc.subproj/NSUndoManager.m:361
2017-10-19 09:18:18.116 Python[58214:9246558] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff5475e0fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff7b04cc76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff54763e92 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff5683c690 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 193
	4   Foundation                          0x00007fff567cb614 +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 469
	5   AppKit                              0x00007fff51ce98ee -[NSApplication run] + 997
	6   libqcocoa.dylib                     0x00000001100639bf qt_plugin_instance + 133407
	7   QtCore                              0x000000010dc1a631 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 401
	8   QtCore                              0x000000010dc1f099 _ZN16QCoreApplication4execEv + 393
	9   QtWidgets.so                        0x000000010cc356d2 _ZL23meth_QApplication_exec_P7_objectS0_ + 82
	10  Python                              0x000000010a600b49 _PyCFunction_FastCallDict + 166
	11  Python                              0x000000010a6651da call_function + 489
	12  Python                              0x000000010a65e0a7 _PyEval_EvalFrameDefault + 4811
	13  Python                              0x000000010a66593c _PyEval_EvalCodeWithName + 1719
	14  Python                              0x000000010a66603f fast_function + 218
	15  Python                              0x000000010a6651b1 call_function + 448
	16  Python                              0x000000010a65e0a7 _PyEval_EvalFrameDefault + 4811
	17  Python                              0x000000010a66593c _PyEval_EvalCodeWithName + 1719
	18  Python                              0x000000010a65cda1 PyEval_EvalCodeEx + 57
	19  Python                              0x000000010a5e9106 function_call + 339
	20  Python                              0x000000010a5c8df2 PyObject_Call + 101
	21  Python                              0x000000010a65e310 _PyEval_EvalFrameDefault + 5428
	22  Python                              0x000000010a66593c _PyEval_EvalCodeWithName + 1719
	23  Python                              0x000000010a66603f fast_function + 218
	24  Python                              0x000000010a6651b1 call_function + 448
	25  Python                              0x000000010a65e0a7 _PyEval_EvalFrameDefault + 4811
	26  Python                              0x000000010a66593c _PyEval_EvalCodeWithName + 1719
	27  Python                              0x000000010a65cda1 PyEval_EvalCodeEx + 57
	28  Python                              0x000000010a5e9106 function_call + 339
	29  Python                              0x000000010a5c8df2 PyObject_Call + 101
	30  Python                              0x000000010a65e310 _PyEval_EvalFrameDefault + 5428
	31  Python                              0x000000010a66593c _PyEval_EvalCodeWithName + 1719
	32  Python                              0x000000010a65cda1 PyEval_EvalCodeEx + 57
	33  Python                              0x000000010a5e9106 function_call + 339
	34  Python                              0x000000010a5c8df2 PyObject_Call + 101
	35  Python                              0x000000010a65e310 _PyEval_EvalFrameDefault + 5428
	36  Python                              0x000000010a66593c _PyEval_EvalCodeWithName + 1719
	37  Python                              0x000000010a66603f fast_function + 218
	38  Python                              0x000000010a6651b1 call_function + 448
	39  Python                              0x000000010a65e140 _PyEval_EvalFrameDefault + 4964
	40  Python                              0x000000010a66593c _PyEval_EvalCodeWithName + 1719
	41  Python                              0x000000010a66603f fast_function + 218
	42  Python                              0x000000010a6651b1 call_function + 448
	43  Python                              0x000000010a65e0a7 _PyEval_EvalFrameDefault + 4811
	44  Python                              0x000000010a6662df _PyFunction_FastCall + 121
	45  Python                              0x000000010a5c8f71 _PyObject_FastCallDict + 196
	46  Python                              0x000000010a5c9094 _PyObject_Call_Prepend + 156
	47  Python                              0x000000010a5c8f3c _PyObject_FastCallDict + 143
	48  Python                              0x000000010a5c5da2 PyObject_CallFunctionObjArgs + 210
	49  Python                              0x000000010a65dda0 _PyEval_EvalFrameDefault + 4036
	50  Python                              0x000000010a6662df _PyFunction_FastCall + 121
	51  Python                              0x000000010a6651b1 call_function + 448
	52  Python                              0x000000010a65e0a7 _PyEval_EvalFrameDefault + 4811
	53  Python                              0x000000010a6662df _PyFunction_FastCall + 121
	54  Python                              0x000000010a6651b1 call_function + 448
	55  Python                              0x000000010a65e0a7 _PyEval_EvalFrameDefault + 4811
	56  Python                              0x000000010a6662df _PyFunction_FastCall + 121
	57  Python                              0x000000010a6651b1 call_function + 448
	58  Python                              0x000000010a65e0a7 _PyEval_EvalFrameDefault + 4811
	59  Python                              0x000000010a66593c _PyEval_EvalCodeWithName + 1719
	60  Python                              0x000000010a66603f fast_function + 218
	61  Python                              0x000000010a6651b1 call_function + 448
	62  Python                              0x000000010a65e140 _PyEval_EvalFrameDefault + 4964
	63  Python                              0x000000010a66593c _PyEval_EvalCodeWithName + 1719
	64  Python                              0x000000010a66603f fast_function + 218
	65  Python                              0x000000010a6651b1 call_function + 448
	66  Python                              0x000000010a65e140 _PyEval_EvalFrameDefault + 4964
	67  Python                              0x000000010a66593c _PyEval_EvalCodeWithName + 1719
	68  Python                              0x000000010a66620f _PyFunction_FastCallDict + 449
	69  Python                              0x000000010a5c8f71 _PyObject_FastCallDict + 196
	70  Python                              0x000000010a6b03b7 partial_call + 258
	71  Python                              0x000000010a5c8df2 PyObject_Call + 101
	72  Python                              0x000000010a65e310 _PyEval_EvalFrameDefault + 5428
	73  Python                              0x000000010a6662df _PyFunction_FastCall + 121
	74  Python                              0x000000010a6651b1 call_function + 448
	75  Python                              0x000000010a65e0a7 _PyEval_EvalFrameDefault + 4811
	76  Python                              0x000000010a6662df _PyFunction_FastCall + 121
	77  Python                              0x000000010a6651b1 call_function + 448
	78  Python                              0x000000010a65e0a7 _PyEval_EvalFrameDefault + 4811
	79  Python                              0x000000010a6662df _PyFunction_FastCall + 121
	80  Python                              0x000000010a5c8f71 _PyObject_FastCallDict + 196
	81  Python                              0x000000010a5c9094 _PyObject_Call_Prepend + 156
	82  Python                              0x000000010a5c8df2 PyObject_Call + 101
	83  Python                              0x000000010a69a8cb t_bootstrap + 70
	84  libsystem_pthread.dylib             0x00007fff7bec56c1 _pthread_body + 340
	85  libsystem_pthread.dylib             0x00007fff7bec556d _pthread_body + 0
	86  libsystem_pthread.dylib             0x00007fff7bec4c5d thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    58214 abort      trezor-agent kamil@example.com -s
```

**Comment by romanz** [comment]
Well, this is weird... :(

Can you please try using `homebrew` for installing the `python3-pyqt5` package?
Also, you can run the following [script](https://gist.github.com/romanz/4d9f242b393ccfbffa59824d79539faf) for testing the PIN entry dialog on your machine (it contains the only Qt-related code from `trezor-agent`).

BTW, I can try to rewrite this UI in Tk if this will solve the dependency issues...

**Comment by romanz** [comment]
Please take a look at https://github.com/romanz/trezor-agent/commit/08fef24e39abff0cc60f7341e7e124fccbdc5ce8 (it's using `pymsgbox` instead of `PyQt5`).

**Comment by galuszkak** [comment]
@romanz I've tried now but it doesn't work. It's like stucked forever.
I just see bouncing Python icon in dock like that.
<img width="164" alt="screen shot 2017-10-22 at 9 28 31 am" src="https://user-images.githubusercontent.com/759579/31858542-63a06428-b70b-11e7-9e44-a8fb81d56761.png">
...

**Comment by romanz** [comment]
Could you please try running the following code in your local Python interpreter:
```python
>>> import pymsgbox
>>> pymsgbox.prompt('Foo')
```

**Comment by romanz** [comment]
It [should](https://github.com/asweigart/PyMsgBox/blob/master/setup.py#L24) work on Mac OS X...

**Comment by galuszkak** [comment]
@romanz this one actually works on my laptop. I will try on my work laptop this morning, where I had this bug.

**Comment by galuszkak** [comment]
@romanz on my work laptop this chunk of code also works, but case from Trezor doesn't work still.

**Comment by romanz** [comment]
Can you please try the latest commit (https://github.com/romanz/trezor-agent/commit/3d5717dca1626f3f2269cc66dee00d2d72a39e67)?
It uses a separate process for getting the scrambled PIN (instead of using the `pymsgbox` directly).

**Comment by galuszkak** [comment]
@romanz it doesn't work. But I know why. You have hardcoded python. Can You detect which interepreter You are using so if I'm using python3 it will use it, rather than hardcoding?
```
2017-10-27 12:19:35,350 ERROR        PIN entry failed: b'Traceback (most recent call last):\n  File "<string>", line 1, in <module>\nImportError: No module named pymsgbox\n' [trezor.py:33]
2017-10-27 12:19:35,351 ERROR        ping failed: Command '['python', '-c', 'import sys, pymsgbox; sys.stdout.write(pymsgbox.password(sys.stdin.read()))']' returned non-zero exit status 1. [trezor.py:92]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/libagent-0.9.5-py3.6.egg/libagent/device/trezor.py", line 90, in connect
    connection.ping(msg='', pin_protection=True)  # unlock PIN
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 129, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 144, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 587, in ping
    return self.call(msg)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 158, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 201, in call
    msg = handler(resp)
  File "/usr/local/lib/python3.6/site-packages/libagent-0.9.5-py3.6.egg/libagent/device/trezor.py", line 64, in ui_handler
    scrambled_pin = pin_entry_gui()
  File "/usr/local/lib/python3.6/site-packages/libagent-0.9.5-py3.6.egg/libagent/device/trezor.py", line 34, in pin_entry_gui
    raise sp.CalledProcessError(exitcode, args)
subprocess.CalledProcessError: Command '['python', '-c', 'import sys, pymsgbox; sys.stdout.write(pymsgbox.password(sys.stdin.read()))']' returned non-zero exit status 1.
2017-10-27 12:19:35,352 WARNING      error: Command '['python', '-c', 'import sys, pymsgbox; sys.stdout.write(pymsgbox.password(sys.stdin.read()))']' returned non-zero exit status 1. [server.py:63]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/libagent-0.9.5-py3.6.egg/libagent/server.py", line 58, in handle_connection
    reply = handler.handle(msg=msg)
  File "/usr/local/lib/python3.6/site-packages/libagent-0.9.5-py3.6.egg/libagent/ssh/protocol.py", line 103, in handle
    reply = method(buf=buf)
  File "/usr/local/lib/python3.6/site-packages/libagent-0.9.5-py3.6.egg/libagent/ssh/protocol.py", line 111, in list_pubs
    keys = self.conn.parse_public_keys()
  File "/usr/local/lib/python3.6/site-packages/libagent-0.9.5-py3.6.egg/libagent/ssh/__init__.py", line 178, in parse_public_keys
    for pk in self.public_keys()]
  File "/usr/local/lib/python3.6/site-packages/libagent-0.9.5-py3.6.egg/libagent/ssh/__init__.py", line 172, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/usr/local/lib/python3.6/site-packages/libagent-0.9.5-py3.6.egg/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/usr/local/lib/python3.6/site-packages/libagent-0.9.5-py3.6.egg/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/usr/local/lib/python3.6/site-packages/libagent-0.9.5-py3.6.egg/libagent/device/trezor.py", line 90, in connect
    connection.ping(msg='', pin_protection=True)  # unlock PIN
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 129, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 144, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 587, in ping
    return self.call(msg)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 158, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 201, in call
    msg = handler(resp)
  File "/usr/local/lib/python3.6/site-packages/libagent-0.9.5-py3.6.egg/libagent/device/trezor.py", line 64, in ui_handler
    scrambled_pin = pin_entry_gui()
  File "/usr/local/lib/python3.6/site-packages/libagent-0.9.5-py3.6.egg/libagent/device/trezor.py", line 34, in pin_entry_gui
    raise sp.CalledProcessError(exitcode, args)
subprocess.CalledProcessError: Command '['python', '-c', 'import sys, pymsgbox; sys.stdout.write(pymsgbox.password(sys.stdin.read()))']' returned non-zero exit status 1.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by galuszkak** [comment]
@romanz I think it's possible using this:
```
>>> import sys
>>> sys.executable
'/usr/local/opt/python3/bin/python3.6'
```

**Comment by romanz** [comment]
Thanks for the fix - see https://github.com/romanz/trezor-agent/commit/a2d0c1067dbfb4501d442d07500898b7bbd79b88

**Comment by galuszkak** [comment]
OK I have fix, I will do Pull Request.

**Comment by galuszkak** [comment]
ahh :) already tested my fix and it works 👍

**Comment by galuszkak** [comment]
@romanz we can close then. It's working
