### ISSUE TITLE
ledger-agent ssh connection error on Windows

### ISSUE THREAD

**Issue by gstkenpo** [romanz/trezor-agent#158]
Hi all,
I have successfully added the public to my remote machine. However, I have the following error when i try to connect my remote server with the following command.
```
ledger-agent -c -e ed25519 xxx@yyy.mooo.com
```
I have confirmed the ledger is connected properly and pin is typed. Here is the error log.

May I ask for a suggestion? Thanks

```
ledger-agent -c -e ed25519 xxx@yyy.mooo.com
Traceback (most recent call last):
  File "C:\Users\yunkpoon2\AppData\Local\Programs\Python\Python36-32\Scripts\ledger-agent-script.py", line 11, in <module>
    load_entry_point('ledger-agent==0.9.0', 'console_scripts', 'ledger-agent')()
  File "C:\Users\yunkpoon2\AppData\Local\Programs\Python\Python36-32\Scripts\ledger_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "c:\users\yunkpoon2\appdata\local\programs\python\python36-32\lib\site-packages\libagent\ssh\__init__.py", line 137, in wrapper
    return func(*args, **kwargs)
  File "c:\users\yunkpoon2\appdata\local\programs\python\python36-32\lib\site-packages\libagent\ssh\__init__.py", line 227, in main
    timeout=args.timeout)
  File "c:\users\yunkpoon2\appdata\local\programs\python\python36-32\lib\site-packages\libagent\ssh\__init__.py", line 126, in run_server
    with serve(handler=handler, timeout=timeout) as env:
  File "c:\users\yunkpoon2\appdata\local\programs\python\python36-32\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "c:\users\yunkpoon2\appdata\local\programs\python\python36-32\lib\site-packages\libagent\ssh\__init__.py", line 105, in serve
    with server.unix_domain_socket_server(sock_path) as sock:
  File "c:\users\yunkpoon2\appdata\local\programs\python\python36-32\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "c:\users\yunkpoon2\appdata\local\programs\python\python36-32\lib\site-packages\libagent\server.py", line 33, in unix_domain_socket_server
    server = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
AttributeError: module 'socket' has no attribute 'AF_UNIX'
```

**Comment by romanz** [comment]
It seems you are running it on Windows machine. Unfortunately, my library  currently supports only *nix-like systems (e.g. Linux and Mac OS).

@martin-lizner has created a [TREZOR SSH Agent for Windows](https://github.com/martin-lizner/trezor-ssh-agent), but I am not aware of similar support for Ledger Nano S :(

**Comment by gstkenpo** [comment]
oh poor OS. Then I shell close this issue due to the fact that I mis-understand the tool operation platform

**Comment by carstenblt** [comment]
I am switching from macOS to Windows this month and this will be on my list. I believe this shouldn't be too much work.

**Comment by romanz** [comment]
@carstenblt Thanks!
Please let me know if I can help with anything :)

**Comment by carstenblt** [comment]
I hop I'll find time soon! I had a quick look and supporting the native Windows apps for GPG and SSH should be straight forward. They use standard TCP connections and store the port number and a nonce used for access control in a simple file. See https://git.gnupg.org/cgi-bin/gitweb.cgi?p=libassuan.git;a=blob;f=src/assuan-socket.c for the implementation.

Especially for SSH integration with WSL would be nice and this is indeed going to be possible because Microsoft recently introduced AF_UNIX for Windows. Unfortunately Python does not support this yet.

**Comment by romanz** [comment]
@carstenblt Any news?
Please let me know if there is anything I can help with.

**Comment by carstenblt** [comment]
I'll get to it soon!
