### ISSUE TITLE
NanoS never detected on OSX

### ISSUE THREAD

**Issue by talmai** [romanz/trezor-agent#159]
**On my machine...**
```
$ trezor-agent -vv foobar

2017-11-06 12:11:35,208 DEBUG        parsed identity: {'path': None, 'host': 'foobar', 'proto': None, 'port': None, 'user': None}         [interface.py:30]
2017-11-06 12:11:35,208 DEBUG        identity parts: ['ssh://', 'foobar']                                                                 [interface.py:46]
2017-11-06 12:11:35,208 INFO         identity #0: <ssh://foobar|nist256p1>                                                                [__init__.py:201]
Traceback (most recent call last):
  File "/usr/local/bin/trezor-agent", line 11, in <module>
    sys.exit(ssh_agent())
  File "/usr/local/bin/trezor_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/Library/Python/2.7/site-packages/libagent/ssh/__init__.py", line 130, in wrapper
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/libagent/ssh/__init__.py", line 221, in main
    for pk in conn.public_keys():
  File "/Library/Python/2.7/site-packages/libagent/ssh/__init__.py", line 165, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/Library/Python/2.7/site-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/Library/Python/2.7/site-packages/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/Library/Python/2.7/site-packages/libagent/device/trezor.py", line 82, in connect
    raise interface.NotFoundError('{} not connected'.format(self))
libagent.device.interface.NotFoundError: Trezor not connected
```
**Any ideas?**

**Comment by romanz** [comment]
The documentation is probably to blame here...
I have created separate Python packages for TREZOR, Keepkey and Ledger devices ~6 months ago, to reduce the dependencies for each specific installation (before the split, you had to install all devices' dependencies - even when you had a single device).

In order to use the Nano S, please install the `ledger_agent` package from PyPI (see [here](https://github.com/romanz/trezor-agent/blob/master/doc/INSTALL.md#ledger-nano-s) for more details).
It will create `ledger-agent` command (similar to the `trezor-agent` case).

Please let me know if the documentation can be improved to make the installation procedure for Ledger owners easier :)

**Comment by talmai** [comment]
Ugh.. never thought to look for a new package altogether. 

Yes, worked perfectly. Thanks.

**Comment by romanz** [comment]
You're welcome :)
