### ISSUE TITLE
Assertion error trying to add a subkey using ledger-gpg init

### ISSUE THREAD

**Issue by aitorpazos** [romanz/trezor-agent#167]
I was trying to add a new subkey from my Ledger Nano S to an existing key with other subkeys and I'm getting an "AssertionError".
This is the key structure:
```
pub   nistp521 [SC]
sub   nistp521 [E]
sub   rsa4096 [S]
sub   rsa4096 [E]
```
The error seems to be related to the key configuration, as it worked fine with a new key created using default values, adding a subkey to it and then adding the ledger key. However, I don't know how could I fix it using my existing key.

This is the `AssertionError` trace:
```
Traceback (most recent call last):                                      
  File "/usr/bin/ledger-gpg", line 11, in <module>                                                                                                              
    sys.exit(gpg_tool())                                                         
  File "/usr/bin/ledger_agent.py", line 6, in <lambda>                       
    gpg_tool = lambda: libagent.gpg.main(DeviceType)                      
  File "/usr/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 241, in main
    return args.func(device_type=device_type, args=args)                           
  File "/usr/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 134, in run_init                                                                      
    export_public_key(device_type, args))                               
  File "/usr/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 56, in export_public_key                                                               
    signer_func=signer_func)                                                     
  File "/usr/lib/python3.6/site-packages/libagent/gpg/encode.py", line 55, in create_subkey                                                                
    packets = list(decode.parse_packets(io.BytesIO(primary_bytes)))                                                                                        
  File "/usr/lib/python3.6/site-packages/libagent/gpg/decode.py", line 253, in parse_packets                                                                   
    p = packet_type(util.Reader(io.BytesIO(packet_data)))                        
  File "/usr/lib/python3.6/site-packages/libagent/gpg/decode.py", line 153, in _parse_pubkey                                                              
    assert oid in SUPPORTED_CURVES, util.hexlify(oid)                
AssertionError: 2B81040023 
```

**Comment by romanz** [comment]
Thanks for reporting this issue!
I actually never tested it with NISTP521keys...
Will reproduce locally and fix.

**Comment by romanz** [comment]
This is indeed the issue - I need to add support for adding subkeys to NISTP521-based identities.
Currently, the tool supports NISTP256 ED25519, RSA, DSA and ElGamal.

**Comment by romanz** [comment]
AFAIK, no hardware wallet support operation NIST-521 curve, so this tool will only support adding new (not NIST-521) sub-keys to existing (NIST-521) ones.

**Comment by doolio** [comment]
> Currently, the tool supports NIST-P256, Curve25519, RSA, DSA and ElGamal.

My key is a `nistp256` but I only see the following when trying to add a new subkey for signing:

![image](https://github.com/romanz/trezor-agent/assets/13859009/7ef4a6aa-010a-456c-b050-24be72c29388)
