### ISSUE TITLE
Installing from trunk

### ISSUE THREAD

**Issue by jroelofs** [romanz/trezor-agent#181]
I'm struggling to install from trunk. Not sure if I'm holding it wrong, or if I'm missing something:

```
$ trezor-gpg init "Jon Roelofs <jroelofs@jroelofs.com>" -v --time=1514499740
2017-12-28 16:37:18,265 WARNING      This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility! [__init__.py:116]
2017-12-28 16:37:18,298 INFO         device name: trezor                                                                                  [__init__.py:124]
2017-12-28 16:37:18,299 INFO         GPG home directory: /Users/jroelofs/.gnupg/trezor                                                    [__init__.py:126]
2017-12-28 16:37:18,323 WARNING      NOTE: in order to re-generate the exact same GPG key later, run this command with "--time=1514499740" commandline flag (to set the timestamp of the GPG key manually). [__init__.py:34]
Traceback (most recent call last):
  File "/opt/local//Library/Frameworks/Python.framework/Versions/3.6/bin/trezor-gpg", line 11, in <module>
    load_entry_point('trezor-agent', 'console_scripts', 'trezor-gpg')()
  File "/Users/jroelofs/workdir/trezor-agent/agents/trezor/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/Users/jroelofs/workdir/trezor-agent/libagent/gpg/__init__.py", line 255, in main
    return args.func(device_type=device_type, args=args)
  File "/Users/jroelofs/workdir/trezor-agent/libagent/gpg/__init__.py", line 175, in run_init
    export_public_key(device_type, args))
  File "/Users/jroelofs/workdir/trezor-agent/libagent/gpg/__init__.py", line 38, in export_public_key
    verifying_key = c.pubkey(identity=identity, ecdh=False)
  File "/Users/jroelofs/workdir/trezor-agent/libagent/gpg/client.py", line 27, in pubkey
    with self.device:
  File "/Users/jroelofs/workdir/trezor-agent/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/Users/jroelofs/workdir/trezor-agent/libagent/device/trezor.py", line 102, in connect
    for transport in self._defs.Transport.enumerate():
  File "/Users/jroelofs/workdir/trezor-agent/libagent/device/trezor.py", line 39, in _defs
    from . import trezor_defs
  File "/Users/jroelofs/workdir/trezor-agent/libagent/device/trezor_defs.py", line 7, in <module>
    from trezorlib.messages import IdentityType, PassphraseAck, PinMatrixAck
ModuleNotFoundError: No module named 'trezorlib.messages'
```

FAOD, it "just works" when I install directly from pip, but the version from there is a bit outdated.

**Comment by romanz** [comment]
Thanks for reporting this issue!
Please also install the latest [python-trezor](https://github.com/trezor/python-trezor/) version, because the latest `trezor-agent` code depends on the refactored Python interface (https://github.com/romanz/trezor-agent/commit/db16aa3d1ce12e7e1e621decb8911894cd6e7a5f).

**Comment by jroelofs** [comment]
Oooh, thanks! This worked like a charm:

```
sudo pip install -e git+https://github.com/trezor/python-trezor.git#egg=trezor
```

**Comment by romanz** [comment]
You're welcome :)
