### ISSUE TITLE
Ubuntu - ImportError: No module named messages

### ISSUE THREAD

**Issue by pruflyos** [romanz/trezor-agent#191]
I installed `trezor-agent` according to the instructions on Ubuntu 16.04 (python2.7), but always get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/trezor-agent", line 11, in <module>
    sys.exit(ssh_agent())
  File "/usr/local/bin/trezor_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/usr/local/lib/python2.7/dist-packages/libagent/ssh/__init__.py", line 145, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/libagent/ssh/__init__.py", line 237, in main
    for pk in conn.public_keys():
  File "/usr/local/lib/python2.7/dist-packages/libagent/ssh/__init__.py", line 180, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/usr/local/lib/python2.7/dist-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/usr/local/lib/python2.7/dist-packages/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/usr/local/lib/python2.7/dist-packages/libagent/device/trezor.py", line 107, in connect
    for transport in self._defs.Transport.enumerate():
  File "/usr/local/lib/python2.7/dist-packages/libagent/device/trezor.py", line 44, in _defs
    from . import trezor_defs
  File "/usr/local/lib/python2.7/dist-packages/libagent/device/trezor_defs.py", line 7, in <module>
    from trezorlib.messages import IdentityType, PassphraseAck, PinMatrixAck
ImportError: No module named messages
```

**Comment by Wheest** [comment]
Have a swatch at [https://github.com/romanz/trezor-agent/issues/181](181), installing python-trezor first worked for me.  Installed via cloned github repos rather than the pip one

**Comment by romanz** [comment]
Thanks for opening the issue!
Indeed, the latest `trezor-agent` package now requires the latest `trezorlib` version, which can be installed using:
```
$ pip install -e git+https://github.com/trezor/python-trezor.git#egg=trezor
```
