### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by brotonmail** [romanz/trezor-agent#195]
I installed trezor-agent on Debian 9. First I got the error "ImportError: No module named messages" After first installing python-trezor with pip install -e git+https://github.com/trezor/python-trezor.git#egg=trezor I now get this issue.

```
Traceback (most recent call last):
  File "/home/user/.local/bin/trezor-agent", line 11, in <module>
    load_entry_point('trezor-agent', 'console_scripts', 'trezor-agent')()
  File "/home/user/trezor-agent/agents/trezor/trezor_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/home/user/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 145, in wrapper
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 237, in main
    for pk in conn.public_keys():
  File "/home/user/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 180, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/home/user/.local/lib/python2.7/site-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/home/user/.local/lib/python2.7/site-packages/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/home/user/.local/lib/python2.7/site-packages/libagent/device/trezor.py", line 107, in connect
    for transport in self._defs.Transport.enumerate():
  File "/home/user/.local/lib/python2.7/site-packages/libagent/device/trezor.py", line 44, in _defs
    from . import trezor_defs
  File "/home/user/.local/lib/python2.7/site-packages/libagent/device/trezor_defs.py", line 10, in <module>
    from trezorlib.transport_udp import UdpTransport
  File "/home/user/.local/bin/src/trezor/trezorlib/transport_udp.py", line 59
    return "%s:%s:%s" % (self.PATH_PREFIX, *self.device)
                                           ^
SyntaxError: invalid syntax
```

**Comment by romanz** [comment]
Thanks for reporting this issue!

**Comment by romanz** [comment]
It seems that the latest `trezorlib` code is using Python3-only feature ([see PEP 448](https://www.python.org/dev/peps/pep-0448/)).
Could you try to re-install it (and `trezor-agent`) using `pip3`?

**Comment by brotonmail** [comment]
Yes! Installing with pip3 worked. Thank you guys!

**Comment by romanz** [comment]
You're welcome :)
