### ISSUE TITLE
Error with latest version from master (0.9.1?)

### ISSUE THREAD

**Issue by Flink** [romanz/trezor-agent#199]
I tried to update directly with `pip`, it wasn’t installing, I have the following error:
```
Collecting trezor_agent
  Using cached trezor_agent-0.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/libagent.egg-info
    writing pip-egg-info/libagent.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/libagent.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/libagent.egg-info/requires.txt
    writing top-level names to pip-egg-info/libagent.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/libagent.egg-info/SOURCES.txt'
    error: package directory 'libagent' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jqdxqtaw/trezor-agent/
```

Then tried with the source directly and now when calling `trezor-gpg unlock` I have the following error:
```
Traceback (most recent call last):
  File "/usr/bin/trezor-agent", line 11, in <module>
    load_entry_point('trezor-agent', 'console_scripts', 'trezor-agent')()
  File "/home/flink/Coding/github/trezor-agent/agents/trezor/trezor_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/usr/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 137, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 229, in main
    for pk in conn.public_keys():
  File "/usr/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 172, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/usr/lib/python3.6/site-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/usr/lib/python3.6/site-packages/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/usr/lib/python3.6/site-packages/libagent/device/trezor.py", line 60, in connect
    for d in self._defs.Transport.enumerate():
  File "/usr/lib/python3.6/site-packages/libagent/device/trezor.py", line 20, in _defs
    from . import trezor_defs
  File "/usr/lib/python3.6/site-packages/libagent/device/trezor_defs.py", line 8, in <module>
    from trezorlib.transport_bridge import BridgeTransport
  File "/usr/lib/python3.6/site-packages/trezorlib/transport_bridge.py", line 5, in <module>
    from . import protobuf_json
  File "/usr/lib/python3.6/site-packages/trezorlib/protobuf_json.py", line 106, in <module>
    FD.TYPE_INT64: long,
NameError: name 'long' is not defined
```
Any idea? 😕

**Comment by romanz** [comment]
Please update the `trezor` package to the [latest version](https://pypi.python.org/pypi/trezor) from PyPI (the old version didn't Python 3):

```
$ pip3 install -U trezor
```

**Comment by Flink** [comment]
Already did, does not change the `pip install` error.

**Comment by romanz** [comment]
It seems that there is an old version of `trezor` package installed at `/usr/lib/python3.6/site-packages/trezorlib/` (since the `protobuf_json.py` module was removed at https://github.com/trezor/python-trezor/commit/f73fc334395a1cb28744d1fea54efc7dd34c742e).

Could you uninstall the globally installed `trezor` package using `sudo pip3 uninstall trezor` - and try to re-install the latest version instead?

Also, could you please use https://asciinema.org/ to record the full execution of the failing command?

**Comment by Flink** [comment]
Completely removed `trezor` packages and `trezor-agent`, reinstalled `trezor`. I still can’t install the `0.9.1` version of `trezor-agent` which is the latest version on `pip` (giving the error above) but if I force `pip` to install `0.9.0` then all is working again 🙂

**Comment by romanz** [comment]
Thanks for the reporting - I reproduced the installation issue using a virtualenv:
```
$ python3 -m venv .env
/tmp $ . .env/bin/activate
(.env) 0 /tmp $ pip install trezor_agent
Collecting trezor_agent
  Downloading trezor_agent-0.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/libagent.egg-info
    writing requirements to pip-egg-info/libagent.egg-info/requires.txt
    writing pip-egg-info/libagent.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/libagent.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/libagent.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/libagent.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    error: package directory 'libagent' does not exist
```

**Comment by romanz** [comment]
Well, it's my mistake - I've uploaded a broken tarball :(

**Comment by Flink** [comment]
Ah ok 😉 It’s time for a `0.9.2` version then 😄

**Comment by romanz** [comment]
Please try now: https://pypi.python.org/pypi/trezor_agent/0.9.2

**Comment by Flink** [comment]
Works fine! Thanks :+1: :beers: :grin:

**Comment by romanz** [comment]
You're welcome, and thanks again for the report :)
