### ISSUE TITLE
Trezor Model T: libagent.device.interface.NotFoundError: Trezor not connected

### ISSUE THREAD

**Issue by pruflyos** [romanz/trezor-agent#213]
I upgraded to the latest trezor-agent using python3.5. I can successfully conncet via SSH using `Trezor One` but no success with `Trezor Model T`.

By the way, `trezorctl` works fine with `Model T` only `trezor-agent` has a problem.

```
$ trezor-agent -c pruflyos@127.0.0.1
2018-03-08 13:19:27,323 WARNING      error: Trezor not connected                                                                          [server.py:63]
Traceback (most recent call last):
  File "/home/pruflyos/.local/lib/python3.5/site-packages/libagent/server.py", line 58, in handle_connection
    reply = handler.handle(msg=msg)
  File "/home/pruflyos/.local/lib/python3.5/site-packages/libagent/ssh/protocol.py", line 103, in handle
    reply = method(buf=buf)
  File "/home/pruflyos/.local/lib/python3.5/site-packages/libagent/ssh/protocol.py", line 111, in list_pubs
    keys = self.conn.parse_public_keys()
  File "/home/pruflyos/.local/lib/python3.5/site-packages/libagent/ssh/__init__.py", line 198, in parse_public_keys
    for pk in self.public_keys()]
  File "/home/pruflyos/.local/lib/python3.5/site-packages/libagent/ssh/__init__.py", line 192, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/home/pruflyos/.local/lib/python3.5/site-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/home/pruflyos/.local/lib/python3.5/site-packages/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/home/pruflyos/.local/lib/python3.5/site-packages/libagent/device/trezor.py", line 126, in connect
    raise interface.NotFoundError('{} not connected'.format(self))
libagent.device.interface.NotFoundError: Trezor not connected
Permission denied (publickey).
```

**Comment by pruflyos** [comment]
After uninstalling all python3 packages and re-installing `trezor-agent` from the sources, I don't get this error anymore. Closing.
