### ISSUE TITLE
Model T: errors when providing password

### ISSUE THREAD

**Issue by pruflyos** [romanz/trezor-agent#214]
Using `Trezor Model T` for SSH login I always get an error when asked how I want to enter the password.

1. I get the following error when chosing to enter the password via the `Device` (Touchscreen):
```
$ trezor-agent -c pruflyos@127.0.0.1
2018-03-08 00:00:00,00 WARNING      error: object of type 'NoneType' has no len()                                                        [server.py:63]
Traceback (most recent call last):
  File "/home/pruflyos/trezor-agent/libagent/server.py", line 58, in handle_connection
    reply = handler.handle(msg=msg)
  File "/home/pruflyos/trezor-agent/libagent/ssh/protocol.py", line 103, in handle
    reply = method(buf=buf)
  File "/home/pruflyos/trezor-agent/libagent/ssh/protocol.py", line 111, in list_pubs
    keys = self.conn.parse_public_keys()
  File "/home/pruflyos/trezor-agent/libagent/ssh/__init__.py", line 200, in parse_public_keys
    for pk in self.public_keys()]
  File "/home/pruflyos/trezor-agent/libagent/ssh/__init__.py", line 194, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/home/pruflyos/trezor-agent/libagent/ssh/client.py", line 26, in export_public_keys
    pubkey = self.device.pubkey(identity=i)
  File "/home/pruflyos/trezor-agent/libagent/device/trezor.py", line 157, in pubkey
    n=addr, ecdsa_curve_name=curve_name)
  File "/home/pruflyos/python-trezor/trezorlib/client.py", line 177, in wrapped_f
    ret = f(*args, **kwargs)
  File "/home/pruflyos/python-trezor/trezorlib/client.py", line 557, in get_public_node
    return self.call(proto.GetPublicKey(address_n=n, ecdsa_curve_name=ecdsa_curve_name, show_display=show_display, coin_name=coin_name))
  File "/home/pruflyos/python-trezor/trezorlib/client.py", line 191, in wrapped_f
    return f(*args, **kwargs)
  File "/home/pruflyos/python-trezor/trezorlib/client.py", line 235, in call
    resp = self.call(msg)
  File "/home/pruflyos/python-trezor/trezorlib/client.py", line 191, in wrapped_f
    return f(*args, **kwargs)
  File "/home/pruflyos/python-trezor/trezorlib/client.py", line 232, in call
    msg = handler(resp)
  File "/home/pruflyos/trezor-agent/libagent/device/trezor.py", line 93, in new_handler
    length = len(ack.passphrase)
TypeError: object of type 'NoneType' has no len()
Permission denied (publickey).
```

2. I get the following error when providing the password via the `Host` (keyboard):
```
$ trezor-agent -c pruflyos@127.0.0.1
Passphrase required: 

Confirm your Passphrase: 

2018-03-08 00:00:00,000 WARNING      error:                                                                                               [server.py:63]
Traceback (most recent call last):
  File "/home/pruflyos/trezor-agent/libagent/server.py", line 58, in handle_connection
    reply = handler.handle(msg=msg)
  File "/home/pruflyos/trezor-agent/libagent/ssh/protocol.py", line 103, in handle
    reply = method(buf=buf)
  File "/home/pruflyos/trezor-agent/libagent/ssh/protocol.py", line 111, in list_pubs
    keys = self.conn.parse_public_keys()
  File "/home/pruflyos/trezor-agent/libagent/ssh/__init__.py", line 200, in parse_public_keys
    for pk in self.public_keys()]
  File "/home/pruflyos/trezor-agent/libagent/ssh/__init__.py", line 194, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/home/pruflyos/trezor-agent/libagent/ssh/client.py", line 28, in export_public_keys
    curve_name=i.curve_name)
  File "/home/pruflyos/trezor-agent/libagent/formats.py", line 148, in decompress_pubkey
    vk = decompress(pubkey)
  File "/home/pruflyos/trezor-agent/libagent/formats.py", line 128, in _decompress_nist256
    point = ecdsa.ellipticcurve.Point(curve.curve, x, y)
  File "/usr/local/lib/python3.5/dist-packages/ecdsa/ellipticcurve.py", line 73, in __init__
    if self.__curve: assert self.__curve.contains_point( x, y )
AssertionError
Permission denied (publickey).
```

**Comment by pruflyos** [comment]
I installed `trezor-agent` from the latest sources.
I have to use `sudo` unfortunately, because the install script `setup.py` tries to write something to `/usr/local/lib/python3.5/dist-packages/`. 

Here's my current setup and dependencies:
```
$ cd trezor-agent
$ git pull
$ sudo -H pip3 install -e .
Obtaining file:///home/pruflyos/trezor-agent
Requirement already satisfied: backports.shutil_which>=3.5.1 in /usr/local/lib/python3.5/dist-packages (from libagent==0.10.0)
Requirement already satisfied: ConfigArgParse>=0.12.0 in /usr/local/lib/python3.5/dist-packages (from libagent==0.10.0)
Requirement already satisfied: python-daemon>=2.1.2 in /usr/local/lib/python3.5/dist-packages (from libagent==0.10.0)
Requirement already satisfied: ecdsa>=0.13 in /usr/local/lib/python3.5/dist-packages (from libagent==0.10.0)
Requirement already satisfied: ed25519>=1.4 in /usr/local/lib/python3.5/dist-packages (from libagent==0.10.0)
Requirement already satisfied: mnemonic>=0.18 in /usr/local/lib/python3.5/dist-packages (from libagent==0.10.0)
Requirement already satisfied: pymsgbox>=1.0.6 in /usr/local/lib/python3.5/dist-packages (from libagent==0.10.0)
Requirement already satisfied: semver>=2.2 in /usr/local/lib/python3.5/dist-packages (from libagent==0.10.0)
Requirement already satisfied: unidecode>=0.4.20 in /usr/local/lib/python3.5/dist-packages (from libagent==0.10.0)
Requirement already satisfied: docutils in /usr/local/lib/python3.5/dist-packages (from python-daemon>=2.1.2->libagent==0.10.0)
Requirement already satisfied: lockfile>=0.10 in /usr/local/lib/python3.5/dist-packages (from python-daemon>=2.1.2->libagent==0.10.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from python-daemon>=2.1.2->libagent==0.10.0)
Requirement already satisfied: pbkdf2 in /usr/local/lib/python3.5/dist-packages (from mnemonic>=0.18->libagent==0.10.0)
Installing collected packages: libagent
  Found existing installation: libagent 0.10.0
    Can't uninstall 'libagent'. No files were found to uninstall.
  Running setup.py develop for libagent
Successfully installed libagent

$ sudo -H pip3 install -e agents/trezor/
Obtaining file:///home/pruflyos/trezor-agent/agents/trezor
Requirement already satisfied: libagent>=0.9.0 in /home/pruflyos/trezor-agent (from trezor-agent==0.9.2)
Requirement already satisfied: trezor>=0.9.0 in /home/pruflyos/python-trezor (from trezor-agent==0.9.2)
Requirement already satisfied: backports.shutil_which>=3.5.1 in /usr/local/lib/python3.5/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: ConfigArgParse>=0.12.0 in /usr/local/lib/python3.5/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: python-daemon>=2.1.2 in /usr/local/lib/python3.5/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: ecdsa>=0.13 in /usr/local/lib/python3.5/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: ed25519>=1.4 in /usr/local/lib/python3.5/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: mnemonic>=0.18 in /usr/local/lib/python3.5/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: pymsgbox>=1.0.6 in /usr/local/lib/python3.5/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: semver>=2.2 in /usr/local/lib/python3.5/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: unidecode>=0.4.20 in /usr/local/lib/python3.5/dist-packages (from libagent>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: setuptools>=19.0 in /usr/lib/python3/dist-packages (from trezor>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: requests>=2.4.0 in /usr/local/lib/python3.5/dist-packages (from trezor>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: click>=6.2 in /usr/local/lib/python3.5/dist-packages (from trezor>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: pyblake2>=0.9.3 in /usr/local/lib/python3.5/dist-packages (from trezor>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: rlp>=0.6.0 in /usr/local/lib/python3.5/dist-packages (from trezor>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: hidapi>=0.7.99.post20 in /usr/local/lib/python3.5/dist-packages (from trezor>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: libusb1>=1.6.4 in /usr/local/lib/python3.5/dist-packages (from trezor>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: docutils in /usr/local/lib/python3.5/dist-packages (from python-daemon>=2.1.2->libagent>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: lockfile>=0.10 in /usr/local/lib/python3.5/dist-packages (from python-daemon>=2.1.2->libagent>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: pbkdf2 in /usr/local/lib/python3.5/dist-packages (from mnemonic>=0.18->libagent>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests>=2.4.0->trezor>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests>=2.4.0->trezor>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests>=2.4.0->trezor>=0.9.0->trezor-agent==0.9.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests>=2.4.0->trezor>=0.9.0->trezor-agent==0.9.2)
Installing collected packages: trezor-agent
  Found existing installation: trezor-agent 0.9.2
    Can't uninstall 'trezor-agent'. No files were found to uninstall.
  Running setup.py develop for trezor-agent
Successfully installed trezor-agent
```

**Comment by romanz** [comment]
Regarding https://github.com/romanz/trezor-agent/issues/214#issuecomment-371549578 - you can install it (without `sudo`) using:
```
$ pip3 install --user -e .
```

**Comment by pruflyos** [comment]
The first problem is solved, but there's still an error regarding the elliptic curve point similar to the second one before. The error is identical now for both input methods - `device` and `host`:

```
$ trezor-agent pruflyos@127.0.0.1
Traceback (most recent call last):
  File "/home/pruflyos/.local/bin/trezor-agent", line 11, in <module>
    load_entry_point('trezor-agent', 'console_scripts', 'trezor-agent')()
  File "/home/pruflyos/trezor-agent/agents/trezor/trezor_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/home/pruflyos/trezor-agent/libagent/ssh/__init__.py", line 164, in wrapper
    return func(*args, **kwargs)
  File "/home/pruflyos/trezor-agent/libagent/ssh/__init__.py", line 287, in main
    for pk in conn.public_keys():
  File "/home/pruflyos/trezor-agent/libagent/ssh/__init__.py", line 199, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/home/pruflyos/trezor-agent/libagent/ssh/client.py", line 28, in export_public_keys
    curve_name=i.curve_name)
  File "/home/pruflyos/trezor-agent/libagent/formats.py", line 148, in decompress_pubkey
    vk = decompress(pubkey)
  File "/home/pruflyos/trezor-agent/libagent/formats.py", line 128, in _decompress_nist256
    point = ecdsa.ellipticcurve.Point(curve.curve, x, y)
  File "/home/pruflyos/.local/lib/python3.5/site-packages/ecdsa/ellipticcurve.py", line 73, in __init__
    if self.__curve: assert self.__curve.contains_point( x, y )
AssertionError
```
