### ISSUE TITLE
Not working on macOS High Sierra with Trezor T

### ISSUE THREAD

**Issue by JediWed** [romanz/trezor-agent#215]
Installed via `pip3 install trezor_agent`.

Getting following message: 

```
2018-03-10 22:15:28,963 ERROR        Connection error (try unplugging and replugging your device): Trezor not connected                   [__init__.py:159]
```

**Comment by romanz** [comment]
Thanks for reporting this issue!
I have uploaded the latest version to PyPI: https://pypi.python.org/pypi/libagent/0.11.0

Please update it using:
```
$ pip3 install -U libagent
```

**Comment by JediWed** [comment]
Still not working:

Traceback (most recent call last):
  File "/usr/local/bin/trezor-agent", line 11, in <module>
    load_entry_point('trezor-agent==0.9.2', 'console_scripts', 'trezor-agent')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/bin/trezor_agent.py", line 1, in <module>
    import libagent.gpg
  File "/usr/local/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 25, in <module>
    from . import agent, client, encode, keyring, protocol
  File "/usr/local/lib/python3.6/site-packages/libagent/gpg/agent.py", line 5, in <module>
    from . import client, decode, keyring, protocol
  File "/usr/local/lib/python3.6/site-packages/libagent/gpg/client.py", line 6, in <module>
    from ..device import interface
  File "/usr/local/lib/python3.6/site-packages/libagent/device/__init__.py", line 3, in <module>
    from . import interface, ui
ImportError: cannot import name 'ui'

(macOS High Sierra)

**Comment by BitCryptex** [comment]
Same issue as above on Ubuntu 16.04 after update.

**Comment by romanz** [comment]
My bad - should be fixed at https://github.com/romanz/trezor-agent/commit/34c03a462ce4b099ca933cfbaf509da4781aa9d4.
Please update to https://pypi.python.org/pypi/libagent/0.11.1.

**Comment by romanz** [comment]
BTW, we'll need to wait for a new official version of TREZOR model T firmware (since the current one has an issue with public key generation - which is fixed at https://github.com/trezor/trezor-core/commit/1b8217ca669338cec9c1c8149a206d2d4d0c37d0).

**Comment by JediWed** [comment]
Is that the reason for:

Traceback (most recent call last):
  File "/usr/local/bin/trezor-agent", line 11, in <module>
    load_entry_point('trezor-agent==0.9.2', 'console_scripts', 'trezor-agent')()
  File "/usr/local/bin/trezor_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 164, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 287, in main
    for pk in conn.public_keys():
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 199, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/client.py", line 28, in export_public_keys
    curve_name=i.curve_name)
  File "/usr/local/lib/python3.6/site-packages/libagent/formats.py", line 148, in decompress_pubkey
    vk = decompress(pubkey)
  File "/usr/local/lib/python3.6/site-packages/libagent/formats.py", line 128, in _decompress_nist256
    point = ecdsa.ellipticcurve.Point(curve.curve, x, y)
  File "/usr/local/lib/python3.6/site-packages/ecdsa/ellipticcurve.py", line 73, in __init__
    if self.__curve: assert self.__curve.contains_point( x, y )
AssertionError


?

**Comment by romanz** [comment]
Yes...

**Comment by JediWed** [comment]
Okay let's wait for an update :) 
Thanks for you fast support.

**Comment by Flink** [comment]
@romanz I was just about to report a new bug saying that I can’t use the ssh agent anymore with the new model T (it’s still working fine with the Trezor One) but I guess that’s the same problem as `trezor-agent` complains about an invalid public key (`signature status: ERROR` and so on) :sweat_smile:

**Comment by romanz** [comment]
Should be resolved at [2.0.6](https://github.com/trezor/trezor-core/releases/tag/v2.0.6) firmware.
It can be downloaded from https://github.com/trezor/webwallet-data/tree/master/firmware/2.

**Comment by romanz** [comment]
It can be installed from [beta-wallet.trezor.io](beta-wallet.trezor.io) or by entering the bootloader mode on TREZOR model T (by tapping on the touchscreen during the boot) and running:
```
$ trezorctl firmware_update -f firmware/1/trezor-2.0.6.bin
```

**Comment by Flink** [comment]
@romanz Just updated to the latest firmware and tested: it works :tada: :+1: :grin:
