### ISSUE TITLE
Cannot get GPG running with Ledger Nano S again

### ISSUE THREAD

**Issue by fansari** [romanz/trezor-agent#222]
Hi Roman,

after some months I tried again to use ledger-gpg but I cannot do it anymore.

I installed the latest code from GitHub.

GNUPGHOME is set.

```
[fansari@bat ledger]$ echo $GNUPGHOME
/home/fansari/.gnupg/ledger
```
A secret key is avaialbe:

```
[fansari@bat ledger]$ gpg2 -k
/home/fansari/.gnupg/ledger/pubring.kbx
---------------------------------------
pub   nistp256 2017-05-20 [SC]
      F75129D15FA6BEC33D9B29E3335F1B084AEAD372
uid           [ultimate] Frank Ansari <mail@frank-ansari.de>
sub   nistp256 2017-05-20 [E]
```
Now I ran a test:

```
[fansari@bat ledger]$ echo "Hello World!" | gpg2 --sign
gpg: keydb_search failed: Broken pipe
gpg: no default secret key: Broken pipe
gpg: signing failed: Broken pipe
```
In case you need this output:
```
[fansari@bat ledger]$ gpg2 --export | gpg2 --list-packets
# off=0 ctb=98 tag=6 hlen=2 plen=82
:public key packet:
        version 4, algo 19, created 1495285382, expires 0
        pkey[0]: [72 bits] nistp256 (1.2.840.10045.3.1.7)
        pkey[1]: [515 bits]
        keyid: 335F1B084AEAD372
# off=84 ctb=b4 tag=13 hlen=2 plen=35
:user ID packet: "Frank Ansari <mail@frank-ansari.de>"
# off=121 ctb=88 tag=2 hlen=2 plen=121
:signature packet: algo 19, keyid 335F1B084AEAD372
        version 4, created 1495285382, md5len 0, sigclass 0x13
        digest algo 8, begin of digest 42 5a
        hashed subpkt 2 len 4 (sig created 2017-05-20)
        hashed subpkt 11 len 1 (pref-sym-algos: 9)
        hashed subpkt 27 len 1 (key flags: 03)
        hashed subpkt 21 len 1 (pref-hash-algos: 8)
        hashed subpkt 22 len 1 (pref-zip-algos: 0)
        hashed subpkt 23 len 1 (keyserver preferences: 80)
        subpkt 16 len 8 (issuer key ID 335F1B084AEAD372)
        subpkt 26 len 10 (policy: TREZOR-GPG)
        data: [256 bits]
        data: [252 bits]
# off=244 ctb=b8 tag=14 hlen=2 plen=86
:public sub key packet:
        version 4, algo 18, created 1495285382, expires 0
        pkey[0]: [72 bits] nistp256 (1.2.840.10045.3.1.7)
        pkey[1]: [515 bits]
        pkey[2]: [32 bits]
        keyid: 80ACE17E008B858F
# off=332 ctb=88 tag=2 hlen=2 plen=109
:signature packet: algo 19, keyid 335F1B084AEAD372
        version 4, created 1495285382, md5len 0, sigclass 0x18
        digest algo 8, begin of digest e2 58
        hashed subpkt 2 len 4 (sig created 2017-05-20)
        hashed subpkt 27 len 1 (key flags: 0C)
        subpkt 16 len 8 (issuer key ID 335F1B084AEAD372)
        subpkt 26 len 10 (policy: TREZOR-GPG)
        data: [256 bits]
        data: [255 bits]
```

**Comment by romanz** [comment]
Could you please run `trezor-gpg-agent -vv` from command-line and attach its log?

**Comment by romanz** [comment]
Also, please attach `~/.gnupg/ledger/gpg-agent.log` if possible.

**Comment by fansari** [comment]
```
fansari@bat ledger]$ ledger-gpg-agent -vv
2018-03-18 19:32:39,342 DEBUG        serving on /run/user/1000/gnupg/d.fwxzikfp74tcffudc7ykwut1/S.gpg-agent                               [server.py:30]
2018-03-18 19:32:39,342 DEBUG        waiting for connection on /run/user/1000/gnupg/d.fwxzikfp74tcffudc7ykwut1/S.gpg-agent                [agent.py:14]
```

**Comment by fansari** [comment]
```
[fansari@bat ledger]$ cat gpg-agent.log
2018-03-18 19:30:10,550 DEBUG        serving on /run/user/1000/gnupg/d.fwxzikfp74tcffudc7ykwut1/S.gpg-agent                               [server.py:30]
2018-03-18 19:30:10,550 DEBUG        waiting for connection on /run/user/1000/gnupg/d.fwxzikfp74tcffudc7ykwut1/S.gpg-agent                [agent.py:14]
2018-03-18 19:30:10,643 DEBUG        accepted connection on /run/user/1000/gnupg/d.fwxzikfp74tcffudc7ykwut1/S.gpg-agent                   [agent.py:20]
2018-03-18 19:30:10,650 DEBUG        <- 'OK'                                                                                              [keyring.py:41]
2018-03-18 19:30:10,650 DEBUG        -> 'RESET'                                                                                           [keyring.py:59]
2018-03-18 19:30:10,650 DEBUG        <- 'OK'                                                                                              [keyring.py:41]
2018-03-18 19:30:10,650 DEBUG        -> 'OPTION ttytype=linux'                                                                            [keyring.py:59]
2018-03-18 19:30:10,650 DEBUG        <- 'OK'                                                                                              [keyring.py:41]
2018-03-18 19:30:10,651 DEBUG        -> 'OPTION display=:0'                                                                               [keyring.py:59]
2018-03-18 19:30:10,651 DEBUG        <- 'OK'                                                                                              [keyring.py:41]
2018-03-18 19:30:10,651 DEBUG        -> 'OPTION putenv=XMODIFIERS=@im=ibus'                                                               [keyring.py:59]
2018-03-18 19:30:10,651 DEBUG        <- 'OK'                                                                                              [keyring.py:41]
2018-03-18 19:30:10,651 DEBUG        -> 'OPTION putenv=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus'                             [keyring.py:59]
2018-03-18 19:30:10,651 DEBUG        <- 'OK'                                                                                              [keyring.py:41]
2018-03-18 19:30:10,651 DEBUG        -> 'OPTION putenv=QT_IM_MODULE=ibus'                                                                 [keyring.py:59]
2018-03-18 19:30:10,651 DEBUG        <- 'OK'                                                                                              [keyring.py:41]
2018-03-18 19:30:10,651 DEBUG        -> 'GETINFO version'                                                                                 [keyring.py:59]
2018-03-18 19:30:10,651 DEBUG        <- 'D 2.2.5'                                                                                         [keyring.py:41]
2018-03-18 19:30:10,651 DEBUG        <- 'OK'                                                                                              [keyring.py:41]
2018-03-18 19:30:10,652 DEBUG        -> 'OPTION allow-pinentry-notify'                                                                    [keyring.py:59]
2018-03-18 19:30:10,652 DEBUG        <- 'OK'                                                                                              [keyring.py:41]
2018-03-18 19:30:10,652 DEBUG        -> 'OPTION agent-awareness=2.1.0'                                                                    [keyring.py:59]
2018-03-18 19:30:10,652 DEBUG        <- 'OK'                                                                                              [keyring.py:41]
2018-03-18 19:30:10,652 DEBUG        -> 'SCD SERIALNO openpgp'                                                                            [keyring.py:59]
2018-03-18 19:30:10,652 ERROR        unknown request: 'SCD SERIALNO openpgp'                                                              [agent.py:168]
2018-03-18 19:30:10,652 DEBUG        waiting for connection on /run/user/1000/gnupg/d.fwxzikfp74tcffudc7ykwut1/S.gpg-agent                [agent.py:14]
2018-03-18 19:32:39,342 DEBUG        serving on /run/user/1000/gnupg/d.fwxzikfp74tcffudc7ykwut1/S.gpg-agent                               [server.py:30]
2018-03-18 19:32:39,342 DEBUG        waiting for connection on /run/user/1000/gnupg/d.fwxzikfp74tcffudc7ykwut1/S.gpg-agent                [agent.py:14]
```

**Comment by romanz** [comment]
It seems that `trezor-gpg-agent` fails to respond correctly to `SCD SERIALNO openpgp` command, which wasn't sent at previous GPG versions.

**Comment by romanz** [comment]
Let me try to install the latest GPG on a VM, to see what the correct response should be.
BTW, which OS/distro are you using?

**Comment by romanz** [comment]
It seems to run correctly on the latest `trezor-agent`:
```
 echo 123 | gpg -sa | gpg --verify
2018-03-18 19:20:05,933 DEBUG        accepted connection on /run/user/1001/gnupg/d.mppaigfowm4c1ab53zbmyo6s/S.gpg-agent                   [agent.py:20]
2018-03-18 19:20:05,933 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
2018-03-18 19:20:05,933 DEBUG        -> b'RESET'                                                                                          [keyring.py:71]
2018-03-18 19:20:05,934 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
2018-03-18 19:20:05,934 DEBUG        -> b'OPTION ttytype=xterm-256color'                                                                  [keyring.py:71]
2018-03-18 19:20:05,934 DEBUG        options: [b'ttytype=xterm-256color']                                                                 [agent.py:124]
2018-03-18 19:20:05,934 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
2018-03-18 19:20:05,934 DEBUG        -> b'GETINFO version'                                                                                [keyring.py:71]
2018-03-18 19:20:05,934 DEBUG        <- b'D 2.2.5'                                                                                        [keyring.py:53]
2018-03-18 19:20:05,934 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
2018-03-18 19:20:05,934 DEBUG        -> b'OPTION allow-pinentry-notify'                                                                   [keyring.py:71]
2018-03-18 19:20:05,934 DEBUG        options: [b'ttytype=xterm-256color', b'allow-pinentry-notify']                                       [agent.py:124]
2018-03-18 19:20:05,935 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
2018-03-18 19:20:05,935 DEBUG        -> b'OPTION agent-awareness=2.1.0'                                                                   [keyring.py:71]
2018-03-18 19:20:05,935 DEBUG        options: [b'ttytype=xterm-256color', b'allow-pinentry-notify', b'agent-awareness=2.1.0']             [agent.py:124]
2018-03-18 19:20:05,935 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
2018-03-18 19:20:05,935 DEBUG        -> b'SCD SERIALNO openpgp'                                                                           [keyring.py:71]
2018-03-18 19:20:05,935 DEBUG        <- b'ERR 100696144 No such device <SCD>'                                                             [keyring.py:53]
2018-03-18 19:20:05,935 DEBUG        -> b'HAVEKEY 95852E917FE2C39152BA998192B5791DB15CDCF0'                                               [keyring.py:71]
2018-03-18 19:20:05,935 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
gpg: using "FooBar" as default secret key for signing
2018-03-18 19:20:05,936 DEBUG        -> b'HAVEKEY 95852E917FE2C39152BA998192B5791DB15CDCF0 95852E917FE2C39152BA998192B5791DB15CDCF0'      [keyring.py:71]
2018-03-18 19:20:05,936 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
2018-03-18 19:20:05,936 DEBUG        -> b'RESET'                                                                                          [keyring.py:71]
2018-03-18 19:20:05,936 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
2018-03-18 19:20:05,937 DEBUG        -> b'SIGKEY 95852E917FE2C39152BA998192B5791DB15CDCF0'                                                [keyring.py:71]
2018-03-18 19:20:05,937 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
2018-03-18 19:20:05,937 DEBUG        -> b'SETKEYDESC Please+enter+the+passphrase+to+unlock+the+OpenPGP+secret+key:%0A%22FooBar%22%0A256-bit+ECDSA+key,+ID+9A214ED4A9F2E2B5,%0Acreated+2018-03-18.%0A' [keyring.py:71]
2018-03-18 19:20:05,937 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
2018-03-18 19:20:05,937 DEBUG        -> b'SETHASH 10 E1C871CBDD35DCBEA4570DE86F61242DBBA86AEFFCBDCF62A4ECCF1B6433B5C30F15596607A6C8286534339C53FC0DFC3FE27F3DF5491E7855086A6D8E013D91' [keyring.py:71]
2018-03-18 19:20:05,937 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
2018-03-18 19:20:05,937 DEBUG        -> b'PKSIGN'                                                                                         [keyring.py:71]
2018-03-18 19:20:05,937 DEBUG        signing b'E1C871CBDD35DCBEA4570DE86F61242DBBA86AEFFCBDCF62A4ECCF1B6433B5C30F15596607A6C8286534339C53FC0DFC3FE27F3DF5491E7855086A6D8E013D91' digest (algo #b'10') [agent.py:161]
2018-03-18 19:20:05,937 DEBUG        identity parts: ['gpg://', 'FooBar']                                                                 [interface.py:46]
2018-03-18 19:20:05,937 INFO         please confirm GPG signature on FakeDevice for "<gpg://FooBar|nist256p1>"...                         [client.py:35]
2018-03-18 19:20:05,938 DEBUG        signing digest: E1C871CBDD35DCBEA4570DE86F61242DBBA86AEFFCBDCF62A4ECCF1B6433B5C3                     [client.py:38]
2018-03-18 19:20:05,938 CRITICAL     NEVER USE THIS CODE FOR REAL-LIFE USE-CASES!!!                                                       [fake_device.py:31]
2018-03-18 19:20:05,938 CRITICAL     ONLY FOR DEBUGGING AND TESTING!!!                                                                    [fake_device.py:32]
2018-03-18 19:20:05,970 DEBUG        result: b'(7:sig-val(5:ecdsa(1:r32:C\x93\xdaK\xc1E\xddrl?q\x9a\xd4\x00\xbc\x12\xe6\x93u\xae8?\x85l\x9fk\xae\xaa\xd2\xe4\xf0J)(1:s32:\xc0\xb9\xf1\xa9\xf6\xf2\xd8i\xb2Y?\x086\x05y\x8c*\x0b\xb2~(\xe4q\xd2\xf1\xb7D+\xc1V"\xb6)))' [agent.py:166]
2018-03-18 19:20:05,971 DEBUG        <- b'D (7:sig-val(5:ecdsa(1:r32:C\x93\xdaK\xc1E\xddrl?q\x9a\xd4\x00\xbc\x12\xe6\x93u\xae8?\x85l\x9fk\xae\xaa\xd2\xe4\xf0J)(1:s32:\xc0\xb9\xf1\xa9\xf6\xf2\xd8i\xb2Y?\x086\x05y\x8c*\x0b\xb2~(\xe4q\xd2\xf1\xb7D+\xc1V"\xb6)))' [keyring.py:53]
2018-03-18 19:20:05,971 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
gpg: Signature made Sun 18 Mar 2018 07:20:05 PM UTC2018-03-18 19:20:05,971 DEBUG        waiting for connection on /run/user/1001/gnupg/d.mppaigfowm4c1ab53zbmyo6s/S.gpg-agent                [agent.py:14]

gpg:                using ECDSA key AD1F552B377AD61DFBC7A5D59A214ED4A9F2E2B5
gpg: Good signature from "FooBar" [ultimate]
```

**Comment by romanz** [comment]
It seems that you are using an older version (according to the logged line numbers):

```
2018-03-18 19:30:10,652 ERROR        unknown request: 'SCD SERIALNO openpgp'                                                              [agent.py:168]
```

https://github.com/romanz/trezor-agent/blob/5dba12f14475b9be3f6cd39276d9138a83c7c515/libagent/gpg/agent.py#L210

**Comment by fansari** [comment]
I am using Fedora 27.

Here what happans when I try to follow the installation guide.

BTW: "pip3 install ledger_agent" ends up with the same error.

```
[fansari@bat ledger]$ git clone https://github.com/romanz/trezor-agent.git
Cloning into 'trezor-agent'...
remote: Counting objects: 4136, done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 4136 (delta 110), reused 150 (delta 92), pack-reused 3951
Receiving objects: 100% (4136/4136), 1.53 MiB | 1.98 MiB/s, done.
Resolving deltas: 100% (2886/2886), done.
[fansari@bat ledger]$ pip3 install --user -e trezor-agent/agents/ledger
Obtaining file:///home/fansari/devel/ledger/trezor-agent/agents/ledger
Collecting libagent>=0.9.0 (from ledger-agent==0.9.0)
  Using cached libagent-0.11.2.tar.gz
Collecting ledgerblue>=0.1.8 (from ledger-agent==0.9.0)
  Using cached ledgerblue-0.1.16.tar.gz
Collecting backports.shutil_which>=3.5.1 (from libagent>=0.9.0->ledger-agent==0.9.0)
  Using cached backports.shutil_which-3.5.1-py2.py3-none-any.whl
Collecting ConfigArgParse>=0.12.0 (from libagent>=0.9.0->ledger-agent==0.9.0)
  Using cached ConfigArgParse-0.13.0.tar.gz
Collecting python-daemon>=2.1.2 (from libagent>=0.9.0->ledger-agent==0.9.0)
  Using cached python_daemon-2.1.2-py2.py3-none-any.whl
Collecting ecdsa>=0.13 (from libagent>=0.9.0->ledger-agent==0.9.0)
  Using cached ecdsa-0.13-py2.py3-none-any.whl
Collecting ed25519>=1.4 (from libagent>=0.9.0->ledger-agent==0.9.0)
  Using cached ed25519-1.4.tar.gz
Collecting mnemonic>=0.18 (from libagent>=0.9.0->ledger-agent==0.9.0)
  Using cached mnemonic-0.18.tar.gz
Collecting pymsgbox>=1.0.6 (from libagent>=0.9.0->ledger-agent==0.9.0)
  Using cached PyMsgBox-1.0.6.zip
Collecting semver>=2.2 (from libagent>=0.9.0->ledger-agent==0.9.0)
  Using cached semver-2.7.9.tar.gz
Collecting unidecode>=0.4.20 (from libagent>=0.9.0->ledger-agent==0.9.0)
  Using cached Unidecode-1.0.22-py2.py3-none-any.whl
Collecting hidapi>=0.7.99 (from ledgerblue>=0.1.8->ledger-agent==0.9.0)
  Using cached hidapi-0.7.99.post21.tar.gz
    Complete output from command python setup.py egg_info:
    Compiling /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Plex/Scanners.py because it changed.
    Compiling /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Plex/Actions.py because it changed.
    Compiling /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/Pythran.py because it changed.
    Compiling /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/Lexicon.py because it changed.
    Compiling /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/Scanning.py because it changed.
    Compiling /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/Parsing.py because it changed.
    Compiling /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/Visitor.py because it changed.
    Compiling /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/FlowControl.py because it changed.
    Compiling /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/Code.py because it changed.
    Compiling /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Runtime/refnanny.pyx because it changed.
    Compiling /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/FusedNode.py because it changed.
    Compiling /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Tempita/_tempita.py because it changed.
    Compiling /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/StringIOTree.py because it changed.
    [ 1/13] Cythonizing /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/Code.py
    [ 2/13] Cythonizing /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/FlowControl.py
    [ 3/13] Cythonizing /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/FusedNode.py
    [ 4/13] Cythonizing /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/Lexicon.py
    [ 5/13] Cythonizing /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/Parsing.py
    [ 6/13] Cythonizing /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/Pythran.py
    [ 7/13] Cythonizing /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/Scanning.py
    [ 8/13] Cythonizing /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Compiler/Visitor.py
    [ 9/13] Cythonizing /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Plex/Actions.py
    [10/13] Cythonizing /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Plex/Scanners.py
    [11/13] Cythonizing /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Runtime/refnanny.pyx
    [12/13] Cythonizing /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/StringIOTree.py
    [13/13] Cythonizing /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Tempita/_tempita.py
    Unable to find pgen, not compiling formal grammar.
    warning: no files found matching '2to3-fixers.txt'
    warning: no files found matching 'Doc/*'
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    warning: no files found matching 'pyximport/README'
    /tmp/easy_install-i1csah9s/Cython-0.28.1/Cython/Plex/Scanners.c:19:10: fatal error: Python.h: No such file or directory
     #include "Python.h"
              ^~~~~~~~~~
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 127, in _compile
        extra_postargs)
      File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 170, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/usr/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 156, in call_command
        self.run_command(cmdname)
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
        self.build()
      File "/usr/lib64/python3.6/distutils/command/install_lib.py", line 107, in build
        self.run_command('build_ext')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 75, in run
        _build_ext.run(self)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/usr/lib64/python3.6/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 129, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-i1csah9s/Cython-0.28.1/setup.py", line 285, in <module>
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1103, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib64/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-i1csah9s/Cython-0.28.1/setup.py", line 285, in <module>
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-v7v7xctk/hidapi/setup.py", line 123, in <module>
        install_requires = ['setuptools>=19.0'],
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 453, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 866, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1146, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1158, in obtain
        return installer(requirement)
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 520, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 671, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 697, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 878, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1117, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1105, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-v7v7xctk/hidapi/
You are using pip version 9.0.1, however version 9.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[fansari@bat ledger]$ pip install --upgrade pip
Requirement already up-to-date: pip in /usr/lib/python2.7/site-packages
```

**Comment by fansari** [comment]
I am using Fedora 27.

Let me try to summarize my steps so far. The first step makes pip3 available. My system had a broken link. The next two steps were necessary because otherwise the compilation fails.

```
dnf reinstall python3-pip
dnf install python3-devel
python3 -m pip install cython
git clone https://github.com/romanz/trezor-agent.git
pip3 install --user -e trezor-agent/agents/ledger
``

**Comment by romanz** [comment]
Please also update the to latest `libagent` using:
```
$ pip3 install -U --user -e trezor-agent/
```

**Comment by fansari** [comment]
OK. Now as result I have this in /home/fansari/.local/bin

```
[fansari@bat bin]$ ll
total 24
-rwxrwxr-x. 1 fansari fansari 234 Mar 19 21:31 easy_install
-rwxrwxr-x. 1 fansari fansari 234 Mar 19 21:31 easy_install-3.6
-rwxrwxr-x. 1 fansari fansari 386 Mar 19 21:20 ledger-agent
-rwxrwxr-x. 1 fansari fansari 320 Mar 19 21:20 ledger_agent.py
-rwxrwxr-x. 1 fansari fansari 382 Mar 19 21:20 ledger-gpg
-rwxrwxr-x. 1 fansari fansari 394 Mar 19 21:20 ledger-gpg-agent
drwxrwxr-x. 1 fansari fansari  54 Mar 19 21:22 __pycache__
```
If I run ledger-gpg-agent from there it is workig. Is this folder meant to be the final destination for the installation?

**Comment by romanz** [comment]
Yes, I recommend installing the tools there.

**Comment by fansari** [comment]
Cool. My last step was to install the systemd stuff in ~/.config/systemd/user and now it is starting up after system boot!
