### ISSUE TITLE
trezor-gpg won't work with Trezor T

### ISSUE THREAD

**Issue by AgentME** [romanz/trezor-agent#230]
I've previously used trezor-gpg to create a public key associated with my classic trezor. My trezor T has the same key. I tried to use my trezor T to decrypt something, but I get this error:

```
$ GNUPGHOME=~/.gnupg/trezor gpg2 --decrypt < 'foo.txt.gpg'
gpg: encrypted with 256-bit ECDH key, ID 61976EF6, created 2017-10-12
      "Trezor <trezor@macil.tech>"
gpg: decryption failed: No secret key
```

Next, I moved my ~/.gnupg/trezor directory somewhere safe and tried creating a new keypair with the trezor:

```
$ trezor-gpg init "Foo <foo@example.com>"
2018-04-03 20:05:22,098 WARNING      This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility! [__init__.py:117]
2018-04-03 20:05:22,105 WARNING      NOTE: in order to re-generate the exact same GPG key later, run this command with "--time=1522811122" commandline flag (to set the timestamp of the GPG key manually). [__init__.py:35]
Traceback (most recent call last):
  File "/home/chris/.local/bin/trezor-gpg", line 11, in <module>
    sys.exit(gpg_tool())
  File "/home/chris/.local/bin/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/home/chris/.local/lib/python3.5/site-packages/libagent/gpg/__init__.py", line 286, in main
    return args.func(device_type=device_type, args=args)
  File "/home/chris/.local/lib/python3.5/site-packages/libagent/gpg/__init__.py", line 180, in run_init
    export_public_key(device_type, args))
  File "/home/chris/.local/lib/python3.5/site-packages/libagent/gpg/__init__.py", line 39, in export_public_key
    verifying_key = c.pubkey(identity=identity, ecdh=False)
  File "/home/chris/.local/lib/python3.5/site-packages/libagent/gpg/client.py", line 27, in pubkey
    with self.device:
  File "/home/chris/.local/lib/python3.5/site-packages/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/home/chris/.local/lib/python3.5/site-packages/libagent/device/trezor.py", line 104, in connect
    connection = self._defs.Client(transports[0])
  File "/home/chris/.local/lib/python3.5/site-packages/trezorlib/client.py", line 504, in __init__
    self.init_device()
  File "/home/chris/.local/lib/python3.5/site-packages/trezorlib/client.py", line 511, in init_device
    self.features = expect(proto.Features)(self.call)(proto.Initialize())
  File "/home/chris/.local/lib/python3.5/site-packages/trezorlib/client.py", line 176, in wrapped_f
    ret = f(*args, **kwargs)
  File "/home/chris/.local/lib/python3.5/site-packages/trezorlib/client.py", line 190, in wrapped_f
    return f(*args, **kwargs)
  File "/home/chris/.local/lib/python3.5/site-packages/trezorlib/client.py", line 230, in call
    resp = self.call_raw(msg)
  File "/home/chris/.local/lib/python3.5/site-packages/trezorlib/client.py", line 190, in wrapped_f
    return f(*args, **kwargs)
  File "/home/chris/.local/lib/python3.5/site-packages/trezorlib/client.py", line 225, in call_raw
    self.transport.write(msg)
  File "/home/chris/.local/lib/python3.5/site-packages/trezorlib/transport_bridge.py", line 105, in write
    raise TransportException('trezord: Could not write message' + get_error(r))
trezorlib.transport.TransportException: trezord: Could not write message (error=400 str=malformed wire format)
```

I'm on Ubuntu 16.04 with trezor-agent version 0.9.2. I updated it and its dependencies right before trying this.

**Comment by romanz** [comment]
This issue should be resolved at 2.0.6 TREZOR model T firmware.
It can be downloaded from https://github.com/trezor/webwallet-data/tree/master/firmware/2.
