### ISSUE TITLE
Unable to unlock Trezor ; No such file or directory: 'pinentry': 'pinentry'

### ISSUE THREAD

**Issue by saphirblanc** [romanz/trezor-agent#243]
Hi,

I'm trying to generate an SSH key letting me access my server using my trezor. Here are the logs :

```
$ trezor-agent -vv root@XXX
2018-05-20 17:11:49,498 DEBUG        parsed identity: {'proto': None, 'user': 'root', 'host': 'XXX', 'port': None, 'path': None} [interface.py:30]
2018-05-20 17:11:49,498 DEBUG        identity parts: ['ssh://', 'root@', 'XXX']                                       [interface.py:46]
2018-05-20 17:11:49,498 INFO         identity #0: <ssh://root@XXX|nist256p1>                                          [__init__.py:251]
2018-05-20 17:11:49,505 WARNING      DISPLAY not defined                                                                                  [ui.py:65]
2018-05-20 17:11:49,505 INFO         using [b'ttyname=/dev/ttys001'] for pinentry options                                                 [ui.py:67]
2018-05-20 17:11:49,630 DEBUG        Starting new HTTP connection (1): 127.0.0.1                                                          [connectionpool.py:208]
2018-05-20 17:11:49,637 DEBUG        http://127.0.0.1:21325 "POST /enumerate HTTP/1.1" 200 123                                            [connectionpool.py:396]
2018-05-20 17:11:49,651 DEBUG        transports: [<trezorlib.transport_bridge.BridgeTransport object at 0x105b40b38>, <trezorlib.transport_hid.HidTransport object at 0x105fe4908>] [trezor.py:102]
2018-05-20 17:11:49,653 DEBUG        Starting new HTTP connection (1): 127.0.0.1                                                          [connectionpool.py:208]
2018-05-20 17:11:49,662 DEBUG        http://127.0.0.1:21325 "POST /acquire/XXX/null HTTP/1.1" 200 17 [connectionpool.py:396]
2018-05-20 17:11:49,704 DEBUG        http://127.0.0.1:21325 "POST /call/90 HTTP/1.1" 200 1328                                             [connectionpool.py:396]
2018-05-20 17:11:49,709 DEBUG        http://127.0.0.1:21325 "POST /release/90 HTTP/1.1" 200 17                                            [connectionpool.py:396]
2018-05-20 17:11:49,709 DEBUG        connected to Trezor XXX                                                         [trezor.py:82]
2018-05-20 17:11:49,710 DEBUG        label    : XXX                                                                                 [trezor.py:83]
2018-05-20 17:11:49,710 DEBUG        vendor   : bitcointrezor.com                                                                         [trezor.py:84]
2018-05-20 17:11:49,710 DEBUG        version  : 1.6.1                                                                                     [trezor.py:88]
2018-05-20 17:11:49,710 DEBUG        revision : b'9588e8f2736b60916f51e470deb18f55112a6ebc'                                               [trezor.py:89]
2018-05-20 17:11:49,729 DEBUG        http://127.0.0.1:21325 "POST /acquire/XXX/null HTTP/1.1" 200 17 [connectionpool.py:396]
2018-05-20 17:11:49,887 DEBUG        http://127.0.0.1:21325 "POST /call/91 HTTP/1.1" 200 16                                               [connectionpool.py:396]
2018-05-20 17:11:49,945 DEBUG        http://127.0.0.1:21325 "POST /call/91 HTTP/1.1" 200 1328                                             [connectionpool.py:396]
2018-05-20 17:11:49,951 DEBUG        http://127.0.0.1:21325 "POST /release/91 HTTP/1.1" 200 17                                            [connectionpool.py:396]
2018-05-20 17:11:49,951 ERROR        ping failed: [Errno 2] No such file or directory: 'pinentry': 'pinentry'                             [trezor.py:116]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/libagent/device/trezor.py", line 110, in connect
    connection.ping(msg='', pin_protection=True)  # unlock PIN
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 162, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 176, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 644, in ping
    return self.call(msg)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 190, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 235, in call
    msg = handler(resp)
  File "/usr/local/lib/python3.6/site-packages/libagent/device/trezor.py", line 37, in new_handler
    scrambled_pin = self.ui.get_pin()
  File "/usr/local/lib/python3.6/site-packages/libagent/device/ui.py", line 40, in get_pin
    options=self.options_getter())
  File "/usr/local/lib/python3.6/site-packages/libagent/device/ui.py", line 98, in interact
    env=os.environ)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pinentry': 'pinentry'
Traceback (most recent call last):
  File "/usr/local/bin/trezor-agent", line 11, in <module>
    load_entry_point('trezor-agent==0.9.2', 'console_scripts', 'trezor-agent')()
  File "/usr/local/bin/trezor_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 164, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 287, in main
    for pk in conn.public_keys():
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 199, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/usr/local/lib/python3.6/site-packages/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/usr/local/lib/python3.6/site-packages/libagent/device/trezor.py", line 110, in connect
    connection.ping(msg='', pin_protection=True)  # unlock PIN
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 162, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 176, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 644, in ping
    return self.call(msg)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 190, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 235, in call
    msg = handler(resp)
  File "/usr/local/lib/python3.6/site-packages/libagent/device/trezor.py", line 37, in new_handler
    scrambled_pin = self.ui.get_pin()
  File "/usr/local/lib/python3.6/site-packages/libagent/device/ui.py", line 40, in get_pin
    options=self.options_getter())
  File "/usr/local/lib/python3.6/site-packages/libagent/device/ui.py", line 98, in interact
    env=os.environ)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pinentry': 'pinentry' 
```

So the pin pad is showing up for about a second and then disappears. However, if I do unlock it through trezor.io and then generate the SSH key, everything goes smoothly.

Any suggestion ?

Thanks!

**Comment by romanz** [comment]
Thanks for reporting this issue!
It seems that `pinentry` binary is not installed on your machine ([doc link](https://github.com/romanz/trezor-agent/blob/master/doc/README-PINENTRY.md)).

**Comment by saphirblanc** [comment]
Hi,
Thanks for your answer. Indeed, I did not have installed pinentry-mac. Now it is :
```
$ brew list | grep 'pin'
pinentry-mac
```
however, I'm still facing the issue :/ :
```
$ trezor-agent -vv -c root@XXX
2018-05-22 13:13:14,495 DEBUG        parsed identity: {'proto': None, 'user': 'root', 'host': 'XXX', 'port': None, 'path': None} [interface.py:30]
2018-05-22 13:13:14,495 DEBUG        identity parts: ['ssh://', 'root@', 'XXX']                                       [interface.py:46]
2018-05-22 13:13:14,495 INFO         identity #0: <ssh://root@XXX|nist256p1>                                          [__init__.py:251]
2018-05-22 13:13:14,498 DEBUG        parsed identity: {'proto': None, 'user': 'root', 'host': 'XXX', 'port': None, 'path': None} [interface.py:30]
2018-05-22 13:13:14,503 WARNING      DISPLAY not defined                                                                                  [ui.py:65]
2018-05-22 13:13:14,503 INFO         using [b'ttyname=/dev/ttys000'] for pinentry options                                                 [ui.py:67]
2018-05-22 13:13:14,514 DEBUG        local SSH version: b'OpenSSH_7.6p1, LibreSSL 2.6.2\n'                                                [__init__.py:123]
2018-05-22 13:13:14,514 DEBUG        serving on /var/folders/tj/lm88qkj91cvcg7247yc64sh80000gn/T/trezor-ssh-agent-xld_937s                [server.py:30]
2018-05-22 13:13:14,515 DEBUG        server thread started                                                                                [server.py:84]
2018-05-22 13:13:14,515 INFO         running ['ssh', '-l', 'root', 'XXX'] with {'SSH_AUTH_SOCK': '/var/folders/tj/lm88qkj91cvcg7247yc64sh80000gn/T/trezor-ssh-agent-xld_937s', 'SSH_AGENT_PID': '908'} [server.py:119]
2018-05-22 13:13:14,515 DEBUG        waiting for connection on /var/folders/tj/lm88qkj91cvcg7247yc64sh80000gn/T/trezor-ssh-agent-xld_937s [server.py:92]
2018-05-22 13:13:14,518 DEBUG        subprocess 913 is running                                                                            [server.py:126]
2018-05-22 13:13:14,717 DEBUG        welcome agent                                                                                        [server.py:53]
2018-05-22 13:13:14,717 DEBUG        request: 1 bytes                                                                                     [protocol.py:94]
2018-05-22 13:13:14,717 DEBUG        calling list_pubs()                                                                                  [protocol.py:102]
2018-05-22 13:13:14,718 DEBUG        waiting for connection on /var/folders/tj/lm88qkj91cvcg7247yc64sh80000gn/T/trezor-ssh-agent-xld_937s [server.py:92]
2018-05-22 13:13:14,831 DEBUG        Starting new HTTP connection (1): 127.0.0.1                                                          [connectionpool.py:208]
2018-05-22 13:13:14,839 DEBUG        http://127.0.0.1:21325 "POST /enumerate HTTP/1.1" 200 123                                            [connectionpool.py:396]
2018-05-22 13:13:14,858 DEBUG        transports: [<trezorlib.transport_bridge.BridgeTransport object at 0x10df86e48>, <trezorlib.transport_hid.HidTransport object at 0x10e42aac8>] [trezor.py:102]
2018-05-22 13:13:14,860 DEBUG        Starting new HTTP connection (1): 127.0.0.1                                                          [connectionpool.py:208]
2018-05-22 13:13:14,872 DEBUG        http://127.0.0.1:21325 "POST /acquire/hide7eebe30c3d3ed48bccc60f6b96379ccd37e411975e5d695568407762c7a9a6e/null HTTP/1.1" 200 16 [connectionpool.py:396]
2018-05-22 13:13:14,914 DEBUG        http://127.0.0.1:21325 "POST /call/3 HTTP/1.1" 200 1328                                              [connectionpool.py:396]
2018-05-22 13:13:14,921 DEBUG        http://127.0.0.1:21325 "POST /release/3 HTTP/1.1" 200 16                                             [connectionpool.py:396]
2018-05-22 13:13:14,923 DEBUG        connected to Trezor 808B3E592CEF7E00167D70A6                                                         [trezor.py:82]
2018-05-22 13:13:14,923 DEBUG        label    : 2_Saphir                                                                                  [trezor.py:83]
2018-05-22 13:13:14,924 DEBUG        vendor   : bitcointrezor.com                                                                         [trezor.py:84]
2018-05-22 13:13:14,924 DEBUG        version  : 1.6.1                                                                                     [trezor.py:88]
2018-05-22 13:13:14,924 DEBUG        revision : b'9588e8f2736b60916f51e470deb18f55112a6ebc'                                               [trezor.py:89]
2018-05-22 13:13:14,939 DEBUG        http://127.0.0.1:21325 "POST /acquire/hide7eebe30c3d3ed48bccc60f6b96379ccd37e411975e5d695568407762c7a9a6e/null HTTP/1.1" 200 16 [connectionpool.py:396]
2018-05-22 13:13:15,095 DEBUG        http://127.0.0.1:21325 "POST /call/4 HTTP/1.1" 200 16                                                [connectionpool.py:396]
2018-05-22 13:13:15,152 DEBUG        http://127.0.0.1:21325 "POST /call/4 HTTP/1.1" 200 1328                                              [connectionpool.py:396]
2018-05-22 13:13:15,157 DEBUG        http://127.0.0.1:21325 "POST /release/4 HTTP/1.1" 200 16                                             [connectionpool.py:396]
2018-05-22 13:13:15,158 ERROR        ping failed: [Errno 2] No such file or directory: 'pinentry': 'pinentry'                             [trezor.py:116]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/libagent/device/trezor.py", line 110, in connect
    connection.ping(msg='', pin_protection=True)  # unlock PIN
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 162, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 176, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 644, in ping
    return self.call(msg)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 190, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 235, in call
    msg = handler(resp)
  File "/usr/local/lib/python3.6/site-packages/libagent/device/trezor.py", line 37, in new_handler
    scrambled_pin = self.ui.get_pin()
  File "/usr/local/lib/python3.6/site-packages/libagent/device/ui.py", line 40, in get_pin
    options=self.options_getter())
  File "/usr/local/lib/python3.6/site-packages/libagent/device/ui.py", line 98, in interact
    env=os.environ)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pinentry': 'pinentry'
2018-05-22 13:13:15,163 WARNING      error: [Errno 2] No such file or directory: 'pinentry': 'pinentry'                                   [server.py:63]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/libagent/server.py", line 58, in handle_connection
    reply = handler.handle(msg=msg)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/protocol.py", line 103, in handle
    reply = method(buf=buf)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/protocol.py", line 111, in list_pubs
    keys = self.conn.parse_public_keys()
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 205, in parse_public_keys
    for pk in self.public_keys()]
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/__init__.py", line 199, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/usr/local/lib/python3.6/site-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/usr/local/lib/python3.6/site-packages/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/usr/local/lib/python3.6/site-packages/libagent/device/trezor.py", line 110, in connect
    connection.ping(msg='', pin_protection=True)  # unlock PIN
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 162, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 176, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 644, in ping
    return self.call(msg)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 190, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/trezorlib/client.py", line 235, in call
    msg = handler(resp)
  File "/usr/local/lib/python3.6/site-packages/libagent/device/trezor.py", line 37, in new_handler
    scrambled_pin = self.ui.get_pin()
  File "/usr/local/lib/python3.6/site-packages/libagent/device/ui.py", line 40, in get_pin
    options=self.options_getter())
  File "/usr/local/lib/python3.6/site-packages/libagent/device/ui.py", line 98, in interact
    env=os.environ)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pinentry': 'pinentry'
```
Pretty sure, it's something from my side, but what... thanks for the time taken!

**Comment by romanz** [comment]
You're welcome :)
