### ISSUE TITLE
GPG subkey creation fails

### ISSUE THREAD

**Issue by rustyrussell** [romanz/trezor-agent#26]
```
$ trezor-gpg create --subkey | gpg2 --import
2016-08-25 12:23:42,814 WARNING    RSA signatures are not verified
2016-08-25 12:23:42,819 WARNING    RSA signatures are not verified
2016-08-25 12:23:42,820 WARNING    public key D9200E6CD1ADB8F1 is not verified!
2016-08-25 12:23:42,820 INFO       adding subkey to primary GPG key "Rusty Russell <rusty@rustcorp.com.au>"
2016-08-25 12:23:42,820 INFO       confirm signing with new subkey
2016-08-25 12:24:58,487 INFO       confirm signing with primary key
gpg: checking the trustdb
gpg: keyring_search failed: Legacy key
gpg: failed to rebuild keyring cache: Legacy key
gpg: marginals needed: 3  completes needed: 1  trust model: PGP
gpg: depth: 0  valid:   1  signed:  33  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:  33  signed:  10  trust: 33-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2017-10-04
Traceback (most recent call last):
  File "/home/rusty/.local/bin/trezor-gpg", line 11, in <module>
    load_entry_point('trezor-agent==0.6.5', 'console_scripts', 'trezor-gpg')()
  File "/home/rusty/.local/lib/python2.7/site-packages/trezor_agent/gpg/__main__.py", line 92, in main
    args.run(args)
  File "/home/rusty/.local/lib/python2.7/site-packages/trezor_agent/gpg/__main__.py", line 39, in run_create
    signer_func=conn.sign)
  File "/home/rusty/.local/lib/python2.7/site-packages/trezor_agent/gpg/encode.py", line 164, in create_subkey
    signer_func = AgentSigner(primary['user_id']).sign
  File "/home/rusty/.local/lib/python2.7/site-packages/trezor_agent/gpg/encode.py", line 65, in __init__
    self.keygrip = keyring.get_keygrip(user_id)
  File "/home/rusty/.local/lib/python2.7/site-packages/trezor_agent/gpg/keyring.py", line 186, in get_keygrip
    output = sp.check_output(args).decode('ascii')
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['gpg2', '--list-keys', '--with-keygrip', 'Rusty Russell <rusty@rustcorp.com.au>']' returned non-zero exit status 2
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

**Comment by romanz** [comment]
Thanks for reporting this issue!

In order to create a subkey, trezor-agent needs to sign the new subkey using the existing GPG primary key.
In order to do that, I am using the first keygrip from the stdout of `gpg2 --list-keys --with-keygrip $TREZOR_GPG_USER_ID` but it seems that in this case it returned without any output...

Could you please check if this primary key is available for signature on your machine (e.g. by running `gpg2 -K`)?

**Comment by rustyrussell** [comment]
Roman Zeyde <notifications@github.com> writes:
> Thanks for reporting this issue!
>
> In order to create a subkey, trezor-agent needs to sign the new subkey using the existing GPG primary key.
> In order to do that, I am using the first keygrip from the stdout of `gpg2 --list-keys --with-keygrip $TREZOR_GPG_USER_ID` but it seems that in this case it returned without any output...

$ gpg2 --list-keys --with-keygrip $TREZOR_GPG_USER_ID
pub   rsa4096/D1ADB8F1 2011-10-18 [SC]
      Keygrip = A31CA6ACCE5C1E12D6B7E127BE2916E4BFFBD3E6
uid         [ultimate] Rusty Russell <rusty@rustcorp.com.au>
sub   rsa4096/7E499676 2011-10-18 [E]
      Keygrip = F0AEF257D9F1C247807BA7CB3A425E04890D05A9

Weird, perhaps $TREZOR_GPG_USER_ID was unset.

I re-ran it, it failed (in a new way).  I suspected an incorrect
passphrase, so I re-re-ran it, it succeeded):

rusty@ASUS-UX305UA:~/devel/cvs/lightning (guilt/fixmes)$ trezor-gpg create --subkey | gpg2 --import

2016-08-25 20:58:09,976 WARNING    NOTE: in order to re-generate the exact same GPG key later, run this command with "--time=1472124489" commandline flag (to set the timestamp of the GPG key manually).
Use the numeric keypad to describe number positions. The layout is:
    7 8 9
    4 5 6
    1 2 3
Please enter current PIN: 

2016-08-25 20:58:38,911 WARNING    RSA signatures are not verified
2016-08-25 20:58:38,922 WARNING    RSA signatures are not verified
2016-08-25 20:58:38,926 WARNING    public key D9200E6CD1ADB8F1 is not verified!
2016-08-25 20:58:38,926 INFO       adding subkey to primary GPG key "Rusty Russell <rusty@rustcorp.com.au>"
2016-08-25 20:58:38,927 INFO       confirm signing with new subkey
2016-08-25 20:58:52,757 INFO       confirm signing with primary key
Traceback (most recent call last):
  File "/home/rusty/.local/bin/trezor-gpg", line 11, in <module>
    load_entry_point('trezor-agent==0.6.5', 'console_scripts', 'trezor-gpg')()
  File "/home/rusty/.local/lib/python2.7/site-packages/trezor_agent/gpg/__main__.py", line 92, in main
    args.run(args)
  File "/home/rusty/.local/lib/python2.7/site-packages/trezor_agent/gpg/__main__.py", line 39, in run_create
    signer_func=conn.sign)
  File "/home/rusty/.local/lib/python2.7/site-packages/trezor_agent/gpg/encode.py", line 172, in create_subkey
    unhashed_subpackets=unhashed_subpackets)
  File "/home/rusty/.local/lib/python2.7/site-packages/trezor_agent/gpg/protocol.py", line 234, in make_signature
    params = signer_func(digest=digest)
  File "/home/rusty/.local/lib/python2.7/site-packages/trezor_agent/gpg/encode.py", line 70, in sign
    keygrip=self.keygrip, digest=digest)
  File "/home/rusty/.local/lib/python2.7/site-packages/trezor_agent/gpg/keyring.py", line 165, in sign_digest
    raise ValueError(prefix)
ValueError: S
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
rusty@ASUS-UX305UA:~/devel/cvs/lightning (guilt/fixmes)$ trezor-gpg create --subkey | gpg2 --import
2016-08-25 21:00:08,045 WARNING    NOTE: in order to re-generate the exact same GPG key later, run this command with "--time=1472124608" commandline flag (to set the timestamp of the GPG key manually).
2016-08-25 21:00:08,444 WARNING    RSA signatures are not verified
2016-08-25 21:00:08,449 WARNING    RSA signatures are not verified
2016-08-25 21:00:08,450 WARNING    public key D9200E6CD1ADB8F1 is not verified!
2016-08-25 21:00:08,450 INFO       adding subkey to primary GPG key "Rusty Russell <rusty@rustcorp.com.au>"
2016-08-25 21:00:08,450 INFO       confirm signing with new subkey
2016-08-25 21:00:13,605 INFO       confirm signing with primary key
2016-08-25 21:00:13,738 WARNING    RSA signatures are not verified
2016-08-25 21:00:13,746 WARNING    RSA signatures are not verified
2016-08-25 21:00:13,778 WARNING    public key D9200E6CD1ADB8F1 is not verified!
2016-08-25 21:00:13,778 INFO       adding subkey to primary GPG key "Rusty Russell <rusty@rustcorp.com.au>"
2016-08-25 21:00:13,778 INFO       confirm signing with primary key
gpg: key D1ADB8F1: "Rusty Russell <rusty@rustcorp.com.au>" 2 new signatures
gpg: key D1ADB8F1: "Rusty Russell <rusty@rustcorp.com.au>" 2 new subkeys
gpg: Total number processed: 1
gpg:            new subkeys: 2
gpg:         new signatures: 2
gpg: keyring_search failed: Legacy key
gpg: failed to rebuild keyring cache: Legacy key
gpg: marginals needed: 3  completes needed: 1  trust model: PGP
gpg: depth: 0  valid:   1  signed:  33  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:  33  signed:  10  trust: 33-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2017-10-04

> Could you please check if this primary key is available for signature on your machine (e.g. by running `gpg2 -K`)?

$ gpg2 -K
/home/rusty/.gnupg/pubring.gpg
------------------------------
sec   rsa4096/D1ADB8F1 2011-10-18 [SC]
uid         [ultimate] Rusty Russell <rusty@rustcorp.com.au>
ssb   rsa4096/7E499676 2011-10-18 [E]
ssb#  nistp256/448BC714 2016-08-25 [S]
ssb#  nistp256/5268EBAE 2016-08-25 [E]

Now I've generated two keys :(

Can I simply remove one in gpg and go about my merry way?

Thanks,
Rusty.

**Comment by romanz** [comment]
Great, it seems that it worked correctly :)

trezor-agent usually adds 2 subkeys: one for signatures (448BC714) and one for encryption (5268EBAE). You can delete each one of them, using `gpg2 --edit-key` command, but IIUC it should work now as-is:
https://github.com/romanz/trezor-agent/blob/master/README-GPG.md#2-generate-a-new-subkey-for-an-existing-gpg-identity

**Comment by romanz** [comment]
You can try to see if the new subkey works for GPG signatures using the following commands:

```
$ trezor-gpg agent &
$ echo "Hello World!" | gpg2 --sign | gpg2 --verify 
```
https://github.com/romanz/trezor-agent/blob/master/README-GPG.md#sign-and-verify-gpg-messages

**Comment by romanz** [comment]
@rustyrussell 
I just wanted to know if the procedure above worked well for you...
If it's still an issue, please let me know :)
