### ISSUE TITLE
Unable to generate GPG subkey

### ISSUE THREAD

**Issue by MAHDTech** [romanz/trezor-agent#263]
When attempting to generate a subkey from an existing ID I receive the following error:

```bash
trezor-gpg init USER --subkey

2018-09-12 05:40:07,228 WARNING      This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility! [__init__.py:118]
2018-09-12 05:40:07,275 ERROR        GPG home directory /home/user/.gnupg/trezor exists, remove it manually if required               [__init__.py:135]
```

**Comment by romanz** [comment]
Yes, `trezor-gpg init` will re-create this directory if it doesn't exist:
https://github.com/romanz/trezor-agent/blob/71f357c1bfc76bd8260e4cd7f079372c3063cfce/libagent/gpg/__init__.py#L138

**Comment by MAHDTech** [comment]
Ok, after removing the directory and then re-running the command I now receive this error indicating the key doesn't exist.

```bash
2018-09-12 10:57:55,887 INFO         creating client instance for device: bridge:web04
  [client.py:151]
2018-09-12 10:57:56,319 INFO         adding nist256p1 GPG subkey for "USER" to existing key
  [__init__.py:45]
gpg: keybox '/home/user/.gnupg/trezor/pubring.kbx' created
gpg: WARNING: nothing exported
2018-09-12 10:57:56,369 ERROR        could not find public key 'USER' in local GPG keyring
  [keyring.py:238]
Traceback (most recent call last):
  File "/usr/bin/trezor-gpg", line 11, in <module>
    load_entry_point('trezor-agent==0.9.3', 'console_scripts', 'trezor-gpg')()
  File "/usr/bin/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/usr/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 324, in main
    return args.func(device_type=device_type, args=args)
  File "/usr/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 182, in run_init
    export_public_key(device_type, args))
  File "/usr/lib/python3.6/site-packages/libagent/gpg/__init__.py", line 54, in export_public_key
    primary_bytes = keyring.export_public_key(args.user_id)
  File "/usr/lib/python3.6/site-packages/libagent/gpg/keyring.py", line 239, in export_public_key
    raise KeyError(user_id)
KeyError: 'USER'
```

**Comment by romanz** [comment]
You should replace `USER` with your existing GPG identity - so `trezor-gpg init` will add your TREZOR-backed identity as a subkey to your existing one.

**Comment by MAHDTech** [comment]
I receive the same error using the output from 

```bash
gpg --list-secret-keys --keyid-format LONG

trezor-gpg init 35CAA34317576BD2 --subkey 

KeyError: '35CAA34317576BD2'
```

**Comment by romanz** [comment]
> https://asciinema.org/a/wNXYV3kJGHOznEpoQ0ViZ5Eb8

The `--subkey` feature is usually used to add TREZOR-based GPG keys to **non-TREZOR-based** existing GPG keys, e.g. see the following example for adding NISTP-256 TREZOR-based subkeys to existing RSA-2048 non-TREZOR-based GPG identity:
https://github.com/romanz/trezor-agent/blob/master/doc/README-GPG.md#generate-gnupg-subkeys.
