### ISSUE TITLE
trezor-gpg init supplies arguments to gpg in wrong order

### ISSUE THREAD

**Issue by tkintscher** [romanz/trezor-agent#268]
I'm trying to run `trezor-gpg init`, but it fails like this:
```
~ » trezor-gpg init "foo@bar"
2018-10-07 13:35:00,795 WARNING      This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility! [__init__.py:118]
2018-10-07 13:35:00,827 WARNING      NOTE: in order to re-generate the exact same GPG key later, run this command with "--time=1538912100" commandline flag (to set the timestamp of the GPG key manually). [__init__.py:35]
gpg: inserting ownertrust of 6
gpg: Note: '--homedir' is not considered an option
gpg: keydb_search failed: Invalid argument
gpg: error reading key: Invalid argument
Traceback (most recent call last):
  File "/usr/local/bin/trezor-gpg", line 11, in <module>
    load_entry_point('trezor-agent==0.9.3', 'console_scripts', 'trezor-gpg')()
  File "/usr/local/Cellar/trezor-agent/0.9.3/libexec/bin/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/usr/local/Cellar/trezor-agent/0.9.3/libexec/lib/python3.7/site-packages/libagent/gpg/__init__.py", line 324, in main
    return args.func(device_type=device_type, args=args)
  File "/usr/local/Cellar/trezor-agent/0.9.3/libexec/lib/python3.7/site-packages/libagent/gpg/__init__.py", line 199, in run_init
    '--homedir', homedir]))
  File "/usr/local/Cellar/trezor-agent/0.9.3/libexec/lib/python3.7/site-packages/libagent/gpg/__init__.py", line 104, in check_call
    subprocess.check_call(args=args, stdin=stdin, env=env)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/Cellar/gnupg/2.2.10/bin/gpg', '--list-secret-keys', 'foo@bar', '--homedir', '/Users/foo/.gnupg/trezor']' returned non-zero exit status 2.
```

This is on MacOS with the latest version of gpg from brew:
```
~ » gpg --version
gpg (GnuPG) 2.2.10
libgcrypt 1.8.3
```

Indeed the command that trezor-gpg is trying to run does not work:
```
~ » /usr/local/Cellar/gnupg/2.2.10/bin/gpg --list-secret-keys "foo@bar" --homedir /Users/foo/.gnupg/trezor
gpg: Note: '--homedir' is not considered an option
gpg: keydb_search failed: Invalid argument
gpg: error reading key: Invalid argument
```
According to the gpg manpage, homedir must be the first argument:
```
~ » /usr/local/Cellar/gnupg/2.2.10/bin/gpg --homedir /Users/foo/.gnupg/trezor --list-secret-keys "foo@bar"
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
sec   nistp256 2018-10-07 [SC]
      [...]
uid           [ultimate] foo@bar
ssb   nistp256 2018-10-07 [E]
```

**Comment by romanz** [comment]
@tkintscher Thanks for reporting this issue!
Please try https://github.com/romanz/trezor-agent/commit/fec84288be7fbafa8a4f417d72cd87117f67ceee - I think it should solve this issue :)

**Comment by tkintscher** [comment]
@romanz Yes, that works for me.
Thanks a lot for fixing it!
