### ISSUE TITLE
Pinentry doesn't work when using --shell option on macOS

### ISSUE THREAD

**Issue by grr11** [romanz/trezor-agent#272]
I'm having some trouble using the trezor agent with the --shell option. 

The following error only happens when I configure my Terminal app to automatically open a shell with the trezor agent using this command: 

/Users/user/Homebrew/bin/trezor-agent /Users/user/.ssh/trezor.pub --shell

> sbash-3.2$ ssh user@host
 2018-11-04 17:42:14,723 ERROR        ping failed: [Errno 2] No such file or directory: 'pinentry': 'pinentry'                             [trezor.py:129]
Traceback (most recent call last):
  File "/Users/user/Homebrew/lib/python3.7/site-packages/libagent/device/trezor.py", line 123, in connect
    connection.ping(msg='', pin_protection=True)  # unlock PIN
  File "/Users/user/Homebrew/lib/python3.7/site-packages/trezorlib/client.py", line 100, in wrapped_f
    ret = f(*args, **kwargs)
  File "/Users/user/Homebrew/lib/python3.7/site-packages/trezorlib/client.py", line 115, in wrapped_f
    ret = f(*args, **kwargs)
  File "/Users/user/Homebrew/lib/python3.7/site-packages/trezorlib/client.py", line 628, in ping
    return self.call(msg)
  File "/Users/user/Homebrew/lib/python3.7/site-packages/trezorlib/client.py", line 131, in wrapped_f
    return f(*args, **kwargs)
  File "/Users/user/Homebrew/lib/python3.7/site-packages/trezorlib/client.py", line 174, in call
    msg = handler(resp)
  File "/Users/user/Homebrew/lib/python3.7/site-packages/libagent/device/trezor.py", line 38, in new_handler
    scrambled_pin = self.ui.get_pin()
  File "/Users/user/Homebrew/lib/python3.7/site-packages/libagent/device/ui.py", line 40, in get_pin
    options=self.options_getter())
  File "/Users/user/Homebrew/lib/python3.7/site-packages/libagent/device/ui.py", line 98, in interact
    env=os.environ)
  File "/Users/user/Homebrew/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/Users/user/Homebrew/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pinentry': 'pinentry'
sign_and_send_pubkey: signing failed: agent refused operation

I can avoid this if I first use the agent directly so that the pin is cached (trezor-agent user@host -c). Then it works until the cache expires and I have to enter the pin again.

I get a different issue if I manually run the trezor-agent shell: trezor-agent ~/.ssh/trezor.pub --shell
When I do this the trezor shell repeatedly gets put in the background during the pinentry process, and I have to manually bring it back to the foreground:

> bash-3.2$ trezor-agent ~/.ssh/trezor.pub --shell
2018-11-04 18:04:23,331 WARNING      DISPLAY not defined                                                                                  [ui.py:65]
bash-3.2$ ssh host
Unauthorized access to or use of this system...
[1]+  Stopped                 trezor-agent ~/.ssh/trezor.pub --shell
bash-3.2$ fg
trezor-agent ~/.ssh/trezor.pub --shell
[1]+  Stopped                 ssh host
bash-3.2$ fg
ssh host
tcsetattr: Interrupted system call
Welcome to Ubuntu...
0 packages can be updated.
0 updates are security updates.
Unauthorized access to or use of this system...
Last login: ...

Again, this only happens if I need to enter the pin. Otherwise it works.

I'm using a Mac running High Sierra v10.13.3

Any thoughts on why this is happening?
Thanks!

**Comment by grr11** [comment]
I was able to resolve this problem by installing pinentry-mac 

> brew install pinentry-mac

And then supplying the path using the --pin-entry-binary argument

> $ trezor-agent --pin-entry-binary /Users/user/Homebrew/bin/pinentry-mac IDENTITY --shell

:)
