### ISSUE TITLE
trezor-gpg init "identity" shows ImportError: cannot import name 'CallException'

### ISSUE THREAD

**Issue by LukasRada** [romanz/trezor-agent#280]
GPG identity init `trezor-gpg init "identity"` shows:
```
Traceback (most recent call last):
  File "/usr/local/bin/trezor-gpg", line 11, in <module>
    sys.exit(gpg_tool())
  File "/usr/local/bin/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/home/user/.local/lib/python3.5/site-packages/libagent/gpg/__init__.py", line 324, in main
    return args.func(device_type=device_type, args=args)
  File "/home/user/.local/lib/python3.5/site-packages/libagent/gpg/__init__.py", line 182, in run_init
    export_public_key(device_type, args))
  File "/home/user/.local/lib/python3.5/site-packages/libagent/gpg/__init__.py", line 39, in export_public_key
    verifying_key = c.pubkey(identity=identity, ecdh=False)
  File "/home/user/.local/lib/python3.5/site-packages/libagent/gpg/client.py", line 27, in pubkey
    with self.device:
  File "/home/user/.local/lib/python3.5/site-packages/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/home/user/.local/lib/python3.5/site-packages/libagent/device/trezor.py", line 109, in connect
    transport = self._defs.find_device()
  File "/home/user/.local/lib/python3.5/site-packages/libagent/device/trezor.py", line 25, in _defs
    from . import trezor_defs
  File "/home/user/.local/lib/python3.5/site-packages/libagent/device/trezor_defs.py", line 7, in <module>
    from trezorlib.client import CallException, PinException
ImportError: cannot import name 'CallException'
```

Is this related to #269 ?

**Comment by romanz** [comment]
It seems that `libagent` package is not up-to-date, since the latest version has different code at line #7:
https://github.com/romanz/trezor-agent/blob/995fba3e93cde9e1b1ee0ae8faaed9fc830f567a/libagent/device/trezor_defs.py#L7

Which version of `libagent` is installed?
```bash
$ pip3 freeze | grep libagent
```

Could you please re-install `libagent` package and try again?

**Comment by LukasRada** [comment]
You are right.

I re-installed libagent from 0.12.1 to 0.13.0 and command trezor-gpg init works as expected.

Thank you.
