### ISSUE TITLE
problem with the agent: End of file

### ISSUE THREAD

**Issue by korzq** [romanz/trezor-agent#286]
Can't decrypt a file created by `gpg -c` Error message when I do gpg message.gpg
`problem with the agent: End of file` and here is the error message from the log https://pastebin.com/gpuhYypx It works when I don't have ~/.gnupg/trezor as my $GNUPGHOME
Signing, encrypting and decrypting using trezor works.

**Comment by romanz** [comment]
Thanks for reporting this issue!
FTR, the error log is:
```
2019-03-01 20:08:40,878 WARNING      Unknown GETINFO command: (b'cmd_has_option', b'GET_PASSPHRASE', b'repeat')                           [agent.py:140]
2019-03-01 20:08:40,880 ERROR        handler failed: get_passphrase() takes 1 positional argument but 2 were given                        [__init__.py:273]
Traceback (most recent call last):
  File "/home/eric/.local/lib/python3.7/site-packages/libagent/gpg/__init__.py", line 265, in run_agent
    handler.handle(conn)
  File "/home/eric/.local/lib/python3.7/site-packages/libagent/gpg/agent.py", line 242, in handle
    handler(conn, args)
  File "/home/eric/.local/lib/python3.7/site-packages/libagent/gpg/agent.py", line 121, in handle_get_passphrase
    p1 = self.client.device.ui.get_passphrase('Symmetric encryption')
TypeError: get_passphrase() takes 1 positional argument but 2 were given
```

**Comment by romanz** [comment]
BTW, which version of `gpg` are you using?
```bash
$ gpg --version
```

**Comment by romanz** [comment]
Please try the latest commit (https://github.com/romanz/trezor-agent/commit/e437591dd59ece3110bb8fd11fb06bc2bb29f15f) - it should (hopefully) fix the issue :)

**Comment by korzq** [comment]
It still doesn't seems to work for me, my gpg version is gpg (GnuPG) 2.2.13 libgcrypt 1.8.4. I am using Arch Linux. I first uninstalled trezor-agent with ` pip3 uninstall trezor-agent` then clone the repo then installing it using `pip3 install --user -e trezor-agent/agents/trezor`. 
Error Log:
`2019-03-03 17:26:43,422 WARNING      Unknown GETINFO command: (b'cmd_has_option', b'GET_PASSPHRASE', b'repeat')                           [agent.py:140]
2019-03-03 17:26:43,423 ERROR        handler failed: get_passphrase() takes 1 positional argument but 2 were given                        [__init__.py:273]
Traceback (most recent call last):
  File "/home/eric/.local/lib/python3.7/site-packages/libagent/gpg/__init__.py", line 265, in run_agent
    handler.handle(conn)
  File "/home/eric/.local/lib/python3.7/site-packages/libagent/gpg/agent.py", line 242, in handle
    handler(conn, args)
  File "/home/eric/.local/lib/python3.7/site-packages/libagent/gpg/agent.py", line 121, in handle_get_passphrase
    p1 = self.client.device.ui.get_passphrase('Symmetric encryption')
TypeError: get_passphrase() takes 1 positional argument but 2 were given
`

**Comment by romanz** [comment]
Please also update the `libagent` package (which contains the SSH and GPG agent implementation).
The `trezor-agent` package only adds the TREZOR-related scripts, so you should update them together:
```
$ pip install --user -e trezor-agent/libagent
$ pip install --user -e trezor-agent/agents/trezor
```

**Comment by korzq** [comment]
It doesn't seems like I can install libagent from the repo using the command `pip install --user -e trezor-agent/libagent`. `Directory 'trezor-agent/libagent' is not installable. File 'setup.py' not found.`

Here is the entire trezor-agent install log
```
λ pip install --user -e trezor-agent/agents/trezor
Obtaining file:///home/eric/trezor-agent/agents/trezor
Collecting libagent>=0.13.0 (from trezor-agent==0.10.0)
  Using cached https://files.pythonhosted.org/packages/05/e8/5189585c7c0546c1b54fd27f8f84d9d5b3c254da50cab3d5dca8e5ed6aea/libagent-0.13.0.tar.gz
Requirement already satisfied: trezor[hidapi]>=0.11.0 in ./.local/lib/python3.7/site-packages (from trezor-agent==0.10.0) (0.11.1)
Requirement already satisfied: docutils>=0.14 in /usr/lib/python3.7/site-packages (from libagent>=0.13.0->trezor-agent==0.10.0) (0.14)
Requirement already satisfied: wheel>=0.32.3 in ./.local/lib/python3.7/site-packages (from libagent>=0.13.0->trezor-agent==0.10.0) (0.33.1)
Requirement already satisfied: backports.shutil_which>=3.5.1 in ./.local/lib/python3.7/site-packages (from libagent>=0.13.0->trezor-agent==0.10.0) (3.5.2)
Requirement already satisfied: ConfigArgParse>=0.12.1 in ./.local/lib/python3.7/site-packages (from libagent>=0.13.0->trezor-agent==0.10.0) (0.14.0)
Requirement already satisfied: python-daemon>=2.1.2 in ./.local/lib/python3.7/site-packages (from libagent>=0.13.0->trezor-agent==0.10.0) (2.2.3)
Requirement already satisfied: ecdsa>=0.13 in ./.local/lib/python3.7/site-packages (from libagent>=0.13.0->trezor-agent==0.10.0) (0.13)
Requirement already satisfied: ed25519>=1.4 in ./.local/lib/python3.7/site-packages (from libagent>=0.13.0->trezor-agent==0.10.0) (1.4)
Requirement already satisfied: mnemonic>=0.18 in ./.local/lib/python3.7/site-packages (from libagent>=0.13.0->trezor-agent==0.10.0) (0.18)
Requirement already satisfied: pymsgbox>=1.0.6 in ./.local/lib/python3.7/site-packages (from libagent>=0.13.0->trezor-agent==0.10.0) (1.0.6)
Requirement already satisfied: semver>=2.2 in ./.local/lib/python3.7/site-packages (from libagent>=0.13.0->trezor-agent==0.10.0) (2.8.1)
Requirement already satisfied: unidecode>=0.4.20 in ./.local/lib/python3.7/site-packages (from libagent>=0.13.0->trezor-agent==0.10.0) (1.0.23)
Requirement already satisfied: pyblake2>=0.9.3 in ./.local/lib/python3.7/site-packages (from trezor[hidapi]>=0.11.0->trezor-agent==0.10.0) (1.1.2)
Requirement already satisfied: setuptools>=19.0 in /usr/lib/python3.7/site-packages (from trezor[hidapi]>=0.11.0->trezor-agent==0.10.0) (40.8.0)
Requirement already satisfied: construct>=2.9 in ./.local/lib/python3.7/site-packages (from trezor[hidapi]>=0.11.0->trezor-agent==0.10.0) (2.9.45)
Requirement already satisfied: typing-extensions>=3.6 in ./.local/lib/python3.7/site-packages (from trezor[hidapi]>=0.11.0->trezor-agent==0.10.0) (3.7.2)
Requirement already satisfied: requests>=2.4.0 in /usr/lib/python3.7/site-packages (from trezor[hidapi]>=0.11.0->trezor-agent==0.10.0) (2.21.0)
Requirement already satisfied: click<8,>=7 in ./.local/lib/python3.7/site-packages (from trezor[hidapi]>=0.11.0->trezor-agent==0.10.0) (7.0)
Requirement already satisfied: libusb1>=1.6.4 in ./.local/lib/python3.7/site-packages (from trezor[hidapi]>=0.11.0->trezor-agent==0.10.0) (1.7)
Requirement already satisfied: hidapi>=0.7.99.post20; extra == "hidapi" in ./.local/lib/python3.7/site-packages (from trezor[hidapi]>=0.11.0->trezor-agent==0.10.0) (0.7.99.post21)
Requirement already satisfied: lockfile>=0.10 in /usr/lib/python3.7/site-packages (from python-daemon>=2.1.2->libagent>=0.13.0->trezor-agent==0.10.0) (0.12.2)
Requirement already satisfied: pbkdf2 in ./.local/lib/python3.7/site-packages (from mnemonic>=0.18->libagent>=0.13.0->trezor-agent==0.10.0) (1.3)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.7/site-packages (from requests>=2.4.0->trezor[hidapi]>=0.11.0->trezor-agent==0.10.0) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.7/site-packages (from requests>=2.4.0->trezor[hidapi]>=0.11.0->trezor-agent==0.10.0) (2.8)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.7/site-packages (from requests>=2.4.0->trezor[hidapi]>=0.11.0->trezor-agent==0.10.0) (1.24.1)
Building wheels for collected packages: libagent
  Running setup.py bdist_wheel for libagent ... done
  Stored in directory: /home/eric/.cache/pip/wheels/40/b7/4b/2fdec2b24b3b0caa5714a63729830966932d62619dcdf6ad7f
Successfully built libagent
Installing collected packages: libagent, trezor-agent
  Running setup.py develop for trezor-agent
Successfully installed libagent-0.13.0 trezor-agent
```

**Comment by romanz** [comment]
If you're inside the trezor-agent repo, you can install it using `pip install --user -e libagent`.

**Comment by korzq** [comment]
same error

**Comment by romanz** [comment]
Oops, my bad.
Could you please run:
```
pip install -U --user -e libagent
```

**Comment by korzq** [comment]
It is working now. Thanks!! Shall I close the issue?
And it doesn't seems like the version number of libagent has changed.

**Comment by romanz** [comment]
You're welcome :)
I will release a new version today.

**Comment by romanz** [comment]
https://pypi.org/project/libagent/0.13.1/
