### ISSUE TITLE
Public Key Export Fails

### ISSUE THREAD

**Issue by SpaceAgeMinds** [romanz/trezor-agent#291]
Has any steps changed from whats in the docs?
System: Debian 9
Trezor Firmware: 1.8.1
Let me know if I can provide any more information.

While trying to export my public key for github... 

`trezor-agent -v -e ed25519 git@github.com`

I get the following error...
```
2019-05-24 17:52:35,270 INFO         identity #0: <ssh://git@github.com|ed25519>                                                          [__init__.py:201]
Traceback (most recent call last):
  File "/usr/local/bin/trezor-agent", line 11, in <module>
    sys.exit(ssh_agent())
  File "/usr/local/bin/trezor_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/home/sysmin/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 130, in wrapper
    return func(*args, **kwargs)
  File "/home/sysmin/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 221, in main
    for pk in conn.public_keys():
  File "/home/sysmin/.local/lib/python2.7/site-packages/libagent/ssh/__init__.py", line 165, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/home/sysmin/.local/lib/python2.7/site-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/home/sysmin/.local/lib/python2.7/site-packages/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/home/sysmin/.local/lib/python2.7/site-packages/libagent/device/trezor.py", line 62, in connect
    transport = self._defs.Transport(d)
  File "/usr/lib/python2.7/dist-packages/trezorlib/transport_hid.py", line 140, in HidTransport
    transport = path_to_transport(device[0])
  File "/usr/lib/python2.7/dist-packages/trezorlib/transport_hid.py", line 35, in path_to_transport
    raise ConnectionError("Connection failed")
trezorlib.transport.ConnectionError: Connection failed
```

**Comment by jonathancross** [comment]
Does this happen with all ed25519 keys?

**Comment by SpaceAgeMinds** [comment]
When you say "all ed25519" do you mean the above command but with another email?

eg. "trezor-agent -v -e ed25519 other@example.com"

Then yes, regardless of the email provided I still get the same error.

**Comment by SpaceAgeMinds** [comment]
I've tested the newest release with github and everything seems to work.

Notes:
1. I've since updated my OS to debian 10.
2. The alias I used "alias trezor-git='trezor-agent -e ed25519 git@github.com -- git'"
3. I used pip3 to install.
4. I mostly followed the install instructions from the doc with minor changes, see #3, I also had to add the ~/.local/bin to my path.

Please close this issue at your convenience.

**Comment by SpaceAgeMinds** [comment]
I've tested the newest release with github and everything seems to work.

Notes:

  1. I've since updated my OS to debian 10.
  2. The alias I used "alias trezor-git='trezor-agent -e ed25519 git@github.com -- git'"
  3. I used pip3 to install.
  4. I mostly followed the install instructions from the doc with minor changes, see #3, I also had to add the ~/.local/bin to my path.

**Comment by jonathancross** [comment]
Fantastic, thanks for the follow up @SpaceAgeMinds!
