### ISSUE TITLE
trezor-gpg init fails when passphrase is used

### ISSUE THREAD

**Issue by EDmitry** [romanz/trezor-agent#308]
When running trezor-gpg init "identity", the command fails:

gpg: inserting ownertrust of 6
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: error reading key: No secret key
Traceback (most recent call last):
  File "/home/user/.local/bin/trezor-gpg", line 10, in <module>
    sys.exit(gpg_tool())
  File "/home/user/.local/bin/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/home/user/.local/lib/python3.7/site-packages/libagent/gpg/__init__.py", line 324, in main
    return args.func(device_type=device_type, args=args)
  File "/home/user/.local/lib/python3.7/site-packages/libagent/gpg/__init__.py", line 199, in run_init
    '--list-secret-keys', args.user_id]))
  File "/home/user/.local/lib/python3.7/site-packages/libagent/gpg/__init__.py", line 104, in check_call
    subprocess.check_call(args=args, stdin=stdin, env=env)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call

If I enter an empty passphrase for the Trezor, it surprisingly exports the keys correctly.

**Comment by EDmitry** [comment]
When I enter the passphrase on the device itself, I hit the same issue.

**Comment by EDmitry** [comment]
After some experimenting I found that it's not related to passphrases. What I was actually doing was removing .gnupg/trezor and regenerating keys. But I think there is some other state that doesn't get cleared in between new key extractions. To complicate things, I'm using Qubes OS. Restarting a Qube helps. I can check if that's the case on a standalone system.

**Comment by EDmitry** [comment]
Looks like trezor-agent is running and should be killed. Closing.
