### ISSUE TITLE
trezorctl sd-protect enable: trezorlib.exceptions.TrezorFailure: UnexpectedMessage: Unexpected message

### ISSUE THREAD

**Issue by xaionaro** [romanz/trezor-agent#315]
Hello.

```
[xaionaro@void ~]$ trezorctl sd-protect enable
Traceback (most recent call last):
  File "/usr/local/bin/trezorctl", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/trezorlib/cli/device.py", line 265, in sd_protect
    return device.sd_protect(client, operation)
  File "/usr/local/lib/python3.7/site-packages/trezorlib/tools.py", line 212, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/trezorlib/device.py", line 102, in sd_protect
    ret = client.call(messages.SdProtect(operation=operation))
  File "/usr/local/lib/python3.7/site-packages/trezorlib/tools.py", line 233, in wrapped_f
    return f(client, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/trezorlib/client.py", line 222, in call
    raise exceptions.TrezorFailure(resp)
trezorlib.exceptions.TrezorFailure: UnexpectedMessage: Unexpected message
```

```
[xaionaro@void ~]$ trezorctl list
webusb:005:1:4
```

Device model: Trezor T

**Comment by matejcik** [comment]
presumably your TT firmware is too old to support `sd-protect`.
also this is the wrong repository, it has nothing to do with trezorctl

**Comment by xaionaro** [comment]
> also this is the wrong repository, it has nothing to do with trezorctl

Whoops, sorry :(
