### ISSUE TITLE
trezor-gpg-agent crashes on Arch

### ISSUE THREAD

**Issue by dekoza** [romanz/trezor-agent#321]
```pytrace
$ trezor-gpg init dominik
2020-04-08 15:30:41,132 WARNING      This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility! [__init__.py:118]
2020-04-08 15:30:41,153 WARNING      NOTE: in order to re-generate the exact same GPG key later, run this command with "--time=1586352641" commandline flag (to set the timestamp of the GPG key manually). [__init__.py:33]
Traceback (most recent call last):
  File "/usr/bin/trezor-gpg", line 8, in <module>
    sys.exit(gpg_tool())
  File "/usr/bin/trezor_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/usr/lib/python3.8/site-packages/libagent/gpg/__init__.py", line 324, in main
    return args.func(device_type=device_type, args=args)
  File "/usr/lib/python3.8/site-packages/libagent/gpg/__init__.py", line 182, in run_init
    export_public_key(device_type, args))
  File "/usr/lib/python3.8/site-packages/libagent/gpg/__init__.py", line 39, in export_public_key
    verifying_key = c.pubkey(identity=identity, ecdh=False)
  File "/usr/lib/python3.8/site-packages/libagent/gpg/client.py", line 27, in pubkey
    with self.device:
  File "/usr/lib/python3.8/site-packages/libagent/device/interface.py", line 126, in __enter__
    self.conn = self.connect()
  File "/usr/lib/python3.8/site-packages/libagent/device/trezor.py", line 55, in connect
    connection = self._defs.Client(transport=transport,
TypeError: __init__() got an unexpected keyword argument 'state'
```
This is latest Manjaro Linux (Arch clone). All dependencies installed from AUR (via `yay`), only `trezor-agent` was installed using pip (as root). `trezord` and udev rules are also installed. Trezor works seamlessly with browser.

```
$pip freeze|grep trezor
trezor==0.12.0
trezor-agent==0.10.0
```

After forcefully downgrading `trezor` (python-trezor) to 0.11.6 - crashes stopped.

**Comment by dekoza** [comment]
Duplicate of #319
