### ISSUE TITLE
Trezor One 1.8.3 - cannot generate public key

### ISSUE THREAD

**Issue by xvador** [romanz/trezor-agent#323]
```
Traceback (most recent call last):
  File "/usr/local/bin/trezor-agent", line 11, in <module>
    sys.exit(ssh_agent())
  File "/usr/local/bin/trezor_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/usr/local/lib/python3.6/dist-packages/libagent/ssh/__init__.py", line 174, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/libagent/ssh/__init__.py", line 311, in main
    for pk in conn.public_keys():
  File "/usr/local/lib/python3.6/dist-packages/libagent/ssh/__init__.py", line 210, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/usr/local/lib/python3.6/dist-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/usr/local/lib/python3.6/dist-packages/libagent/device/interface.py", line 126, in __enter__
    self.conn = self.connect()
  File "/usr/local/lib/python3.6/dist-packages/libagent/device/trezor.py", line 57, in connect
    state=self.__class__.cached_state)
TypeError: __init__() got an unexpected keyword argument 'state'
```

**Comment by rishanb** [comment]
Experiencing the same issue on both Ubuntu 18.04 and 19.10 and have tried installing various versions of Python. Would love some help.

**Comment by rishanb** [comment]
@romanz I've contacted you Keybase.io in case you need more details or want a video etc.

**Comment by romanz** [comment]
Thanks for reporting the issue!
I think it may be related to https://github.com/romanz/trezor-agent/pull/322.

**Comment by romanz** [comment]
I have release a new versions for `libagent` and `trezor-agent` that should resolve the issue:
- https://pypi.org/project/libagent/0.14.0/
- https://pypi.org/project/trezor-agent/0.11.0/

**Comment by romanz** [comment]
You can try to update your versions using:
```
$ pip install -U trezor-agent
```

**Comment by rishanb** [comment]
Thank you sir will try ASAP and report back.

**Comment by grnqrtr** [comment]
Fixed for me, thanks!

**Comment by rishanb** [comment]
Perfect, working on my end too.

**Comment by rishanb** [comment]
Thank you!

**Comment by romanz** [comment]
Happy to help :)
