### ISSUE TITLE
macOS - too many values to unpack

### ISSUE THREAD

**Issue by MAHDTech** [romanz/trezor-agent#327]
Hi,

I've recently switched from Linux to macOS and have an error with trezor-agent that I have not seen before when using Linux. 

Intermittently this will occur and requires restarting the agent.

I installed trezor-agent and libusb via homebrew

> trezor-agent: v0.11.0
> libusb: v1.0.23

I'm running trezor-agent daemonized as follows:

```
trezor-agent --verbose \
	--daemonize \
	--timeout 60 \
	--log-file "$HOME/.logs/tssh.log"
	--sock-path "$HOME/.ssh/trezor-agent/tssh.sock" \
	--cache-expiry-seconds 300 \
	"$HOME/.ssh/trezor-agent/identities.conf"
```

Has anyone seen this particular error before?

```
2020-04-24 04:27:28,855 INFO         Enumerating HidTransport: found 0 devices                                                            [__init__.py:120]
2020-04-24 04:27:28,856 INFO         Enumerating UdpTransport: found 0 devices                                                            [__init__.py:120]
2020-04-24 04:27:28,862 INFO         Enumerating BridgeTransport: found 0 devices                                                         [__init__.py:120]
2020-04-24 04:27:28,870 INFO         Enumerating WebUsbTransport: found 1 devices                                                         [__init__.py:120]
2020-04-24 04:27:28,870 INFO         creating client instance for device: webusb:020:1                                                    [client.py:91]
2020-04-24 04:27:39,728 WARNING      error: too many values to unpack (expected 3)                                                        [server.py:100]

Traceback (most recent call last):
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/server.py", line 95, in handle_connection
    reply = handler.handle(msg=msg)
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/ssh/protocol.py", line 103, in handle
    reply = method(buf=buf)
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/ssh/protocol.py", line 111, in list_pubs
    keys = self.conn.parse_public_keys()
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/ssh/__init__.py", line 215, in parse_public_keys
    for pk in self.public_keys()]
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/ssh/__init__.py", line 215, in <listcomp>
    for pk in self.public_keys()]
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/formats.py", line 197, in import_public_key
    file_type, base64blob, name = line.split()
ValueError: too many values to unpack (expected 3)
2020-04-24 04:27:39,728 WARNING      error: too many values to unpack (expected 3)                                                        [server.py:100]
Traceback (most recent call last):
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/server.py", line 95, in handle_connection
    reply = handler.handle(msg=msg)
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/ssh/protocol.py", line 103, in handle
    reply = method(buf=buf)
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/ssh/protocol.py", line 111, in list_pubs
    keys = self.conn.parse_public_keys()
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/ssh/__init__.py", line 215, in parse_public_keys
    for pk in self.public_keys()]
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/ssh/__init__.py", line 215, in <listcomp>
    for pk in self.public_keys()]
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/formats.py", line 197, in import_public_key
    file_type, base64blob, name = line.split()
ValueError: too many values to unpack (expected 3)
2020-04-24 04:27:39,728 WARNING      error: too many values to unpack (expected 3)                                                        [server.py:100]
Traceback (most recent call last):
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/server.py", line 95, in handle_connection
    reply = handler.handle(msg=msg)
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/ssh/protocol.py", line 103, in handle
    reply = method(buf=buf)
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/ssh/protocol.py", line 111, in list_pubs
    keys = self.conn.parse_public_keys()
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/ssh/__init__.py", line 215, in parse_public_keys
    for pk in self.public_keys()]
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/ssh/__init__.py", line 215, in <listcomp>
    for pk in self.public_keys()]
  File "/usr/local/Cellar/trezor-agent/0.11.0/libexec/lib/python3.7/site-packages/libagent/formats.py", line 197, in import_public_key
    file_type, base64blob, name = line.split()
```

**Comment by romanz** [comment]
It seems that `$HOME/.ssh/trezor-agent/identities.conf` has unexpected format.
Currently, my tool expects it to be a collection of SSH public keys, which can be generated using the `trezor-agent` command:
```
$ trezor-agent some-server-hostname
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLRc3RvGRG2siC6f6/alWNTh1n6Sx4Qp7c/4Qi1bK3fgYp6oJ25WMsEzWAmAvN2pZSAmdpBZD2InPm9EHgafUFI= <ssh://some-server-hostname|nist256p1>
```

**Comment by MAHDTech** [comment]
Thanks @romanz 

Has the format of the file changed in any recent versions? I copied my working one from linux but the file is like this example below, there is only one value, not the 3.

```
<ssh://github.com|ed25519>
<ssh://gitlab.com|ed25519>
<ssh://bitbucket.org|ed25519>
```

You saying it should instead have the 3 parts like so?

```
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLRc3RvGRG2siC6f6/alWNTh1n6Sx4Qp7c/4Qi1bK3fgYp6oJ25WMsEzWAmAvN2pZSAmdpBZD2InPm9EHgafUFI= <ssh://some-server-hostname|nist256p1>
```

I'll give that a try, it's odd cause it will work a few times and then crash where I would have expected it to not work at all.

**Comment by MAHDTech** [comment]
OK, I've not had any further crashes since the modification so I'm going to assume it was an ID10T error with my identifies file. 😄
