### ISSUE TITLE
`OPTION ttyname=not a tty` results in `TypeError: handle_option() takes 2 positional arguments but 4 were given`

### ISSUE THREAD

**Issue by afreakk** [romanz/trezor-agent#349]
Using gpg in script outside interactive terminal results in the following error.
Also using aws-vault inside interactive terminal with pass backend with trezor gpg results in the following error:
```
2021-03-24 15:37:27,321 DEBUG        waiting for connection on /run/user/1000/gnupg/d.wu4no9py1cz591u7io9rsjpm/S.gpg-agent                [agent.py:14]
2021-03-24 15:37:27,322 DEBUG        accepted connection on /run/user/1000/gnupg/d.wu4no9py1cz591u7io9rsjpm/S.gpg-agent                   [agent.py:20]
2021-03-24 15:37:27,322 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
2021-03-24 15:37:27,322 DEBUG        -> b'RESET'                                                                                          [keyring.py:71]
2021-03-24 15:37:27,322 DEBUG        <- b'OK'                                                                                             [keyring.py:53]
2021-03-24 15:37:27,322 DEBUG        -> b'OPTION ttyname=not a tty'                                                                       [keyring.py:71]
2021-03-24 15:37:27,322 ERROR        handler failed: handle_option() takes 2 positional arguments but 4 were given                        [__init__.py:271]
Traceback (most recent call last):
  File "/nix/store/i623x14ay25nlkvlmasjv8sbyxzxihcp-python3.8-libagent-0.14.1/lib/python3.8/site-packages/libagent/gpg/__init__.py", line 263, in run_agent
    handler.handle(conn)
  File "/nix/store/i623x14ay25nlkvlmasjv8sbyxzxihcp-python3.8-libagent-0.14.1/lib/python3.8/site-packages/libagent/gpg/agent.py", line 242, in handle
    handler(conn, args)
  File "/nix/store/i623x14ay25nlkvlmasjv8sbyxzxihcp-python3.8-libagent-0.14.1/lib/python3.8/site-packages/libagent/gpg/agent.py", line 92, in <lambda>
    b'OPTION': lambda _, args: self.handle_option(*args),
TypeError: handle_option() takes 2 positional arguments but 4 were given
2021-03-24 15:37:27,322 DEBUG        waiting for connection on /run/user/1000/gnupg/d.wu4no9py1cz591u7io9rsjpm/S.gpg-agent                [agent.py:14]
```
`OPTION ttyname=not a tty` seems to split into multiple arguments, which `handle_option` does not like.

**Comment by doolio** [comment]
You need to set `export GPG_TTY=$(tty)` in your shell rc file (e.g. ~/.bashrc) unfortunately. Setting it in ~/.profile as one should does not necessarily work as it depends on your whether your graphical display starts a login shell or not (see the top answer here https://superuser.com/questions/183870/difference-between-bashrc-and-bash-profile?answertab=active#tab-top). On my Debian 11 (stable) machine with LightDM+Mate does not for example.
