### ISSUE TITLE
Poor Python 3 support

### ISSUE THREAD

**Issue by dekoza** [romanz/trezor-agent#36]
The tests are passing for Py3 although when I run `trezor-gpg agent` I get this:

```traceback
Traceback (most recent call last):
  File "/home/minder/.virtualenvs/trezor/bin/trezor-gpg", line 11, in <module>
    load_entry_point('trezor-agent==0.7.0', 'console_scripts', 'trezor-gpg')()
  File "/home/minder/.virtualenvs/trezor/lib/python3.5/site-packages/trezor_agent/gpg/__main__.py", line 95, in main
    args.run(args)
  File "/home/minder/.virtualenvs/trezor/lib/python3.5/site-packages/trezor_agent/gpg/__main__.py", line 65, in run_agent
    sock_path = keyring.get_agent_sock_path()
  File "/home/minder/.virtualenvs/trezor/lib/python3.5/site-packages/trezor_agent/gpg/keyring.py", line 18, in get_agent_sock_path
    lines = sp.check_output(['gpgconf', '--list-dirs']).strip().split('\n')
TypeError: a bytes-like object is required, not 'str'
```

Nevertheless I'm working on a solution :smile:

**Comment by dekoza** [comment]
`keepkeylib` is not Py3 compatible :disappointed:

**Comment by romanz** [comment]
Thanks for reporting this issue and the fixes :)

**Comment by dekoza** [comment]
I know. I'm wondering if we could switch `keepkey` for `python-trezor.trezorlib` - it looks like they fixed the Py3 issues there as It Works For Me™ :wink: 

I'll investigate and post appropriate patch in case of success.

**Comment by dekoza** [comment]
Wait a minute... :stuck_out_tongue: `trezorlib` *is* being used :laughing: Silly me.

**Comment by romanz** [comment]
Now GPG feature should also work on Python 3: https://github.com/romanz/trezor-agent/commit/65d2c04478837b96709e258c50b9fad95b555782
