### ISSUE TITLE
SSH agent fails

### ISSUE THREAD

**Issue by AlexanderPavlenko** [romanz/trezor-agent#388]
openssh (stable 8.9p1) fails to use the agent
```
WARNING      error: 27                                                                                            [server.py:100]
Traceback (most recent call last):
  File "/Users/lexi/.local/pipx/venvs/trezor-agent/lib/python3.9/site-packages/libagent/server.py", line 95, in handle_connection
    reply = handler.handle(msg=msg)
  File "/Users/lexi/.local/pipx/venvs/trezor-agent/lib/python3.9/site-packages/libagent/ssh/protocol.py", line 98, in handle
    log.warning('Unsupported command: %s (%d)', msg_name(code), code)
  File "/Users/lexi/.local/pipx/venvs/trezor-agent/lib/python3.9/site-packages/libagent/ssh/protocol.py", line 54, in msg_name
    return ids[code]
KeyError: 27
```
Probably caused by https://github.com/openssh/openssh-portable/blob/master/authfd.h#L104
Hotfixed by adding `SSH_AGENTC_EXTENSION=27,` to libagent/ssh/protocol.py

**Comment by yanchenko-igor** [comment]
@AlexanderPavlenko This is already fixed in #384
