### ISSUE TITLE
Error when running: `sudo ledger-agent username@hostname`

### ISSUE THREAD

**Issue by jrbecart** [romanz/trezor-agent#391]
When running the following command `sudo ledger-agent username@hostname` on Windows 10 WSL2 (ubuntu 20.04) I got the following error message:

```bash
2022-04-20 16:09:48,372 WARNING      DISPLAY not defined                                                                                  [ui.py:92]
Traceback (most recent call last):
  File "/usr/local/bin/ledger-agent", line 8, in <module>
    sys.exit(ssh_agent())
  File "/usr/local/bin/ledger_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/usr/local/lib/python3.8/dist-packages/libagent/ssh/__init__.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/libagent/ssh/__init__.py", line 308, in main
    for pk in conn.public_keys():
  File "/usr/local/lib/python3.8/dist-packages/libagent/ssh/__init__.py", line 209, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/usr/local/lib/python3.8/dist-packages/libagent/ssh/client.py", line 26, in export_public_keys
    vk = self.device.pubkey(identity=i)
  File "/usr/local/lib/python3.8/dist-packages/libagent/device/ledger.py", line 66, in pubkey
    result = bytearray(self.conn.exchange(bytes(apdu)))
  File "/usr/local/lib/python3.8/dist-packages/ledgerblue/comm.py", line 145, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6b0c (Unknown reason)
```
Does anyone have any idea?

**Comment by markus-seidl** [comment]
I guess you do not have switched the ledger to SSH/GPG mode?

**Comment by jrbecart** [comment]
> I guess you do not have switched the ledger to SSH/GPG mode?

Your guess is wrong. I guess you do not use WSL2 ?

**Comment by romanz** [comment]
I suggest asking here: https://github.com/LedgerHQ/app-ssh-agent/issues
