### ISSUE TITLE
libagent.device.interface.DeviceError: Trezor error: DataError: bytes overflow

### ISSUE THREAD

**Issue by iskradelta** [romanz/trezor-agent#407]
trezor-agent -c user@datass gives this

The trezor asks for PIN, right pin entered says Verified, asks for passphrase, clicks OK. Then this crash.
```
....
WARNING unparsed blob
.....
2023-01-09 16:40:21,088 DEBUG        vendor   : trezor.io                                                                                 [trezor.py:36]
2023-01-09 16:40:21,089 DEBUG        version  : 1.11.2                                                                                    [trezor.py:40]
2023-01-09 16:40:21,089 DEBUG        revision : b'0d87b55ba4fed7eecc72bf2a94ee473830b095e9'                                               [trezor.py:41]
2023-01-09 16:40:21,089 DEBUG        sending message: GetAddress                                                                          [client.py:149]
2023-01-09 16:40:21,214 DEBUG        received message: Address                                                                            [client.py:168]
2023-01-09 16:40:21,214 DEBUG        identity parts: ['ssh://', 'user@', 'datass']                                                       [interface.py:46]
2023-01-09 16:40:21,214 DEBUG        "<ssh://user@datass|nist256p1>" signing b'\x00\x00\x00@\x1f....some....mo.xa6' (nist256p1) on Trezor [trezor.py:109]
2023-01-09 16:40:21,215 DEBUG        sending message: SignIdentity                                                                        [client.py:149]
2023-01-09 16:40:21,223 DEBUG        received message: Failure                                                                            [client.py:168]
2023-01-09 16:40:21,223 DEBUG        Trezor error: DataError: bytes overflow                                                              [trezor.py:124]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/device/trezor.py", line 112, in sign_with_pubkey
    result = self._defs.sign_identity(
  File "/usr/lib/python3.10/site-packages/trezorlib/tools.py", line 267, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/trezorlib/misc.py", line 41, in sign_identity
    return client.call(
  File "/usr/lib/python3.10/site-packages/trezorlib/tools.py", line 290, in wrapped_f
    return f(client, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/trezorlib/client.py", line 258, in call
    raise exceptions.TrezorFailure(resp)
trezorlib.exceptions.TrezorFailure: DataError: bytes overflow
2023-01-09 16:40:21,224 ERROR        signature with "<ssh://user@datass|nist256p1>" key failed                                           [protocol.py:151]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/device/trezor.py", line 112, in sign_with_pubkey
    result = self._defs.sign_identity(
  File "/usr/lib/python3.10/site-packages/trezorlib/tools.py", line 267, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/trezorlib/misc.py", line 41, in sign_identity
    return client.call(
  File "/usr/lib/python3.10/site-packages/trezorlib/tools.py", line 290, in wrapped_f
    return f(client, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/trezorlib/client.py", line 258, in call
    raise exceptions.TrezorFailure(resp)
trezorlib.exceptions.TrezorFailure: DataError: bytes overflow
```

Tried both installing from pip and from git clone,
btw the version is wrong in both pip and from git clone, trezor-agent says it is 0.12.0 but its 0.14.something the setup.py is not updated.

**Comment by romanz** [comment]
Many thanks for reporting this issue!
It's probably related to #408.

**Comment by romanz** [comment]
The fix is merged https://github.com/trezor/trezor-firmware/commit/72f456cc1753a230d2155e4124cee87685ba74de.
