### ISSUE TITLE
TREZOR 1 fails to sign OpenSSH 8.9+ challenge

### ISSUE THREAD

**Issue by romanz** [romanz/trezor-agent#408]
> Many thanks - I've reproduced the issue using TREZOR 1, with OpenSSH 8.9 client & server:
```
2023-01-12 20:28:04,950 DEBUG        "<ssh://foo|nist256p1>" signing b'\x00\x00\x00 4\xd5v}\x9f\xa5w\xe8\xe8R\xfb|\xf8\xee\x81{\xb7\xebE\x03>b\xd4WJq\x92\xc03\xd7\x8cc2\x00\x00\x00\x04user\x00\x00\x00\x0essh-connection\x00\x00\x00#publickey-hostbound-v00@openssh.com\x01\x00\x00\x00\x13ecdsa-sha2-nistp256\x00\x00\x00h\x00\x00\x00\x13ecdsa-sha2-nistp256\x00\x00\x00\x08nistp256\x00\x00\x00A\x04Hw\x83\x87\x10u\xef\xcc\xf9\xca\xee\xa9b\xdc$[\xd0\x1d\x07\x1e\x960\xa4\x10\xaf\xfew\xb8\x0eT\xa6\xed\xd6:z\x00\x9a\\|o^\\y}6\xff\xc4KM(\x18\xc1}\x7f\x97\x84m\x17\xb3\xb9LA\xb0D\x00\x00\x003\x00\x00\x00\x0bssh-ed25519\x00\x00\x00 \x9fk\xc3e;\x7fj\xa88^\xc6\xbc\x84\x8b\xb9YEJ\\)X\xc9\xe0IN\xe1\x9c\x91\xe2e0\x15' (nist256p1) on Trezor [trezor.py:109]
2023-01-12 20:28:04,950 DEBUG        sending message: SignIdentity                                                                        [client.py:149]
2023-01-12 20:28:04,957 DEBUG        received message: Failure                                                                            [client.py:168]
2023-01-12 20:28:04,957 DEBUG        Trezor error: DataError: bytes overflow                                                              [trezor.py:124]
Traceback (most recent call last):
  File "/media/user/HDD/roman/Code/trezor-agent/libagent/device/trezor.py", line 112, in sign_with_pubkey
    result = self._defs.sign_identity(
  File "/media/user/HDD/roman/Code/trezor-firmware/python/src/trezorlib/tools.py", line 267, in wrapped_f
    ret = f(*args, **kwargs)
  File "/media/user/HDD/roman/Code/trezor-firmware/python/src/trezorlib/misc.py", line 41, in sign_identity
    return client.call(
  File "/media/user/HDD/roman/Code/trezor-firmware/python/src/trezorlib/tools.py", line 290, in wrapped_f
    return f(client, *args, **kwargs)
  File "/media/user/HDD/roman/Code/trezor-firmware/python/src/trezorlib/client.py", line 258, in call
    raise exceptions.TrezorFailure(resp)
trezorlib.exceptions.TrezorFailure: DataError: bytes overflow
```

_Originally posted by @romanz in https://github.com/romanz/trezor-agent/issues/387#issuecomment-1380844054_
      
Note that the blob being signed contains 289 bytes:
```
In [1]: len(b'\x00\x00\x00 4\xd5v}\x9f\xa5w\xe8\xe8R\xfb|\xf8\xee\x81{\xb7\xebE\x03>b\xd4WJq\x92\xc03\xd7\x8cc2\x00\x00\x00\x04user\x00\x00\x00\x0essh-connection\x00\x00\x00#publickey-hostbound-v00@openssh.com\x01\x00\x00\x00\x13ecdsa-sha2-nistp256\x00\x00\x00h\x00\x00\x00\x13ecdsa
   ...: -sha2-nistp256\x00\x00\x00\x08nistp256\x00\x00\x00A\x04Hw\x83\x87\x10u\xef\xcc\xf9\xca\xee\xa9b\xdc$[\xd0\x1d\x07\x1e\x960\xa4\x10\xaf\xfew\xb8\x0eT\xa6\xed\xd6:z\x00\x9a\\|o^\\y}6\xff\xc4KM(\x18\xc1}\x7f\x97\x84m\x17\xb3\xb9LA\xb0D\x00\x00\x003\x00\x00\x00\x0bssh-ed25519\x
   ...: 00\x00\x00 \x9fk\xc3e;\x7fj\xa88^\xc6\xbc\x84\x8b\xb9YEJ\\)X\xc9\xe0IN\xe1\x9c\x91\xe2e0\x15')
Out[1]: 289
```

IIUC, this happens due to the following limit in TREZOR 1 firmware (currently set to 256 bytes):
https://github.com/trezor/trezor-firmware/blob/c63b334136776a385b2fa26ff76fabc19bb431a2/legacy/firmware/protob/messages-crypto.options#L21

**Comment by romanz** [comment]
IIUC, this happens due to the following limit in TREZOR 1 firmware:
https://github.com/trezor/trezor-firmware/blob/c63b334136776a385b2fa26ff76fabc19bb431a2/legacy/firmware/protob/messages-crypto.options#L21

**Comment by romanz** [comment]
I have increased the limit to 512 bytes (https://github.com/trezor/trezor-firmware/pull/2743) and it seem to work (on an emulator) using OpenSSH 8.9 client & server:
```
2023-01-12 21:20:10,717 DEBUG        using key b'<ssh://foo|nist256p1>' (24:d9:75:37:31:08:96:d9:50:fd:d1:7f:5c:08:b2:43)                 [protocol.py:138]
2023-01-12 21:20:10,717 DEBUG        signing 289-byte blob with "<ssh://foo|nist256p1>" key                                               [protocol.py:145]
2023-01-12 21:20:10,717 DEBUG        blob: b'\x00\x00\x00  \x94\x1dW\xabv\xbf\x95\xbf\xa3\x19d\xc4\xb0\x03\xfc\xc4Bt\xd2\x0c\xbeLm\xf6t\t[<\xdc\xb3*2\x00\x00\x00\x04user\x00\x00\x00\x0essh-connection\x00\x00\x00#publickey-hostbound-v00@openssh.com\x01\x00\x00\x00\x13ecdsa-sha2-nistp256\x00\x00\x00h\x00\x00\x00\x13ecdsa-sha2-nistp256\x00\x00\x00\x08nistp256\x00\x00\x00A\x04\xbd\x98\xbe"\xe1\x89<T\xdb\xe2)\xa3\xfc\x8b\x85\x1a\xc5{O\xa5\x8b2r!%\xa4u=\xbe\'\xf9kL\xeb~\xfdiCn."\x93\x01*b\xe2\xb5\xb5aT\xb4)\xbb\'\xd3\x01\xcdB\x9e\xc2\x05\x92\xd3\x0e\x00\x00\x003\x00\x00\x00\x0bssh-ed25519\x00\x00\x00 \x9fk\xc3e;\x7fj\xa88^\xc6\xbc\x84\x8b\xb9YEJ\\)X\xc9\xe0IN\xe1\x9c\x91\xe2e0\x15' [client.py:34]
2023-01-12 21:20:10,718 DEBUG        key type: b'ecdsa-sha2-nistp256'                                                                     [formats.py:58]
2023-01-12 21:20:10,718 DEBUG        curve name: b'nistp256'                                                                              [formats.py:68]
2023-01-12 21:20:10,718 WARNING      unparsed blob: b'\x00\x00\x003\x00\x00\x00\x0bssh-ed25519\x00\x00\x00 \x9fk\xc3e;\x7fj\xa88^\xc6\xbc\x84\x8b\xb9YEJ\\)X\xc9\xe0IN\xe1\x9c\x91\xe2e0\x15' [client.py:81]
2023-01-12 21:20:10,718 DEBUG        b'ssh-connection': user b'user' via b'publickey-hostbound-v00@openssh.com' (b'ecdsa-sha2-nistp256')  [client.py:40]
2023-01-12 21:20:10,718 DEBUG        nonce: b' \x94\x1dW\xabv\xbf\x95\xbf\xa3\x19d\xc4\xb0\x03\xfc\xc4Bt\xd2\x0c\xbeLm\xf6t\t[<\xdc\xb3*' [client.py:42]
2023-01-12 21:20:10,718 DEBUG        fingerprint: 24:d9:75:37:31:08:96:d9:50:fd:d1:7f:5c:08:b2:43                                         [client.py:44]
2023-01-12 21:20:10,718 DEBUG        hidden challenge size: 289 bytes                                                                     [client.py:45]
2023-01-12 21:20:10,718 DEBUG        identity parts: ['ssh://', 'foo']                                                                    [interface.py:46]
2023-01-12 21:20:10,718 INFO         please confirm user "user" login to "<ssh://foo|nist256p1>" using Trezor...                          [client.py:47]
2023-01-12 21:20:10,718 INFO         Enumerating WebUsbTransport: found 0 devices                                                         [__init__.py:138]
2023-01-12 21:20:10,719 DEBUG        Starting new HTTP connection (2): 127.0.0.1:21325                                                    [connectionpool.py:228]
2023-01-12 21:20:10,719 INFO         Enumerating BridgeTransport: found 0 devices                                                         [__init__.py:138]
2023-01-12 21:20:10,719 INFO         Enumerating UdpTransport: found 1 devices                                                            [__init__.py:138]
2023-01-12 21:20:10,720 INFO         Enumerating HidTransport: found 0 devices                                                            [__init__.py:138]
2023-01-12 21:20:10,720 DEBUG        using transport: udp:127.0.0.1:21324                                                                 [trezor.py:54]
2023-01-12 21:20:10,720 INFO         creating client instance for device: udp:127.0.0.1:21324                                             [client.py:115]
2023-01-12 21:20:10,720 DEBUG        sending message: Initialize                                                                          [client.py:149]
2023-01-12 21:20:10,721 DEBUG        received message: Features                                                                           [client.py:168]
2023-01-12 21:20:10,721 INFO         Successfully resumed session                                                                         [client.py:352]
2023-01-12 21:20:10,721 DEBUG        connected to Trezor C906E19794613145E3DF45F4                                                         [trezor.py:34]
2023-01-12 21:20:10,721 DEBUG        label    : SLIP-0014                                                                                 [trezor.py:35]
2023-01-12 21:20:10,721 DEBUG        vendor   : trezor.io                                                                                 [trezor.py:36]
2023-01-12 21:20:10,721 DEBUG        version  : 1.11.3                                                                                    [trezor.py:40]
2023-01-12 21:20:10,721 DEBUG        revision : b'6b849b02dd6437b271eec27ebce1b192a992ee38'                                               [trezor.py:41]
2023-01-12 21:20:10,721 DEBUG        sending message: GetAddress                                                                          [client.py:149]
2023-01-12 21:20:10,722 DEBUG        received message: Address                                                                            [client.py:168]
2023-01-12 21:20:10,722 DEBUG        identity parts: ['ssh://', 'foo']                                                                    [interface.py:46]
2023-01-12 21:20:10,722 DEBUG        "<ssh://foo|nist256p1>" signing b'\x00\x00\x00  \x94\x1dW\xabv\xbf\x95\xbf\xa3\x19d\xc4\xb0\x03\xfc\xc4Bt\xd2\x0c\xbeLm\xf6t\t[<\xdc\xb3*2\x00\x00\x00\x04user\x00\x00\x00\x0essh-connection\x00\x00\x00#publickey-hostbound-v00@openssh.com\x01\x00\x00\x00\x13ecdsa-sha2-nistp256\x00\x00\x00h\x00\x00\x00\x13ecdsa-sha2-nistp256\x00\x00\x00\x08nistp256\x00\x00\x00A\x04\xbd\x98\xbe"\xe1\x89<T\xdb\xe2)\xa3\xfc\x8b\x85\x1a\xc5{O\xa5\x8b2r!%\xa4u=\xbe\'\xf9kL\xeb~\xfdiCn."\x93\x01*b\xe2\xb5\xb5aT\xb4)\xbb\'\xd3\x01\xcdB\x9e\xc2\x05\x92\xd3\x0e\x00\x00\x003\x00\x00\x00\x0bssh-ed25519\x00\x00\x00 \x9fk\xc3e;\x7fj\xa88^\xc6\xbc\x84\x8b\xb9YEJ\\)X\xc9\xe0IN\xe1\x9c\x91\xe2e0\x15' (nist256p1) on Trezor [trezor.py:109]
2023-01-12 21:20:10,722 DEBUG        sending message: SignIdentity                                                                        [client.py:149]
2023-01-12 21:20:10,722 DEBUG        received message: ButtonRequest                                                                      [client.py:168]
2023-01-12 21:20:10,722 DEBUG        sending message: ButtonAck                                                                           [client.py:149]
2023-01-12 21:20:12,806 DEBUG        received message: SignedIdentity                                                                     [client.py:168]
2023-01-12 21:20:12,806 DEBUG        result: <SignedIdentity: {'public_key': b'\x02\xbd\x98\xbe"\xe1\x89<T\xdb\xe2)\xa3\xfc\x8b\x85\x1a\xc5{O\xa5\x8b2r!%\xa4u=\xbe\'\xf9k', 'signature': b'\x00\x8a\xd4\x1a\xe0\xbav\xacZ\xfa\xb4!gg\xae\xe6\x84W\xbdd\xd81\x93\xfc\n\x13\xce\xe6\x116\xbb\x86\xb2\x07P!\x08\xbe\x02\x8c\xb0\x92\xfeFH\xff/\xbc:%\xfa\xda\xcb\xecI\xe7D\xb3\xe9F\xac-\xa4\xc1\xe2'}> [trezor.py:118]
2023-01-12 21:20:12,806 DEBUG        signature: b'\x8a\xd4\x1a\xe0\xbav\xacZ\xfa\xb4!gg\xae\xe6\x84W\xbdd\xd81\x93\xfc\n\x13\xce\xe6\x116\xbb\x86\xb2\x07P!\x08\xbe\x02\x8c\xb0\x92\xfeFH\xff/\xbc:%\xfa\xda\xcb\xecI\xe7D\xb3\xe9F\xac-\xa4\xc1\xe2' [protocol.py:154]
2023-01-12 21:20:12,822 INFO         signature status: OK                                                                                 [protocol.py:158]
2023-01-12 21:20:12,822 DEBUG        signature size: 74 bytes                                                                             [protocol.py:163]
2023-01-12 21:20:12,822 DEBUG        reply: 110 bytes                                                                                     [protocol.py:108]
2023-01-12 21:20:12,829 DEBUG        goodbye agent                                                                                        [server.py:98]
```
@prusnak Would it please be possible to increase the current limit?

**Comment by iskradelta** [comment]
Pretty cool how fast you found but then also has a fix in place.

The build-docker.sh is running now with your limit adjustment, to see if its possible to get a firmware image and try it out on a real device.

**Comment by iskradelta** [comment]
Verified and it works, its amazing! Only the warning about unparsed blob is still there but thats okay.

It actually works! Thanks!

**Comment by romanz** [comment]
The fix is merged https://github.com/trezor/trezor-firmware/commit/72f456cc1753a230d2155e4124cee87685ba74de.

**Comment by m5x** [comment]
I have also encountered this error but upgrade to latest firmware (1.11.2) using the Trezor Suite didn't help. Will firmware with this fix reach Trezor Suite anytime soon or should people like me start looking for a way to build/update the firmware manually?

**Comment by prusnak** [comment]
> Will firmware with this fix reach Trezor Suite anytime soon

We are releasing the fix in the March firmware upate.

**Comment by m5x** [comment]
Installed firmware v1.12.1 and the issue is gone. Thanks!
