### ISSUE TITLE
error when attempting to use ssh-keygen for signing a message

### ISSUE THREAD

**Issue by iskradelta** [romanz/trezor-agent#410]
I was trying to use ssh-keygen to sign a message, but trezor-agent flashes the "enter passphrase" prompt and gets stuck there, or it gets stuck on "display pin prompt", while ssh-keygen says
```
ssh-keygen -Y sign -f ~/.ssh/id_ecdsa_sk -n file store/single.tar.age
Signing file store/single.tar.age
Confirm user presence for key ECDSA-SK SHA256:Frfrfrfrfr4
Couldn't sign message: device not found
Signing store/single.tar.age failed: device not found
```

I know it is not a good idea to use the main/master key, but was trying it out and want to use another identity for signing a message. Ideally it would be something like `trezor-agent -i user@datass` piped to a file so it contains only that specific public key. Next I would want to say ssh-keygen -Y sign using.that.public to get something signed.

The trezor-agent works fine otherwise like to trezor-agent -c user@datass

trezor-agent log says

```
pc trezor-agent[3604146]: 2023-01-17 16:04:50,737 ERROR        ping failed: b'S ERROR curses.isatty 83918950 \n'                                                    [trezor.py:71]
pc trezor-agent[3604146]: Traceback (most recent call last):
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/device/trezor.py", line 63, in connect
pc trezor-agent[3604146]:     self._defs.get_address(connection,
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/trezorlib/tools.py", line 267, in wrapped_f
pc trezor-agent[3604146]:     ret = f(*args, **kwargs)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/trezorlib/btc.py", line 141, in get_address
pc trezor-agent[3604146]:     return get_authenticated_address(*args, **kwargs)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/trezorlib/tools.py", line 267, in wrapped_f
pc trezor-agent[3604146]:     ret = f(*args, **kwargs)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/trezorlib/btc.py", line 163, in get_authenticated_address
pc trezor-agent[3604146]:     return client.call(
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/trezorlib/tools.py", line 290, in wrapped_f
pc trezor-agent[3604146]:     return f(client, *args, **kwargs)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/trezorlib/client.py", line 250, in call
pc trezor-agent[3604146]:     resp = self._callback_pin(resp)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/trezorlib/client.py", line 176, in _callback_pin
pc trezor-agent[3604146]:     pin = self.ui.get_pin(msg.type)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/device/ui.py", line 44, in get_pin
pc trezor-agent[3604146]:     return interact(
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/device/ui.py", line 149, in interact
pc trezor-agent[3604146]:     pin = expect(p, [b'OK', b'D '], confidential=True)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/device/ui.py", line 116, in expect
pc trezor-agent[3604146]:     raise UnexpectedError(resp)
pc trezor-agent[3604146]: libagent.device.ui.UnexpectedError: b'S ERROR curses.isatty 83918950 \n'
pc trezor-agent[3604146]: 2023-01-17 16:04:50,738 WARNING      error: b'S ERROR curses.isatty 83918950 \n'                                                          [server.py:100]
pc trezor-agent[3604146]: Traceback (most recent call last):
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/server.py", line 95, in handle_connection
pc trezor-agent[3604146]:     reply = handler.handle(msg=msg)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/ssh/protocol.py", line 106, in handle
pc trezor-agent[3604146]:     reply = method(buf=buf)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/ssh/protocol.py", line 114, in list_pubs
pc trezor-agent[3604146]:     keys = self.conn.parse_public_keys()
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/ssh/__init__.py", line 215, in parse_public_keys
pc trezor-agent[3604146]:     for pk in self.public_keys()]
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/ssh/__init__.py", line 209, in public_keys
pc trezor-agent[3604146]:     self.public_keys_cache = conn.export_public_keys(self.identities)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/ssh/client.py", line 24, in export_public_keys
pc trezor-agent[3604146]:     with self.device:
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/device/interface.py", line 126, in __enter__
pc trezor-agent[3604146]:     self.conn = self.connect()
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/device/trezor.py", line 63, in connect
pc trezor-agent[3604146]:     self._defs.get_address(connection,
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/trezorlib/tools.py", line 267, in wrapped_f
pc trezor-agent[3604146]:     ret = f(*args, **kwargs)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/trezorlib/btc.py", line 141, in get_address
pc trezor-agent[3604146]:     return get_authenticated_address(*args, **kwargs)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/trezorlib/tools.py", line 267, in wrapped_f
pc trezor-agent[3604146]:     ret = f(*args, **kwargs)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/trezorlib/btc.py", line 163, in get_authenticated_address
pc trezor-agent[3604146]:     return client.call(
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/trezorlib/tools.py", line 290, in wrapped_f
pc trezor-agent[3604146]:     return f(client, *args, **kwargs)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/trezorlib/client.py", line 250, in call
pc trezor-agent[3604146]:     resp = self._callback_pin(resp)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/trezorlib/client.py", line 176, in _callback_pin
pc trezor-agent[3604146]:     pin = self.ui.get_pin(msg.type)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/device/ui.py", line 44, in get_pin
pc trezor-agent[3604146]:     return interact(
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/device/ui.py", line 149, in interact
pc trezor-agent[3604146]:     pin = expect(p, [b'OK', b'D '], confidential=True)
pc trezor-agent[3604146]:   File "/home/user/.local/lib/python3.10/site-packages/libagent-0.14.6-py3.10.egg/libagent/device/ui.py", line 116, in expect
pc trezor-agent[3604146]:     raise UnexpectedError(resp)
pc trezor-agent[3604146]: libagent.device.ui.UnexpectedError: b'S ERROR curses.isatty 83918950 \n'
```

**Comment by romanz** [comment]
Could you please try the commands at https://github.com/romanz/trezor-agent/pull/370#issuecomment-968218901?

**Comment by iskradelta** [comment]
Ah, thanks that works well. 

The initial problem I had was gone after I rebooted, but had found many similar issues on pinentry forums/bugtrackers. It had something to do with env vars and tty settings. In any case, pinentry bug not trezor-agent.
