### ISSUE TITLE
packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)  python-pyscard>=1.6.12-4build1

### ISSUE THREAD

**Issue by antonionardella** [romanz/trezor-agent#418]
Environment

Python 3.10.9
Setuptools 67.2.0
Packaging 23.0

Issue, when I run `ledger-agent` the following error pops-up:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2711, in _dep_map
    return self.__dep_map
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2826, in __getattr__
    raise AttributeError(attr)
AttributeError: _Distribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 126, in _parse_requirement_details
    marker = _parse_requirement_marker(
  File "/usr/lib/python3.10/site-packages/packaging/_parser.py", line 147, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
  File "/usr/lib/python3.10/site-packages/packaging/_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after version specifier)
    python-pyscard>=1.6.12-4build1
                  ~~~~~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/antonio/.local/bin/ledger-agent", line 8, in <module>
    sys.exit(ssh_agent())
  File "/home/antonio/.local/bin/ledger_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/home/antonio/.local/lib/python3.10/site-packages/libagent/ssh/__init__.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/home/antonio/.local/lib/python3.10/site-packages/libagent/ssh/__init__.py", line 256, in main
    args = create_agent_parser(device_type=device_type).parse_args()
  File "/home/antonio/.local/lib/python3.10/site-packages/libagent/ssh/__init__.py", line 75, in create_agent_parser
    resources_map = {r.key: r for r in pkg_resources.require(agent_package)}
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 956, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 820, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2746, in requires
    dm = self._dep_map
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2713, in _dep_map
    self.__dep_map = self._filter_extras(self._build_dep_map())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2741, in _build_dep_map
    dm.setdefault(extra, []).extend(parse_requirements(reqs))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3095, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/lib/python3.10/site-packages/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
    python-pyscard>=1.6.12-4build1
                  ~~~~~~~~~~^
```

I found these issues https://github.com/pypa/setuptools/issues/3801 with this information:

> The requirement `python-pyscard>=1.6.12-4build1` has an invalid version (ref: [PEP 440](https://peps.python.org/pep-0440/), [PEP 508](https://peps.python.org/pep-0508/#versions)).

And this related issue:
https://github.com/pypa/setuptools/issues/3772#issuecomment-1384342813

Still, I do not know how to fix it.

Would anyone know what is to be done to get the ledger-agent to work again?

Thanks

**Comment by antonionardella** [comment]
Alright, I got it working by setting up a venv and installing setuptools==64 in the venv

After that I was able to connect using `ledger-agent -c user@IP`, but not using an alias
