### ISSUE TITLE
Cannot initialize ledger-gpg on ledger nano S

### ISSUE THREAD

**Issue by teddykisses** [romanz/trezor-agent#419]
Hello, 

I am on linux (ubuntu 22.04). I have a problem initializing ledger-gpg. The main trezor agent and ledger agent installations seemed to be successful. I am trying to install the ledger-gpg support without installing ledger ssh support. Would that cause any problem? Please see below for the output.

Thank you so much!

Best wishes,
Teddy

====
Command Line Output
```
$pip3 install --user -e trezor-agent           
                   
Obtaining file:///home/myusername/Downloads/trezor-agent
  Preparing metadata (setup.py) ... done
Requirement already satisfied: ConfigArgParse>=0.12.1 in /home/myusername/.local/lib/python3.10/site-packages (from libagent==0.14.7) (1.5.3)
Requirement already satisfied: backports.shutil_which>=3.5.1 in /home/myusername/.local/lib/python3.10/site-packages (from libagent==0.14.7) (3.5.2)
Requirement already satisfied: bech32>=1.2.0 in /home/myusername/.local/lib/python3.10/site-packages (from libagent==0.14.7) (1.2.0)
Requirement already satisfied: cryptography>=3.4.6 in /home/myusername/.local/lib/python3.10/site-packages (from libagent==0.14.7) (38.0.4)
Requirement already satisfied: docutils>=0.14 in /home/myusername/.local/lib/python3.10/site-packages (from libagent==0.14.7) (0.19)
Requirement already satisfied: ecdsa>=0.13 in /home/myusername/.local/lib/python3.10/site-packages (from libagent==0.14.7) (0.18.0)
Requirement already satisfied: mnemonic>=0.18 in /home/myusername/.local/lib/python3.10/site-packages (from libagent==0.14.7) (0.20)
Requirement already satisfied: pymsgbox>=1.0.6 in /home/myusername/.local/lib/python3.10/site-packages (from libagent==0.14.7) (1.0.9)
Requirement already satisfied: pynacl>=1.4.0 in /home/myusername/.local/lib/python3.10/site-packages (from libagent==0.14.7) (1.5.0)
Requirement already satisfied: python-daemon>=2.1.2 in /home/myusername/.local/lib/python3.10/site-packages (from libagent==0.14.7) (2.3.2)
Requirement already satisfied: semver>=2.2 in /home/myusername/.local/lib/python3.10/site-packages (from libagent==0.14.7) (2.13.0)
Requirement already satisfied: unidecode>=0.4.20 in /home/myusername/.local/lib/python3.10/site-packages (from libagent==0.14.7) (1.3.6)
Requirement already satisfied: wheel>=0.32.3 in /usr/lib/python3/dist-packages (from libagent==0.14.7) (0.37.1)
Requirement already satisfied: cffi>=1.12 in /home/myusername/.local/lib/python3.10/site-packages (from cryptography>=3.4.6->libagent==0.14.7) (1.15.1)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from ecdsa>=0.13->libagent==0.14.7) (1.16.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from python-daemon>=2.1.2->libagent==0.14.7) (59.6.0)
Requirement already satisfied: lockfile>=0.10 in /home/myusername/.local/lib/python3.10/site-packages (from python-daemon>=2.1.2->libagent==0.14.7) (0.12.2)
Requirement already satisfied: pycparser in /home/myusername/.local/lib/python3.10/site-packages (from cffi>=1.12->cryptography>=3.4.6->libagent==0.14.7) (2.21)
Installing collected packages: libagent
  Attempting uninstall: libagent
    Found existing installation: libagent 0.14.7
    Uninstalling libagent-0.14.7:
      Successfully uninstalled libagent-0.14.7
  Running setup.py develop for libagent
Successfully installed libagent




$pip3 install --user -e trezor-agent/agents/ledger 

Obtaining file:///home/myusername/Downloads/trezor-agent/agents/ledger
  Preparing metadata (setup.py) ... done
Requirement already satisfied: ledgerblue>=0.1.8 in /home/myusername/.local/lib/python3.10/site-packages (from ledger-agent==0.9.0) (0.1.45)
Requirement already satisfied: libagent>=0.9.0 in ./trezor-agent (from ledger-agent==0.9.0) (0.14.7)
Requirement already satisfied: pillow>=3.4.0 in /usr/lib/python3/dist-packages (from ledgerblue>=0.1.8->ledger-agent==0.9.0) (9.0.1)
Requirement already satisfied: hidapi>=0.7.99 in /home/myusername/.local/lib/python3.10/site-packages (from ledgerblue>=0.1.8->ledger-agent==0.9.0) (0.13.1)
Requirement already satisfied: python-u2flib-host>=3.0.2 in /home/myusername/.local/lib/python3.10/site-packages (from ledgerblue>=0.1.8->ledger-agent==0.9.0) (3.0.3)
Requirement already satisfied: protobuf>=2.6.1 in /home/myusername/.local/lib/python3.10/site-packages (from ledgerblue>=0.1.8->ledger-agent==0.9.0) (4.22.0)
Requirement already satisfied: ecpy>=0.9.0 in /home/myusername/.local/lib/python3.10/site-packages (from ledgerblue>=0.1.8->ledger-agent==0.9.0) (1.2.5)
Requirement already satisfied: future in /home/myusername/.local/lib/python3.10/site-packages (from ledgerblue>=0.1.8->ledger-agent==0.9.0) (0.18.3)
Requirement already satisfied: nfcpy>=1.0.4 in /home/myusername/.local/lib/python3.10/site-packages (from ledgerblue>=0.1.8->ledger-agent==0.9.0) (1.0.4)
Requirement already satisfied: pycryptodomex>=3.6.1 in /home/myusername/.local/lib/python3.10/site-packages (from ledgerblue>=0.1.8->ledger-agent==0.9.0) (3.17)
Requirement already satisfied: websocket-client>=0.56.0 in /home/myusername/.local/lib/python3.10/site-packages (from ledgerblue>=0.1.8->ledger-agent==0.9.0) (1.5.1)
Requirement already satisfied: ConfigArgParse>=0.12.1 in /home/myusername/.local/lib/python3.10/site-packages (from libagent>=0.9.0->ledger-agent==0.9.0) (1.5.3)
Requirement already satisfied: backports.shutil_which>=3.5.1 in /home/myusername/.local/lib/python3.10/site-packages (from libagent>=0.9.0->ledger-agent==0.9.0) (3.5.2)
Requirement already satisfied: bech32>=1.2.0 in /home/myusername/.local/lib/python3.10/site-packages (from libagent>=0.9.0->ledger-agent==0.9.0) (1.2.0)
Requirement already satisfied: cryptography>=3.4.6 in /home/myusername/.local/lib/python3.10/site-packages (from libagent>=0.9.0->ledger-agent==0.9.0) (38.0.4)
Requirement already satisfied: docutils>=0.14 in /home/myusername/.local/lib/python3.10/site-packages (from libagent>=0.9.0->ledger-agent==0.9.0) (0.19)
Requirement already satisfied: ecdsa>=0.13 in /home/myusername/.local/lib/python3.10/site-packages (from libagent>=0.9.0->ledger-agent==0.9.0) (0.18.0)
Requirement already satisfied: mnemonic>=0.18 in /home/myusername/.local/lib/python3.10/site-packages (from libagent>=0.9.0->ledger-agent==0.9.0) (0.20)
Requirement already satisfied: pymsgbox>=1.0.6 in /home/myusername/.local/lib/python3.10/site-packages (from libagent>=0.9.0->ledger-agent==0.9.0) (1.0.9)
Requirement already satisfied: pynacl>=1.4.0 in /home/myusername/.local/lib/python3.10/site-packages (from libagent>=0.9.0->ledger-agent==0.9.0) (1.5.0)
Requirement already satisfied: python-daemon>=2.1.2 in /home/myusername/.local/lib/python3.10/site-packages (from libagent>=0.9.0->ledger-agent==0.9.0) (2.3.2)
Requirement already satisfied: semver>=2.2 in /home/myusername/.local/lib/python3.10/site-packages (from libagent>=0.9.0->ledger-agent==0.9.0) (2.13.0)
Requirement already satisfied: unidecode>=0.4.20 in /home/myusername/.local/lib/python3.10/site-packages (from libagent>=0.9.0->ledger-agent==0.9.0) (1.3.6)
Requirement already satisfied: wheel>=0.32.3 in /usr/lib/python3/dist-packages (from libagent>=0.9.0->ledger-agent==0.9.0) (0.37.1)
Requirement already satisfied: cffi>=1.12 in /home/myusername/.local/lib/python3.10/site-packages (from cryptography>=3.4.6->libagent>=0.9.0->ledger-agent==0.9.0) (1.15.1)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from ecdsa>=0.13->libagent>=0.9.0->ledger-agent==0.9.0) (1.16.0)
Requirement already satisfied: setuptools>=19.0 in /usr/lib/python3/dist-packages (from hidapi>=0.7.99->ledgerblue>=0.1.8->ledger-agent==0.9.0) (59.6.0)
Requirement already satisfied: libusb1 in /home/myusername/.local/lib/python3.10/site-packages (from nfcpy>=1.0.4->ledgerblue>=0.1.8->ledger-agent==0.9.0) (3.0.0)
Requirement already satisfied: ndeflib in /home/myusername/.local/lib/python3.10/site-packages (from nfcpy>=1.0.4->ledgerblue>=0.1.8->ledger-agent==0.9.0) (0.3.3)
Requirement already satisfied: pyserial in /home/myusername/.local/lib/python3.10/site-packages (from nfcpy>=1.0.4->ledgerblue>=0.1.8->ledger-agent==0.9.0) (3.5)
Requirement already satisfied: pydes in /home/myusername/.local/lib/python3.10/site-packages (from nfcpy>=1.0.4->ledgerblue>=0.1.8->ledger-agent==0.9.0) (2.0.1)
Requirement already satisfied: lockfile>=0.10 in /home/myusername/.local/lib/python3.10/site-packages (from python-daemon>=2.1.2->libagent>=0.9.0->ledger-agent==0.9.0) (0.12.2)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from python-u2flib-host>=3.0.2->ledgerblue>=0.1.8->ledger-agent==0.9.0) (2.25.1)
Requirement already satisfied: pycparser in /home/myusername/.local/lib/python3.10/site-packages (from cffi>=1.12->cryptography>=3.4.6->libagent>=0.9.0->ledger-agent==0.9.0) (2.21)
Installing collected packages: ledger-agent
  Attempting uninstall: ledger-agent
    Found existing installation: ledger-agent 0.9.0
    Uninstalling ledger-agent-0.9.0:
      Successfully uninstalled ledger-agent-0.9.0
  Running setup.py develop for ledger-agent
Successfully installed ledger-agent








$ledger-gpg init "User Name <username@abc.com>" -v

2023-02-24 09:35:40,678 WARNING      This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility! [__init__.py:118]
2023-02-24 09:35:40,693 INFO         device name: ledger                                                                                  [__init__.py:126]
2023-02-24 09:35:40,693 INFO         GPG home directory: /home/myusername/.gnupg/ledger                                                   [__init__.py:131]
2023-02-24 09:35:40,711 WARNING      NOTE: in order to re-generate the exact same GPG key later, run this command with "--time=0" commandline flag (to set the timestamp of the GPG key manually). [__init__.py:33]
Traceback (most recent call last):
  File "/home/myusername/.local/bin/ledger-gpg", line 33, in <module>
    sys.exit(load_entry_point('ledger-agent', 'console_scripts', 'ledger-gpg')())
  File "/home/myusername/Downloads/trezor-agent/agents/ledger/ledger_agent.py", line 6, in <lambda>
    gpg_tool = lambda: libagent.gpg.main(DeviceType)
  File "/home/myusername/Downloads/trezor-agent/libagent/gpg/__init__.py", line 331, in main
    return args.func(device_type=device_type, args=args)
  File "/home/myusername/Downloads/trezor-agent/libagent/gpg/__init__.py", line 182, in run_init
    export_public_key(device_type, args))
  File "/home/myusername/Downloads/trezor-agent/libagent/gpg/__init__.py", line 39, in export_public_key
    verifying_key = c.pubkey(identity=identity, ecdh=False)
  File "/home/myusername/Downloads/trezor-agent/libagent/gpg/client.py", line 27, in pubkey
    with self.device:
  File "/home/myusername/Downloads/trezor-agent/libagent/device/interface.py", line 126, in __enter__
    self.conn = self.connect()
  File "/home/myusername/Downloads/trezor-agent/libagent/device/ledger.py", line 66, in connect
    dongle = comm.getDongle(debug=True)
  File "/home/myusername/.local/lib/python3.10/site-packages/ledgerblue/comm.py", line 308, in getDongle
    dev.open_path(hidDevicePath)
  File "hid.pyx", line 154, in hid.device.open_path
OSError: open failed
```

**Comment by romanz** [comment]
Seems that there is a connection issue to the device.
Is it possible to connect to it using another program, e.g. [Ledger Live](https://www.ledger.com/ledger-live)?

**Comment by romanz** [comment]
BTW, did you add the following udev rules?
https://github.com/LedgerHQ/blue-loader-python#giving-permissions-on-udev

**Comment by romanz** [comment]
@teddykisses ping :)
