### ISSUE TITLE
Strange error message about keepkey

### ISSUE THREAD

**Issue by infertux** [romanz/trezor-agent#46]
I'm getting this weird error message whenever I run `trezor-agent`:

```
$ trezor-agent [...]
ERROR        Missing module: install via "pip install keepkey"                                                    [factory.py:77]
Traceback (most recent call last):
  File "[...]/trezor/lib/python3.5/site-packages/trezor_agent/factory.py", line 65, in _load_keepkey
    from keepkeylib.client import KeepKeyClient, CallException
ImportError: No module named 'keepkeylib'
[...]
```

Everything seems to work properly though. I guess it's working because it can still load `trezorlib` [there](https://github.com/romanz/trezor-agent/blob/master/trezor_agent/factory.py#L230)?

If `keepkeylib` isn't strictly required, should this message be a friendly warning or maybe only displayed with `--debug`?

---

I'm using these versions:

```
$ pip list | grep trezor
trezor (0.7.4)
trezor-agent (0.7.0)
```

**Comment by infertux** [comment]
Ha, it looks like this was fixed in cf27b345f60fd03b00acf55a765674923efbf025. Any plan to cut a new release soon? :)

**Comment by romanz** [comment]
Thanks for reporting this issue :)
I'll prepare a new release tomorrow.

**Comment by romanz** [comment]
PyPI is updated with [v0.7.1](https://pypi.python.org/pypi/trezor_agent/0.7.1)

**Comment by infertux** [comment]
Thanks a lot @romanz. Much appreciated.

However I'm still getting those scary "error" messages which should just be simple warnings without any traceback IMO:

```
$ trezor-agent -c root@192.168.1.100
2016-10-12 16:31:43,886 ERROR        Missing module: install via "pip install keepkey"                                                    [factory.py:80]
Traceback (most recent call last):
  File "[...]/trezor/lib/python3.5/site-packages/trezor_agent/factory.py", line 68, in _load_keepkey
    from keepkeylib.client import KeepKeyClient, CallException
ImportError: No module named 'keepkeylib'
2016-10-12 16:31:43,887 ERROR        Missing module: install via "pip install ledgerblue"                                                 [factory.py:217]
Traceback (most recent call last):
  File "[...]/trezor/lib/python3.5/site-packages/trezor_agent/factory.py", line 215, in _load_ledger
    from ledgerblue.comm import getDongle
ImportError: No module named 'ledgerblue'
[...]
```

My Python is a bit rusty but I could come up with a PR for that if you think it's a good idea? Maybe something like:

```
2016-10-12 16:31:43,886 WARNING        Missing module keepkey: install via "pip install keepkey" if you need to support this device.
2016-10-12 16:31:43,887 WARNING        Missing module ledgerblue: install via "pip install ledgerblue" if you need to support this device.
```

**Comment by romanz** [comment]
Thanks for reporting this and sorry for the issue.
Hopefully, it should work now:

```
$ trezor-agent localhost -e ed25519
2016-10-12 21:15:09,233 WARNING      No module named 'keepkeylib': install via "pip install keepkey" if you need to support this device   [factory.py:82]
2016-10-12 21:15:09,234 WARNING      No module named 'ledgerblue': install via "pip install ledgerblue" if you need to support this device [factory.py:220]
```

**Comment by romanz** [comment]
If this works for you, I'll prepare a new release :)

**Comment by infertux** [comment]
Thanks again @romanz. I just tried 26435130d7677aa35fb66e144233a74b9fa4ba49 and I can confirm it works great. No need to make a new release just for this though - this isn't urgent/critical ;)
