### ISSUE TITLE
GPG subkey fails on OSX 10.10.5 homebrew python 2.7

### ISSUE THREAD

**Issue by dmytroleonenko** [romanz/trezor-agent#49]
```
$ gpg2 --edit "${TREZOR_GPG_USER_ID}" trust
gpg (GnuPG/MacGPG2) 2.0.30; Copyright (C) 2015 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


gpg: checking the trustdb
gpg: public key of ultimately trusted key 21E44D27 not found
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   4  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 4u
gpg: next trustdb check due at 2018-08-19
pub     0E/FEB0D0AF  created: 2016-10-14  expires: never       usage: SCA
                     trust: ultimate      validity: ultimate
[ultimate] (1). Dmytro Leonenko TREZOR <dmitry.leonenko@gmail.com>

pub     0E/FEB0D0AF  created: 2016-10-14  expires: never       usage: SCA
                     trust: ultimate      validity: ultimate
[ultimate] (1). Dmytro Leonenko TREZOR <dmitry.leonenko@gmail.com>
```

```
$ gpg --version
gpg (GnuPG/MacGPG2) 2.0.30
libgcrypt 1.7.0
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA, RSA, ELG, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

latest trezor (git) and trezor_agent(git)
trezor firmware 1.4.0

**The issue:**
```
$ trezor-gpg create --subkey
2016-10-14 11:56:09,745 WARNING    This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility!
2016-10-14 11:56:09,745 WARNING    NOTE: in order to re-generate the exact same GPG key later, run this command with "--time=1476435369" commandline flag (to set the timestamp of the GPG key manually).
2016-10-14 11:56:09,927 WARNING    No module named keepkeylib.client: install via "pip install keepkey" if you need to support this device
Traceback (most recent call last):
  File "/usr/local/bin/trezor-gpg", line 11, in <module>
    sys.exit(main())
  File "/Users/admin/Library/Python/2.7/lib/python/site-packages/trezor_agent/gpg/__main__.py", line 95, in main
    args.run(args)
  File "/Users/admin/Library/Python/2.7/lib/python/site-packages/trezor_agent/gpg/__main__.py", line 39, in run_create
    signer_func=conn.sign)
  File "/Users/admin/Library/Python/2.7/lib/python/site-packages/trezor_agent/gpg/encode.py", line 124, in create_subkey
    primary = decode.load_public_key(primary_bytes)
  File "/Users/admin/Library/Python/2.7/lib/python/site-packages/trezor_agent/gpg/decode.py", line 320, in load_public_key
    pubkey, userid, signature = packets[:3]
ValueError: need more than 2 values to unpack
```

**Comment by romanz** [comment]
First of all, thanks for trying out `trezor-agent` GPG feature and for reporting this issue :)

It seems that you are using 2.0.30 version of GPG - which may be problem, since ECDSA (and Curve25519) was added to GPG only at 2.1.x branch (https://www.gnupg.org/faq/whats-new-in-2.1.html#ecc).

Also, could you please run `$ gpg2 --export "${TREZOR_GPG_USER_ID}" | gpg2 --list-packets` command and paste the resulting public keys' structure here? This would help me understand and reproduce the problem :)

**Comment by romanz** [comment]
Could you please also re-run the command, but with more verbose logging, using:

```
$ trezor-gpg -v create --subkey
```

Thanks in advance :)

**Comment by romanz** [comment]
@dmytroleonenko ping :)

**Comment by romanz** [comment]
No reply from OP :(

**Comment by andrevmatos** [comment]
Can you, please, add docs instructions on how to create a subkey?

**Comment by romanz** [comment]
Will do :)
