### ISSUE TITLE
AssertionError - Keygrip mismatch at `trezor-gpg agent` during sign operation

### ISSUE THREAD

**Issue by fruitloop** [romanz/trezor-agent#52]
Hi, 
My Setup is: OS X 10.11.5, trezor (0.7.4), trezor-agent (0.7.2), Trezor Firmware 1.4.0

When I use trezor-gpg -v agent, I sometimes get this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/trezor-gpg", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/gpg/__main__.py", line 95, in main
    args.run(args)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/gpg/__main__.py", line 69, in run_agent
    agent.handle_connection(conn)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/gpg/agent.py", line 121, in handle_connection
    sig = pksign(keygrip, digest, algo)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/gpg/agent.py", line 49, in pksign
    assert pubkey.keygrip == binascii.unhexlify(keygrip)
AssertionError
```
Sometimes everything works fine for two or three times, and then I get this error for the rest of the day.

Is there something wrong with my Python installation?

Best Regards
Roland

**Comment by romanz** [comment]
Thanks for reporting this issue!

Could you please run `$ gpg2 --export "${TREZOR_GPG_USER_ID}" | gpg2 --list-packets` command and paste the resulting public keys' structure here? This would help me understand and reproduce the problem :)

**Comment by romanz** [comment]
Also, could you please re-run the `gpg2 --sign` command with the latest version (https://github.com/romanz/trezor-agent/commit/79b6d31dfe8bba5c3f27c5f3a011e5a658d87400) of `trezor-agent`?
It should now include the mismatching keygrips in the exception itself...

**Comment by fruitloop** [comment]
Hi, thanks for the fast response

```
[roland@Turtle:~] % gpg2 -k --with-keygrip github
pub   nistp256 2016-10-16 [SC]
      7E9266BFAA9BE177D92DDAFB51F3833053F2E698
      Keygrip = DAB26946E82099931400D154BB197035B5324F5C
uid           [ultimate] Roland Planitz <github@planitz.at>
sub   nistp256 2016-10-16 [E]
      Keygrip = C3A0AB22ECBD28F010F44DB387892A2C4A586AD6
```

```
[roland@Turtle:~] % gpg2 --export github | gpg2 --list-packets 
# off=0 ctb=98 tag=6 hlen=2 plen=82
:public key packet:
	version 4, algo 19, created 1476651084, expires 0
	pkey[0]: [72 bits] nistp256 (1.2.840.10045.3.1.7)
	pkey[1]: [515 bits]
	keyid: 51F3833053F2E698
# off=84 ctb=b4 tag=13 hlen=2 plen=34
:user ID packet: "Roland Planitz <github@planitz.at>"
# off=120 ctb=88 tag=2 hlen=2 plen=121
:signature packet: algo 19, keyid 51F3833053F2E698
	version 4, created 1476651084, md5len 0, sigclass 0x13
	digest algo 8, begin of digest 6c 53
	hashed subpkt 2 len 4 (sig created 2016-10-16)
	hashed subpkt 11 len 1 (pref-sym-algos: 9)
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 21 len 1 (pref-hash-algos: 8)
	hashed subpkt 22 len 1 (pref-zip-algos: 0)
	hashed subpkt 23 len 1 (keyserver preferences: 80)
	subpkt 16 len 8 (issuer key ID 51F3833053F2E698)
	subpkt 100 len 10 (experimental / private subpacket)
	data: [256 bits]
	data: [255 bits]
# off=243 ctb=b8 tag=14 hlen=2 plen=86
:public sub key packet:
	version 4, algo 18, created 1476651084, expires 0
	pkey[0]: [72 bits] nistp256 (1.2.840.10045.3.1.7)
	pkey[1]: [515 bits]
	pkey[2]: [32 bits]
	keyid: 6DACEBD50DF117C4
# off=331 ctb=88 tag=2 hlen=2 plen=109
:signature packet: algo 19, keyid 51F3833053F2E698
	version 4, created 1476651084, md5len 0, sigclass 0x18
	digest algo 8, begin of digest 7f ac
	hashed subpkt 2 len 4 (sig created 2016-10-16)
	hashed subpkt 27 len 1 (key flags: 0C)
	subpkt 16 len 8 (issuer key ID 51F3833053F2E698)
	subpkt 100 len 10 (experimental / private subpacket)
	data: [255 bits]
	data: [255 bits]
```

I updated trezor-agent and ran it again
```
2016-10-17 10:49:02,149 WARNING    This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility!
2016-10-17 10:49:02,169 DEBUG      serving on SSH_AUTH_SOCK=/Users/roland/.gnupg/S.gpg-agent
2016-10-17 10:49:02,169 DEBUG      waiting for connection on /Users/roland/.gnupg/S.gpg-agent
2016-10-17 10:49:05,783 DEBUG      accepted connection on /Users/roland/.gnupg/S.gpg-agent
2016-10-17 10:49:05,802 DEBUG      <- 'OK'
2016-10-17 10:49:05,803 DEBUG      -> 'RESET'
2016-10-17 10:49:05,803 DEBUG      <- 'OK'
2016-10-17 10:49:05,803 DEBUG      -> 'OPTION ttytype=xterm'
2016-10-17 10:49:05,803 DEBUG      <- 'OK'
2016-10-17 10:49:05,811 DEBUG      -> 'GETINFO version'
2016-10-17 10:49:05,811 DEBUG      <- 'D 2.1.15'
2016-10-17 10:49:05,811 DEBUG      <- 'OK'
2016-10-17 10:49:05,812 DEBUG      -> 'OPTION allow-pinentry-notify'
2016-10-17 10:49:05,812 DEBUG      <- 'OK'
2016-10-17 10:49:05,812 DEBUG      -> 'OPTION agent-awareness=2.1.0'
2016-10-17 10:49:05,813 DEBUG      <- 'OK'
2016-10-17 10:49:05,813 DEBUG      -> 'AGENT_ID'
2016-10-17 10:49:05,813 DEBUG      <- 'D TREZOR'
2016-10-17 10:49:05,813 DEBUG      <- 'OK'
2016-10-17 10:49:05,816 DEBUG      -> 'HAVEKEY E8AAD7A22972124DB68075FD64F070D221C2FD67 D7A218E5A497B42CEF3BC9C0F33BE9C1BA4AC619'
2016-10-17 10:49:05,816 DEBUG      <- 'OK'
2016-10-17 10:49:05,819 DEBUG      -> 'RESET'
2016-10-17 10:49:05,820 DEBUG      <- 'OK'
2016-10-17 10:49:05,820 DEBUG      -> 'SIGKEY E8AAD7A22972124DB68075FD64F070D221C2FD67'
2016-10-17 10:49:05,820 DEBUG      <- 'OK'
2016-10-17 10:49:05,821 DEBUG      -> 'SETKEYDESC Please+enter+the+passphrase+to+unlock+the+OpenPGP+secret+key:%0A%22Roland+Planitz+<roland@planitz.at>%22%0A256-bit+ECDSA+key,+ID+44F2BB535E654B16,%0Acreated+2016-10-16.%0A'
2016-10-17 10:49:05,821 DEBUG      <- 'OK'
2016-10-17 10:49:05,822 DEBUG      -> 'SETHASH 8 CC863C7F00CF0CC7CC327F0EA39732FC532DF137250DBE750F8D0AC2E8C4E2EE'
2016-10-17 10:49:05,822 DEBUG      <- 'OK'
2016-10-17 10:49:05,822 DEBUG      -> 'PKSIGN'
2016-10-17 10:49:05,836 DEBUG      prefix byte: 0b10011000
2016-10-17 10:49:05,837 DEBUG      packet length: 82
2016-10-17 10:49:05,837 DEBUG      parsing elliptic curve key
2016-10-17 10:49:05,838 DEBUG      mpi: 4449154ddcc2460afd028cfb0224aff70342becb57f21698b042c423d0ffe8a1d74036d5ad0ad6a6d936ae2229063f440c79953a44f6eb420c76708f2839dcacd (515 bits)
2016-10-17 10:49:05,917 DEBUG      key ID: 51F3833053F2E698
2016-10-17 10:49:05,917 DEBUG      packet "pubkey": {'created': 1476651084, 'verifying_key': <ecdsa.keys.VerifyingKey instance at 0x10988ccf8>, 'tag': 6, 'curve_oid': '*\x86H\xce=\x03\x01\x07', 'verifier': <function _nist256p1_verify at 0x1098a00c8>, 'version': 4, 'algo': 19, 'key_id': 'Q\xf3\x830S\xf2\xe6\x98', 'type': 'pubkey', '_to_hash': '\x99\x00R\x04X\x03\xe8L\x13\x08*\x86H\xce=\x03\x01\x07\x02\x03\x04D\x91T\xdd\xcc$`\xaf\xd0(\xcf\xb0"J\xffp4+\xec\xb5\x7f!i\x8b\x04,B=\x0f\xfe\x8a\x1dt\x03mZ\xd0\xadjm\x93j\xe2"\x90c\xf4@\xc7\x99S\xa4On\xb4 \xc7g\x08\xf2\x83\x9d\xca\xcd'}
2016-10-17 10:49:05,918 DEBUG      prefix byte: 0b10110100
2016-10-17 10:49:05,918 DEBUG      packet length: 34
2016-10-17 10:49:05,918 DEBUG      packet "user_id": {'tag': 13, 'type': 'user_id', 'value': 'Roland Planitz <github@planitz.at>', '_to_hash': '\xb4\x00\x00\x00"Roland Planitz <github@planitz.at>'}
2016-10-17 10:49:05,918 DEBUG      prefix byte: 0b10001000
2016-10-17 10:49:05,919 DEBUG      packet length: 121
2016-10-17 10:49:05,919 DEBUG      packet "signature": {'hash_prefix': 'lS', 'hashed_subpackets': ['\x02X\x03\xe8L', '\x0b\t', '\x1b\x03', '\x15\x08', '\x16\x00', '\x17\x80'], 'pubkey_alg': 19, '_is_custom': True, 'hash_alg': 8, 'tag': 2, 'sig_type': 19, 'version': 4, 'sig': (102528692007018662478410427344616484795132055260561832797479366964600507666647L, 57719256278049600832974411777041248160917410385421014829423897735370847269749L), 'unhashed_subpackets': ['\x10Q\xf3\x830S\xf2\xe6\x98', 'dTREZOR-GPG'], 'type': 'signature', '_to_hash': '\x04\x13\x13\x08\x00\x15\x05\x02X\x03\xe8L\x02\x0b\t\x02\x1b\x03\x02\x15\x08\x02\x16\x00\x02\x17\x80\x04\xff\x00\x00\x00\x1b'}
2016-10-17 10:49:05,919 DEBUG      prefix byte: 0b10111000
2016-10-17 10:49:05,919 DEBUG      packet length: 86
2016-10-17 10:49:05,920 DEBUG      parsing elliptic curve key
2016-10-17 10:49:05,920 DEBUG      mpi: 408933d7028f6ad2e099f00f84c52aabfee1d5ccd6fbd051d44f057a1d6263d4188ca607f310410116a21afbd83d2e73b4f97e40d178d0904097777c846997825 (515 bits)
2016-10-17 10:49:05,987 DEBUG      key ID: 6DACEBD50DF117C4
2016-10-17 10:49:05,987 DEBUG      packet "subkey": {'created': 1476651084, 'verifying_key': <ecdsa.keys.VerifyingKey instance at 0x10988cd40>, 'kdf': '\x01\x08\x07', 'tag': 14, 'curve_oid': '*\x86H\xce=\x03\x01\x07', 'verifier': <function _nist256p1_verify at 0x108e8eb18>, 'version': 4, 'algo': 18, 'key_id': 'm\xac\xeb\xd5\r\xf1\x17\xc4', 'type': 'subkey', '_to_hash': '\x99\x00V\x04X\x03\xe8L\x12\x08*\x86H\xce=\x03\x01\x07\x02\x03\x04\x08\x93=p(\xf6\xad.\t\x9f\x00\xf8LR\xaa\xbf\xee\x1d\\\xcdo\xbd\x05\x1dD\xf0W\xa1\xd6&=A\x88\xca`\x7f1\x04\x10\x11j!\xaf\xbd\x83\xd2\xe7;O\x97\xe4\r\x17\x8d\t\x04\tww\xc8F\x99x%\x03\x01\x08\x07'}
2016-10-17 10:49:05,987 DEBUG      prefix byte: 0b10001000
2016-10-17 10:49:05,987 DEBUG      packet length: 109
2016-10-17 10:49:05,988 DEBUG      packet "signature": {'hash_prefix': '\x7f\xac', 'hashed_subpackets': ['\x02X\x03\xe8L', '\x1b\x0c'], 'pubkey_alg': 19, '_is_custom': True, 'hash_alg': 8, 'tag': 2, 'sig_type': 24, 'version': 4, 'sig': (51411217383221898020449732713403463792152212539112153765469687666398206976286L, 52574456261918540967165567050963813670579719393906417307543590784493354206261L), 'unhashed_subpackets': ['\x10Q\xf3\x830S\xf2\xe6\x98', 'dTREZOR-GPG'], 'type': 'signature', '_to_hash': '\x04\x18\x13\x08\x00\t\x05\x02X\x03\xe8L\x02\x1b\x0c\x04\xff\x00\x00\x00\x0f'}
2016-10-17 10:49:05,988 DEBUG      loaded public key "Roland Planitz <github@planitz.at>"
2016-10-17 10:49:06,129 DEBUG      nist256p1 ECDSA signature is OK (True)
2016-10-17 10:49:06,129 DEBUG      GPG public key is OK
2016-10-17 10:49:06,129 DEBUG      found custom pubkey
2016-10-17 10:49:06,130 DEBUG      pubkey_dict: {'user_id': 'Roland Planitz <github@planitz.at>', '_is_custom': True, 'created': 1476651084, 'verifying_key': <ecdsa.keys.VerifyingKey instance at 0x10988ccf8>, 'tag': 6, 'curve_oid': '*\x86H\xce=\x03\x01\x07', 'verifier': <function _nist256p1_verify at 0x1098a00c8>, 'version': 4, 'algo': 19, 'key_id': 'Q\xf3\x830S\xf2\xe6\x98', 'type': 'pubkey', '_to_hash': '\x99\x00R\x04X\x03\xe8L\x13\x08*\x86H\xce=\x03\x01\x07\x02\x03\x04D\x91T\xdd\xcc$`\xaf\xd0(\xcf\xb0"J\xffp4+\xec\xb5\x7f!i\x8b\x04,B=\x0f\xfe\x8a\x1dt\x03mZ\xd0\xadjm\x93j\xe2"\x90c\xf4@\xc7\x99S\xa4On\xb4 \xc7g\x08\xf2\x83\x9d\xca\xcd'}
2016-10-17 10:49:06,300 DEBUG      connected to Trezor 79D99D130E0C8CA632F860E3
2016-10-17 10:49:06,300 DEBUG      label    : planitz
2016-10-17 10:49:06,300 DEBUG      vendor   : bitcointrezor.com
2016-10-17 10:49:06,301 DEBUG      version  : 1.4.0
2016-10-17 10:49:06,301 DEBUG      revision : e0e190b3dc29bcb0f6ab9699c439fe7bfbcde370
2016-10-17 10:49:06,365 DEBUG      address string: '\x00\x00\x00\x00gpg://Roland Planitz <github@planitz.at>'
Use the numeric keypad to describe number positions. The layout is:
    7 8 9
    4 5 6
    1 2 3
Please enter current PIN: 

2016-10-17 10:49:16,635 INFO       GPG public key nist256p1/53F2E698 created at 2016-10-16 22:51:24 for "Roland Planitz <github@planitz.at>"
Traceback (most recent call last):
  File "/usr/local/bin/trezor-gpg", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/gpg/__main__.py", line 95, in main
    args.run(args)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/gpg/__main__.py", line 69, in run_agent
    agent.handle_connection(conn)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/gpg/agent.py", line 121, in handle_connection
    sig = pksign(keygrip, digest, algo)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/gpg/agent.py", line 49, in pksign
    assert pubkey.keygrip == binascii.unhexlify(keygrip)
AssertionError
```
I didn't see the debug code you added however.

But when I tried it a second time (restarted trezor-gpg -v agent in one terminal and reran the git --gpg-sign command in the second) the agent crashed with a whole new exception.

I opened another issue here: https://github.com/romanz/trezor-agent/issues/53

Best regards
Roland

**Comment by romanz** [comment]
Thanks for uploading the debug log, it really helps!

Note that the GPG agent got a request to sign with keygrip `E8AAD7A22972124DB68075FD64F070D221C2FD67`, which is not part of your GPG identity:
```
pub   nistp256 2016-10-16 [SC]
      7E9266BFAA9BE177D92DDAFB51F3833053F2E698
      Keygrip = DAB26946E82099931400D154BB197035B5324F5C
uid           [ultimate] Roland Planitz <github@planitz.at>
sub   nistp256 2016-10-16 [E]
      Keygrip = C3A0AB22ECBD28F010F44DB387892A2C4A586AD6
```
So the assertion seems to work as intended :)

It seems like `git` tries to use another key to sign the commit, which is not part of your TREZOR-based GPG key. Could you please run `$ gpg2 -k --with-keygrip` to see if it belongs to any of your other GPG keys?

**Comment by fruitloop** [comment]
```
[roland@Turtle:~] % gpg2 -k --with-keygrip
/Users/roland/.gnupg/pubring.kbx
--------------------------------
pub   nistp256 2016-10-16 [SC]
      7E9266BFAA9BE177D92DDAFB51F3833053F2E698
      Keygrip = DAB26946E82099931400D154BB197035B5324F5C
uid           [ultimate] Roland Planitz <github@planitz.at>
sub   nistp256 2016-10-16 [E]
      Keygrip = C3A0AB22ECBD28F010F44DB387892A2C4A586AD6

pub   nistp256 2016-10-16 [SC]
      A9FC726432034F32071549BF44F2BB535E654B16
      Keygrip = E8AAD7A22972124DB68075FD64F070D221C2FD67
uid           [ultimate] Roland Planitz <roland@planitz.at>
sub   nistp256 2016-10-16 [E]
      Keygrip = D7A218E5A497B42CEF3BC9C0F33BE9C1BA4AC619

pub   nistp256 2016-10-16 [SC]
      79301D1B58944DCF88EB052977F58D0A71D73E81
      Keygrip = EF937823F45C27F481AE249B41BA638377903147
uid           [ultimate] Roland Planitz <keysigning@planitz.at>
sub   nistp256 2016-10-16 [E]
      Keygrip = D06D5C1EF363AE4402BD9F92C6249DD097B74EBD
```

Seems not, but I did try this a few days ago with test keys I deleted already. 
I did remove the keys from my github account and add the actual key (github@planitz.at)

Hope that helps

**Comment by romanz** [comment]
I think that `git` is trying to use your 2nd GPG identity "Roland Planitz <roland@planitz.at>" instead of the 1st.
Please try running:
```
echo "Hello World!" | gpg2 --sign -u 7E9266BFAA9BE177D92DDAFB51F3833053F2E698 | gpg2 --verify
```
to see if it chooses the correct GPG key (and the verification works as intended).
If so, you can use:
```
git config --local user.signingkey 7E9266BFAA9BE177D92DDAFB51F3833053F2E698
```
to explicitly specify your TREZOR-based GPG key.

**Comment by romanz** [comment]
BTW, you can verify you Git user.name and user.email configuration using:
```
$ git config -l | grep user
```
Maybe those are misconfigured, causing Git to choose the "Roland Planitz <roland@planitz.at>" GPG identity?

**Comment by fruitloop** [comment]
```
[roland@Turtle:~/git/trezor-gpg-test] % echo "Hello World!" | gpg2 --sign -u 7E9266BFAA9BE177D92DDAFB51F3833053F2E698 | gpg2 --verify
gpg: Signature made Mon Oct 17 11:53:44 2016 CEST
gpg:                using ECDSA key 51F3833053F2E698
gpg: Good signature from "Roland Planitz <github@planitz.at>" [ultimate]
```
That works fine, no crashes.

I ran `it config --local user.signingkey 7E9266BFAA9BE177D92DDAFB51F3833053F2E698`
and now my .git/config shows this:
```
...
[gpg]
	program = gpg2
[user]
	signingkey = 7E9266BFAA9BE177D92DDAFB51F3833053F2E698
```

but still:
```
[roland@Turtle:~] % clear;export TREZOR_GPG_USER_ID="Roland Planitz <github@planitz.at>"; trezor-gpg -v agent

2016-10-17 11:55:50,874 WARNING    This GPG tool is still in EXPERIMENTAL mode, so please note that the API and features may change without backwards compatibility!
2016-10-17 11:55:50,892 DEBUG      serving on SSH_AUTH_SOCK=/Users/roland/.gnupg/S.gpg-agent
2016-10-17 11:55:50,893 DEBUG      waiting for connection on /Users/roland/.gnupg/S.gpg-agent
2016-10-17 11:55:54,104 DEBUG      accepted connection on /Users/roland/.gnupg/S.gpg-agent
2016-10-17 11:55:54,121 DEBUG      <- 'OK'
2016-10-17 11:55:54,121 DEBUG      -> 'RESET'
2016-10-17 11:55:54,121 DEBUG      <- 'OK'
2016-10-17 11:55:54,122 DEBUG      -> 'OPTION ttytype=xterm'
2016-10-17 11:55:54,122 DEBUG      <- 'OK'
2016-10-17 11:55:54,129 DEBUG      -> 'GETINFO version'
2016-10-17 11:55:54,130 DEBUG      <- 'D 2.1.15'
2016-10-17 11:55:54,130 DEBUG      <- 'OK'
2016-10-17 11:55:54,130 DEBUG      -> 'OPTION allow-pinentry-notify'
2016-10-17 11:55:54,130 DEBUG      <- 'OK'
2016-10-17 11:55:54,131 DEBUG      -> 'OPTION agent-awareness=2.1.0'
2016-10-17 11:55:54,131 DEBUG      <- 'OK'
2016-10-17 11:55:54,131 DEBUG      -> 'AGENT_ID'
2016-10-17 11:55:54,131 DEBUG      <- 'D TREZOR'
2016-10-17 11:55:54,131 DEBUG      <- 'OK'
2016-10-17 11:55:54,133 DEBUG      -> 'HAVEKEY DAB26946E82099931400D154BB197035B5324F5C C3A0AB22ECBD28F010F44DB387892A2C4A586AD6'
2016-10-17 11:55:54,133 DEBUG      <- 'OK'
2016-10-17 11:55:54,136 DEBUG      -> 'RESET'
2016-10-17 11:55:54,136 DEBUG      <- 'OK'
2016-10-17 11:55:54,136 DEBUG      -> 'SIGKEY DAB26946E82099931400D154BB197035B5324F5C'
2016-10-17 11:55:54,137 DEBUG      <- 'OK'
2016-10-17 11:55:54,137 DEBUG      -> 'SETKEYDESC Please+enter+the+passphrase+to+unlock+the+OpenPGP+secret+key:%0A%22Roland+Planitz+<github@planitz.at>%22%0A256-bit+ECDSA+key,+ID+51F3833053F2E698,%0Acreated+2016-10-16.%0A'
2016-10-17 11:55:54,137 DEBUG      <- 'OK'
2016-10-17 11:55:54,138 DEBUG      -> 'SETHASH 8 741081A2EFD3D4AB55ED58080173E2CE9531B0E927014346716CD70C738B8691'
2016-10-17 11:55:54,138 DEBUG      <- 'OK'
2016-10-17 11:55:54,140 DEBUG      -> 'PKSIGN'
2016-10-17 11:55:54,206 DEBUG      prefix byte: 0b10011000
2016-10-17 11:55:54,207 DEBUG      packet length: 82
2016-10-17 11:55:54,210 DEBUG      parsing elliptic curve key
2016-10-17 11:55:54,211 DEBUG      mpi: 4449154ddcc2460afd028cfb0224aff70342becb57f21698b042c423d0ffe8a1d74036d5ad0ad6a6d936ae2229063f440c79953a44f6eb420c76708f2839dcacd (515 bits)
2016-10-17 11:55:54,434 DEBUG      key ID: 51F3833053F2E698
2016-10-17 11:55:54,435 DEBUG      packet "pubkey": {'created': 1476651084, 'verifying_key': <ecdsa.keys.VerifyingKey instance at 0x10fb85cf8>, 'tag': 6, 'curve_oid': '*\x86H\xce=\x03\x01\x07', 'verifier': <function _nist256p1_verify at 0x10fb990c8>, 'version': 4, 'algo': 19, 'key_id': 'Q\xf3\x830S\xf2\xe6\x98', 'type': 'pubkey', '_to_hash': '\x99\x00R\x04X\x03\xe8L\x13\x08*\x86H\xce=\x03\x01\x07\x02\x03\x04D\x91T\xdd\xcc$`\xaf\xd0(\xcf\xb0"J\xffp4+\xec\xb5\x7f!i\x8b\x04,B=\x0f\xfe\x8a\x1dt\x03mZ\xd0\xadjm\x93j\xe2"\x90c\xf4@\xc7\x99S\xa4On\xb4 \xc7g\x08\xf2\x83\x9d\xca\xcd'}
2016-10-17 11:55:54,435 DEBUG      prefix byte: 0b10110100
2016-10-17 11:55:54,435 DEBUG      packet length: 34
2016-10-17 11:55:54,435 DEBUG      packet "user_id": {'tag': 13, 'type': 'user_id', 'value': 'Roland Planitz <github@planitz.at>', '_to_hash': '\xb4\x00\x00\x00"Roland Planitz <github@planitz.at>'}
2016-10-17 11:55:54,435 DEBUG      prefix byte: 0b10001000
2016-10-17 11:55:54,436 DEBUG      packet length: 121
2016-10-17 11:55:54,436 DEBUG      packet "signature": {'hash_prefix': 'lS', 'hashed_subpackets': ['\x02X\x03\xe8L', '\x0b\t', '\x1b\x03', '\x15\x08', '\x16\x00', '\x17\x80'], 'pubkey_alg': 19, '_is_custom': True, 'hash_alg': 8, 'tag': 2, 'sig_type': 19, 'version': 4, 'sig': (102528692007018662478410427344616484795132055260561832797479366964600507666647L, 57719256278049600832974411777041248160917410385421014829423897735370847269749L), 'unhashed_subpackets': ['\x10Q\xf3\x830S\xf2\xe6\x98', 'dTREZOR-GPG'], 'type': 'signature', '_to_hash': '\x04\x13\x13\x08\x00\x15\x05\x02X\x03\xe8L\x02\x0b\t\x02\x1b\x03\x02\x15\x08\x02\x16\x00\x02\x17\x80\x04\xff\x00\x00\x00\x1b'}
2016-10-17 11:55:54,436 DEBUG      prefix byte: 0b10111000
2016-10-17 11:55:54,436 DEBUG      packet length: 86
2016-10-17 11:55:54,436 DEBUG      parsing elliptic curve key
2016-10-17 11:55:54,437 DEBUG      mpi: 408933d7028f6ad2e099f00f84c52aabfee1d5ccd6fbd051d44f057a1d6263d4188ca607f310410116a21afbd83d2e73b4f97e40d178d0904097777c846997825 (515 bits)
2016-10-17 11:55:54,494 DEBUG      key ID: 6DACEBD50DF117C4
2016-10-17 11:55:54,494 DEBUG      packet "subkey": {'created': 1476651084, 'verifying_key': <ecdsa.keys.VerifyingKey instance at 0x10fb85d40>, 'kdf': '\x01\x08\x07', 'tag': 14, 'curve_oid': '*\x86H\xce=\x03\x01\x07', 'verifier': <function _nist256p1_verify at 0x10f187b18>, 'version': 4, 'algo': 18, 'key_id': 'm\xac\xeb\xd5\r\xf1\x17\xc4', 'type': 'subkey', '_to_hash': '\x99\x00V\x04X\x03\xe8L\x12\x08*\x86H\xce=\x03\x01\x07\x02\x03\x04\x08\x93=p(\xf6\xad.\t\x9f\x00\xf8LR\xaa\xbf\xee\x1d\\\xcdo\xbd\x05\x1dD\xf0W\xa1\xd6&=A\x88\xca`\x7f1\x04\x10\x11j!\xaf\xbd\x83\xd2\xe7;O\x97\xe4\r\x17\x8d\t\x04\tww\xc8F\x99x%\x03\x01\x08\x07'}
2016-10-17 11:55:54,494 DEBUG      prefix byte: 0b10001000
2016-10-17 11:55:54,494 DEBUG      packet length: 109
2016-10-17 11:55:54,495 DEBUG      packet "signature": {'hash_prefix': '\x7f\xac', 'hashed_subpackets': ['\x02X\x03\xe8L', '\x1b\x0c'], 'pubkey_alg': 19, '_is_custom': True, 'hash_alg': 8, 'tag': 2, 'sig_type': 24, 'version': 4, 'sig': (51411217383221898020449732713403463792152212539112153765469687666398206976286L, 52574456261918540967165567050963813670579719393906417307543590784493354206261L), 'unhashed_subpackets': ['\x10Q\xf3\x830S\xf2\xe6\x98', 'dTREZOR-GPG'], 'type': 'signature', '_to_hash': '\x04\x18\x13\x08\x00\t\x05\x02X\x03\xe8L\x02\x1b\x0c\x04\xff\x00\x00\x00\x0f'}
2016-10-17 11:55:54,495 DEBUG      loaded public key "Roland Planitz <github@planitz.at>"
2016-10-17 11:55:54,628 DEBUG      nist256p1 ECDSA signature is OK (True)
2016-10-17 11:55:54,628 DEBUG      GPG public key is OK
2016-10-17 11:55:54,628 DEBUG      found custom pubkey
2016-10-17 11:55:54,629 DEBUG      pubkey_dict: {'user_id': 'Roland Planitz <github@planitz.at>', '_is_custom': True, 'created': 1476651084, 'verifying_key': <ecdsa.keys.VerifyingKey instance at 0x10fb85cf8>, 'tag': 6, 'curve_oid': '*\x86H\xce=\x03\x01\x07', 'verifier': <function _nist256p1_verify at 0x10fb990c8>, 'version': 4, 'algo': 19, 'key_id': 'Q\xf3\x830S\xf2\xe6\x98', 'type': 'pubkey', '_to_hash': '\x99\x00R\x04X\x03\xe8L\x13\x08*\x86H\xce=\x03\x01\x07\x02\x03\x04D\x91T\xdd\xcc$`\xaf\xd0(\xcf\xb0"J\xffp4+\xec\xb5\x7f!i\x8b\x04,B=\x0f\xfe\x8a\x1dt\x03mZ\xd0\xadjm\x93j\xe2"\x90c\xf4@\xc7\x99S\xa4On\xb4 \xc7g\x08\xf2\x83\x9d\xca\xcd'}
Traceback (most recent call last):
  File "/usr/local/bin/trezor-gpg", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/gpg/__main__.py", line 95, in main
    args.run(args)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/gpg/__main__.py", line 69, in run_agent
    agent.handle_connection(conn)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/gpg/agent.py", line 121, in handle_connection
    sig = pksign(keygrip, digest, algo)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/gpg/agent.py", line 47, in pksign
    pubkey, conn = encode.load_from_public_key(pubkey_dict=pubkey_dict)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/gpg/encode.py", line 119, in load_from_public_key
    conn = device.HardwareSigner(user_id, curve_name=curve_name)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/gpg/device.py", line 11, in __init__
    self.client_wrapper = factory.load()
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/factory.py", line 248, in load
    device_list.extend(device)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/factory.py", line 27, in _load_client
    connection = client_type(hid_transport(d))
  File "/usr/local/lib/python2.7/site-packages/trezorlib/client.py", line 361, in __init__
    self.init_device()
  File "/usr/local/lib/python2.7/site-packages/trezorlib/client.py", line 368, in init_device
    self.features = expect(proto.Features)(self.call)(proto.Initialize())
  File "/usr/local/lib/python2.7/site-packages/trezorlib/client.py", line 85, in wrapped_f
    ret = f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/trezorlib/client.py", line 98, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/trezorlib/client.py", line 134, in call
    resp = self.call_raw(msg)
  File "/usr/local/lib/python2.7/site-packages/trezorlib/client.py", line 98, in wrapped_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/trezorlib/client.py", line 130, in call_raw
    return self.transport.read_blocking()
  File "/usr/local/lib/python2.7/site-packages/trezorlib/transport.py", line 68, in read_blocking
    data = self._read()
  File "/usr/local/lib/python2.7/site-packages/trezorlib/transport.py", line 128, in _read
    (msg_type, datalen, data) = self.parse_first(chunk)
  File "/usr/local/lib/python2.7/site-packages/trezorlib/transport.py", line 140, in parse_first
    raise Exception("Unexpected magic characters")
Exception: Unexpected magic characters
```

**Comment by romanz** [comment]
Maybe the `python-trezor` installed at `/usr/local/lib/python2.7/site-packages/` is still the old one?
Could you please check `/usr/local/lib/python2.7/site-packages/trezorlib/transport_hid.py` file for the `enumerate()` function? 
It should end with `return sorted(devices.values())` in the latest version (https://github.com/trezor/python-trezor/pull/77)?

**Comment by romanz** [comment]
The "Unexpected magic characters" error happened due to wrong interface being chosen - U2F instead of HID (since the previous code used `return list(devices.values())`, whose order of elements is unpredictable for Python dictionaries).

**Comment by fruitloop** [comment]
It did in fact end in `return list(devices.values())`
so I ran `pip uninstall trezor`
then I installed python-trezor from git again and now it is working.
the file you specified however is now missing!?

is the file supposed to go missing?

**Comment by romanz** [comment]
Maybe it's installed now somewhere else?
Could you please run:
```
$ python -c "import trezorlib.transport_hid; print(trezorlib.transport_hid)"
```
It should print the path of the module it is using for communication with the TREZOR.

**Comment by fruitloop** [comment]
thanks it did indeed change the path
```
python -c "import trezorlib.transport_hid; print(trezorlib.transport_hid)"
<module 'trezorlib.transport_hid' from '/Library/Python/2.7/site-packages/trezor-0.6.12_1-py2.7.egg/trezorlib/transport_hid.pyc'>
```
Now everything seems to work.
Thanks again

best regards
roland

**Comment by romanz** [comment]
You're welcome :)
Many thanks for using this package and helping debugging the issue!
