### ISSUE TITLE
Not working with Ledger Nano S

### ISSUE THREAD

**Issue by martintreurnicht** [romanz/trezor-agent#59]
Using Ledger Nano S with firmware 1.2 on OSX 10.12

When i try and run `trezor-agent me@localhost`, i get the following error:

```bash
Traceback (most recent call last):
  File "/usr/local/bin/trezor-agent", line 11, in <module>
    sys.exit(run_agent())
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/__main__.py", line 115, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/__main__.py", line 132, in run_agent
    public_key = conn.get_public_key(label=label)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/client.py", line 53, in get_public_key
    ecdsa_curve_name=self.curve)
  File "/usr/local/lib/python2.7/site-packages/trezor_agent/factory.py", line 131, in get_public_node
    result = bytearray(self.dongle.exchange(bytes(apdu)))[1:]
  File "/usr/local/lib/python2.7/site-packages/ledgerblue/comm.py", line 128, in exchange
    raise CommException("Invalid status %04x" % sw, sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6e00
```

Device is plugged in and unlocked with pin, logged the same issue with ledger directly, here is the link:

https://github.com/LedgerHQ/blue-app-ssh-agent/issues/2

**Comment by romanz** [comment]
Thanks for reporting this issue!

It indeed stopped working on my machine (Debian 8) after upgrading to the latest `ledgerblue` Python package version (0.1.8 from GitHub), even with the previous firmware versions (Secure Element: 1.1, MCU: 1.0).

When it works, it should print a public key when invoked like this:
```
$ trezor-agent localhost 
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEDnEWM+Qkar3ftSVbzvie61lAyjGcrl1MmDxwTW74uXr9f2/OLHA2G1caYlbkuKRMVP4/5v0dMU2hFPGQGQPL0= ssh://localhost
```

However, now it fails also with:
```
$ trezor-agent localhost 
Traceback (most recent call last):
  File "/home/roman/.local/bin/trezor-agent", line 11, in <module>
    load_entry_point('trezor-agent', 'console_scripts', 'trezor-agent')()
  File "/media/oldhome/roman/Code/trezor/trezor-agent/trezor_agent/__main__.py", line 115, in wrapper
    return func(*args, **kwargs)
  File "/media/oldhome/roman/Code/trezor/trezor-agent/trezor_agent/__main__.py", line 132, in run_agent
    public_key = conn.get_public_key(label=label)
  File "/media/oldhome/roman/Code/trezor/trezor-agent/trezor_agent/client.py", line 53, in get_public_key
    ecdsa_curve_name=self.curve)
  File "/media/oldhome/roman/Code/trezor/trezor-agent/trezor_agent/factory.py", line 131, in get_public_node
    result = bytearray(self.dongle.exchange(bytes(apdu)))[1:]
  File "/home/roman/.local/lib/python2.7/site-packages/ledgerblue/comm.py", line 128, in exchange
    raise CommException("Invalid status %04x" % sw, sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6e00
```

@btchip Could you please take a look?

**Comment by romanz** [comment]
After resetting the device, it seems to work again:
```
$ trezor-agent localhost 
=> 8002000115058000000d88544c45f40d6d00a09335c2b705ac47
<= 410440e711633e4246abddfb5255bcef89eeb5940ca319cae5d4c983c704d6ef8b97afd7f6fce2c70361b571a6256e4b8a44c54fe3fe6fd1d314da114f1901903cbd9000
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEDnEWM+Qkar3ftSVbzvie61lAyjGcrl1MmDxwTW74uXr9f2/OLHA2G1caYlbkuKRMVP4/5v0dMU2hFPGQGQPL0= ssh://localhost
```

**Comment by romanz** [comment]
The "Invalid status 6e00" error happens after firmware upgrade, when the SSH/PGP app is not installed.

**Comment by btchip** [comment]
yes, the only reason you'd get a 6e00 status is if you're not talking to the right app in the device (so if the GPG/SSH app is not currently running)

**Comment by martintreurnicht** [comment]
@romanz Ah, sorry i didn't realize that i had to install a app, i guess it makes sense. I was actually looking for something under the settings but couldn't find it. I can confirm that this is now working for me. This is great!

**Comment by romanz** [comment]
Thanks :)
