### ISSUE TITLE
Handle 'S PROGRESS need_entropy [...]' replies from gpg-agent

### ISSUE THREAD

**Issue by romanz** [romanz/trezor-agent#60]
This happened during RSA signature:

```
gpg-connect-agent: no running gpg-agent - starting '/usr/local/bin/gpg-agent'
gpg-connect-agent: waiting for the agent to come up ... (5s)
gpg-connect-agent: connection to agent established
2016-10-20 12:20:59,287 DEBUG        hashing 378 bytes                                                                                    [protocol.py:263]
2016-10-20 12:20:59,288 DEBUG        signing digest: 40E05004B3110CDF99841FBED5EA0A62E905F926C0FE240CED75E7A86FE52EDA                     [protocol.py:265]
2016-10-20 12:20:59,288 DEBUG        <- 'RESET'                                                                                           [keyring.py:41]
2016-10-20 12:20:59,288 DEBUG        -> 'OK Pleased to meet you, process 10335'                                                           [keyring.py:59]
2016-10-20 12:20:59,293 DEBUG        <- 'OPTION ttyname=/dev/pts/0'                                                                       [keyring.py:41]
2016-10-20 12:20:59,294 DEBUG        -> 'OK'                                                                                              [keyring.py:59]
2016-10-20 12:20:59,294 DEBUG        <- 'OPTION display=:0'                                                                               [keyring.py:41]
2016-10-20 12:20:59,294 DEBUG        -> 'OK'                                                                                              [keyring.py:59]
2016-10-20 12:20:59,294 DEBUG        <- 'SIGKEY 67DDBEE9C0D007C7E00F7C3C30EF3C09D0AA4E3B'                                                 [keyring.py:41]
2016-10-20 12:20:59,294 DEBUG        -> 'OK'                                                                                              [keyring.py:59]
2016-10-20 12:20:59,295 DEBUG        <- 'SETHASH 8 40E05004B3110CDF99841FBED5EA0A62E905F926C0FE240CED75E7A86FE52EDA'                      [keyring.py:41]
2016-10-20 12:20:59,295 DEBUG        -> 'OK'                                                                                              [keyring.py:59]
2016-10-20 12:20:59,295 DEBUG        <- 'SETKEYDESC Sign+a+new+TREZOR-based+subkey'                                                       [keyring.py:41]
2016-10-20 12:20:59,295 DEBUG        -> 'OK'                                                                                              [keyring.py:59]
2016-10-20 12:20:59,295 DEBUG        <- 'PKSIGN'                                                                                          [keyring.py:41]
2016-10-20 12:20:59,295 DEBUG        -> 'OK'                                                                                              [keyring.py:59]
2016-10-20 12:20:59,297 DEBUG        -> 'S PROGRESS need_entropy X 30 120'                                                                [keyring.py:59]
2016-10-20 12:20:59,298 DEBUG        unescaped: 'S PROGRESS need_entropy X 30 120'                                                        [keyring.py:163]
Traceback (most recent call last):
  File "/home/roman/.local/bin/trezor-gpg", line 11, in <module>
    load_entry_point('trezor-agent', 'console_scripts', 'trezor-gpg')()
  File "/media/oldhome/roman/Code/trezor/trezor-agent/trezor_agent/gpg/__main__.py", line 102, in main
    args.run(args)
  File "/media/oldhome/roman/Code/trezor/trezor-agent/trezor_agent/gpg/__main__.py", line 39, in run_create
    signer_func=conn.sign)
  File "/media/oldhome/roman/Code/trezor/trezor-agent/trezor_agent/gpg/encode.py", line 99, in create_subkey
    unhashed_subpackets=unhashed_subpackets)
  File "/media/oldhome/roman/Code/trezor/trezor-agent/trezor_agent/gpg/protocol.py", line 266, in make_signature
    params = signer_func(digest=digest)
  File "/media/oldhome/roman/Code/trezor/trezor-agent/trezor_agent/gpg/keyring.py", line 222, in sign
    return sign_digest(sock=sock, keygrip=keygrip, digest=digest)
  File "/media/oldhome/roman/Code/trezor/trezor-agent/trezor_agent/gpg/keyring.py", line 166, in sign_digest
    raise ValueError(prefix)
ValueError: S
```

**Comment by romanz** [comment]
This can be reproduced by running `cat /dev/random` and killing `gpg-agent` before generating a subkey.
