### ISSUE TITLE
Cannot start trezor-agent anymore

### ISSUE THREAD

**Issue by fansari** [romanz/trezor-agent#74]
Hi, 

when I install the latest version and run it I get this error message:

```
fansari@bat trezor-agent]$ trezor-agent -c magpie
Traceback (most recent call last):
  File "/usr/bin/trezor-agent", line 11, in <module>
    load_entry_point('trezor-agent==0.7.5', 'console_scripts', 'trezor-agent')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2608, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2268, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2274, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/trezor_agent/__main__.py", line 10, in <module>
ImportError: cannot import name device
```

**Comment by romanz** [comment]
Thanks for reporting this issue!
Maybe the [device](https://github.com/romanz/trezor-agent/tree/master/trezor_agent/device) package wasn't installed?
Could please try to install trezor-agent in a virtualenv, to see if there is a problem with the installation?

**Comment by romanz** [comment]
Got it - the PyPI version is broken, since https://github.com/romanz/trezor-agent/blob/master/setup.py#L11 doesn't include `trezor_agent.device` package.
Will fix this tomorrow.

**Comment by romanz** [comment]
Please try v0.7.6 from https://pypi.python.org/pypi/trezor_agent/

**Comment by fansari** [comment]
This is working. I can login on multiple shells but still not to multiple machines.

**Comment by romanz** [comment]
Thanks :)
Great to hear!
