### ISSUE TITLE
Fails on Mac OS X

### ISSUE THREAD

**Issue by bgok** [romanz/trezor-agent#9]
I tried it with both Trezor and KeepKey, same result. Here's the output:

```
bash-3.2$ trezor-agent kenheut@192.168.1.126 -c -vv
2016-01-15 15:32:13,049 DEBUG        connected to KeepKey 71A98D347CD0892AFEC4501E                                                        [factory.py:26]
2016-01-15 15:32:13,049 DEBUG        label    : empty                                                                                     [factory.py:27]
2016-01-15 15:32:13,049 DEBUG        vendor   : keepkey.com                                                                               [factory.py:28]
2016-01-15 15:32:13,049 DEBUG        version  : 1.0.4                                                                                     [factory.py:32]
2016-01-15 15:32:13,049 DEBUG        revision : 0c1cae8edc16ff2241aefd659d113cc0d6b65b10                                                  [factory.py:33]
2016-01-15 15:32:13,051 DEBUG        parsed identity: {'path': None, 'host': '192.168.1.126', 'proto': None, 'port': None, 'user': 'kenheut'} [client.py:88]
2016-01-15 15:32:13,052 INFO         getting "ssh://kenheut@192.168.1.126" public key (nist256p1) from KeepKey...                         [client.py:41]
2016-01-15 15:32:13,052 DEBUG        address string: '\x00\x00\x00\x00ssh://kenheut@192.168.1.126'                                        [client.py:110]
Use the numeric keypad to describe number positions. The layout is:
    7 8 9
    4 5 6
    1 2 3
Please enter current PIN: 

2016-01-15 15:32:17,627 DEBUG        fingerprint: 30:76:db:4c:32:67:16:3d:2f:c7:92:48:5a:f6:d4:c0                                         [formats.py:142]
2016-01-15 15:32:17,627 DEBUG        parsed identity: {'path': None, 'host': '192.168.1.126', 'proto': None, 'port': None, 'user': 'kenheut'} [client.py:88]
2016-01-15 15:32:17,627 DEBUG        SSH connect: ['ssh', '-l', 'kenheut', '192.168.1.126']                                               [__main__.py:107]
2016-01-15 15:32:17,629 DEBUG        loading SSH public key: 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBN7zpDDG5rZ3+yuhw68f60SDVEyReMZr+3hRnEUkKlTCtD504vhmns1dU7qE6TURc1ZnNEOhpyWbfrKQeePu5U0= ssh://kenheut@192.168.1.126\n' [formats.py:149]
2016-01-15 15:32:17,630 DEBUG        key type: ecdsa-sha2-nistp256                                                                        [formats.py:38]
2016-01-15 15:32:17,630 DEBUG        curve name: nistp256                                                                                 [formats.py:45]
2016-01-15 15:32:17,630 DEBUG        loaded ecdsa-sha2-nistp256 public key: 30:76:db:4c:32:67:16:3d:2f:c7:92:48:5a:f6:d4:c0               [formats.py:155]
2016-01-15 15:32:17,630 DEBUG        serving on SSH_AUTH_SOCK=/var/folders/nq/1lv_2c391pqd8xl0kyj8qk5h0000gn/T/ssh-agent-nb7Rof           [server.py:26]
2016-01-15 15:32:17,630 DEBUG        server thread started                                                                                [server.py:62]
2016-01-15 15:32:17,630 INFO         running ['ssh', '-l', 'kenheut', '192.168.1.126'] with {'SSH_AUTH_SOCK': '/var/folders/nq/1lv_2c391pqd8xl0kyj8qk5h0000gn/T/ssh-agent-nb7Rof', 'SSH_AGENT_PID': '44920'} [server.py:109]
2016-01-15 15:32:17,630 DEBUG        waiting for connection on /var/folders/nq/1lv_2c391pqd8xl0kyj8qk5h0000gn/T/ssh-agent-nb7Rof          [server.py:69]
2016-01-15 15:32:17,634 DEBUG        subprocess 44923 is running                                                                          [server.py:116]
2016-01-15 15:32:17,699 DEBUG        welcome agent                                                                                        [server.py:40]
2016-01-15 15:32:17,699 DEBUG        request: 1 bytes                                                                                     [protocol.py:43]
2016-01-15 15:32:17,699 DEBUG        calling list_pubs()                                                                                  [protocol.py:47]
2016-01-15 15:32:17,699 DEBUG        available keys: ['ssh://kenheut@192.168.1.126']                                                      [protocol.py:66]
2016-01-15 15:32:17,699 DEBUG         1) 30:76:db:4c:32:67:16:3d:2f:c7:92:48:5a:f6:d4:c0                                                  [protocol.py:68]
2016-01-15 15:32:17,699 DEBUG        reply: 148 bytes                                                                                     [protocol.py:49]
2016-01-15 15:32:17,700 WARNING      error: [Errno 35] Resource temporarily unavailable                                                   [server.py:48]
Traceback (most recent call last):
  File "build/bdist.macosx-10.10-x86_64/egg/trezor_agent/server.py", line 42, in handle_connection
    msg = util.read_frame(conn)
  File "build/bdist.macosx-10.10-x86_64/egg/trezor_agent/util.py", line 37, in read_frame
    size, = recv(conn, '>L')
  File "build/bdist.macosx-10.10-x86_64/egg/trezor_agent/util.py", line 24, in recv
    buf = _read(size)
error: [Errno 35] Resource temporarily unavailable
2016-01-15 15:32:17,700 DEBUG        waiting for connection on /var/folders/nq/1lv_2c391pqd8xl0kyj8qk5h0000gn/T/ssh-agent-nb7Rof          [server.py:69]
kenheut@192.168.1.126's password: 
2016-01-15 15:32:20,880 DEBUG        closing server                                                                                       [server.py:104]
2016-01-15 15:32:20,880 INFO         server stopped                                                                                       [__main__.py:123]
2016-01-15 15:32:20,880 INFO         disconnected from KeepKey                                                                            [client.py:28]
2016-01-15 15:32:20,921 DEBUG        server stopped                                                                                       [server.py:73]
2016-01-15 15:32:20,921 DEBUG        server thread stopped                                                                                [server.py:77]
```

**Comment by romanz** [comment]
A bit of background:
I had an issue reported (https://github.com/romanz/trezor-agent/issues/6) for Mac OS X last week.
It seemed that there was a problem with some socket system calls on Mac OS X, 
so I have rewritten the exit logic using polling (instead of calling `shutdown()` on the listening socket) at https://github.com/romanz/trezor-agent/commit/fb0d0a5f6138d3e55786ae8b32b6ea2d231527c9.
However, I have tested this only on my Debian workstation, so I am not sure this fix works on Mac OS.

**Comment by romanz** [comment]
Does the `Resource temporarily unavailable` error happens all the time?
Does it happen always after the first `list_pubs()` reply is sent?
What version of SSH client are you using on Mac OS X?

**Comment by romanz** [comment]
An idea: can you tweak `server.UNIX_SOCKET_TIMEOUT` constant (https://github.com/romanz/trezor-agent/blob/master/trezor_agent/server.py#L13)?
Currently, it is set 100 ms, but it may be increased to a few seconds to check if it affects the error.

**Comment by romanz** [comment]
It seems that EAGAIN on Mac OS X has errno=35:
http://stackoverflow.com/questions/14595269/errno-35-eagain-returned-on-recv-call

**Comment by romanz** [comment]
If the problem is that the `recv()` system call is failing with EAGAIN due to a timeout, could you please try the following patch (to make sure that the accepted connection is set to blocking mode) on Mac OS?

```diff
diff --git a/trezor_agent/server.py b/trezor_agent/server.py
index 38835fe..a04a3a4 100644
--- a/trezor_agent/server.py
+++ b/trezor_agent/server.py
@@ -63,6 +63,7 @@ def server_thread(server, handler, quit_event):
 
     def accept_connection():
         conn, _ = server.accept()
+        conn.settimeout(None)
         return conn
 
     while True:
```

**Comment by romanz** [comment]
You can also now set the timeout via a command-line argument: https://github.com/romanz/trezor-agent/commit/b101281a5b53477d3553bd4b9a01cb38e513537e

**Comment by bgok** [comment]
@romanz The conn.settimeout(None) fixed it. I tried with both KeepKey and Trezor and they both work.

**Comment by romanz** [comment]
Great! 
I will push the fix to master branch.
