### ISSUE TITLE
Suggest: add OS list support and OSX build instructions

### ISSUE THREAD

**Issue by harobed** [romanz/trezor-agent#93]
In documentation I see:

```
apt-get install python-dev libusb-1.0-0-dev libudev-dev
```

it's for Debian/Ubuntu. Where is information about OS support ?

If your project support OSX system, can you add OSX build instruction ?

Best regards,
Stéphane

**Comment by fruitloop** [comment]
As far as I remember, there were no dependencies.

just: 
```
git clone https://github.com/romanz/trezor-agent
python setup.py build
python setup.py install
```
The usual stuff.

**Comment by harobed** [comment]
I think it is missing some requirements:

```
$  git clone https://github.com/romanz/trezor-agent
Cloning into 'trezor-agent'...
remote: Counting objects: 3030, done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 3030 (delta 29), reused 0 (delta 0), pack-reused 2971
Receiving objects: 100% (3030/3030), 1.29 MiB | 1.73 MiB/s, done.
Resolving deltas: 100% (2151/2151), done.
$ cd trezor-agent/
$ python setup.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/trezor_agent
copying trezor_agent/__init__.py -> build/lib/trezor_agent
copying trezor_agent/__main__.py -> build/lib/trezor_agent
copying trezor_agent/client.py -> build/lib/trezor_agent
copying trezor_agent/formats.py -> build/lib/trezor_agent
copying trezor_agent/protocol.py -> build/lib/trezor_agent
copying trezor_agent/server.py -> build/lib/trezor_agent
copying trezor_agent/util.py -> build/lib/trezor_agent
creating build/lib/trezor_agent/device
copying trezor_agent/device/__init__.py -> build/lib/trezor_agent/device
copying trezor_agent/device/interface.py -> build/lib/trezor_agent/device
copying trezor_agent/device/keepkey.py -> build/lib/trezor_agent/device
copying trezor_agent/device/keepkey_defs.py -> build/lib/trezor_agent/device
copying trezor_agent/device/ledger.py -> build/lib/trezor_agent/device
copying trezor_agent/device/trezor.py -> build/lib/trezor_agent/device
copying trezor_agent/device/trezor_defs.py -> build/lib/trezor_agent/device
creating build/lib/trezor_agent/gpg
copying trezor_agent/gpg/__init__.py -> build/lib/trezor_agent/gpg
copying trezor_agent/gpg/__main__.py -> build/lib/trezor_agent/gpg
copying trezor_agent/gpg/agent.py -> build/lib/trezor_agent/gpg
copying trezor_agent/gpg/client.py -> build/lib/trezor_agent/gpg
copying trezor_agent/gpg/decode.py -> build/lib/trezor_agent/gpg
copying trezor_agent/gpg/encode.py -> build/lib/trezor_agent/gpg
copying trezor_agent/gpg/keyring.py -> build/lib/trezor_agent/gpg
copying trezor_agent/gpg/protocol.py -> build/lib/trezor_agent/gpg
$  sudo python setup.py install
Password:
running install
running bdist_egg
running egg_info
writing requirements to trezor_agent.egg-info/requires.txt
writing trezor_agent.egg-info/PKG-INFO
writing top-level names to trezor_agent.egg-info/top_level.txt
writing dependency_links to trezor_agent.egg-info/dependency_links.txt
writing entry points to trezor_agent.egg-info/entry_points.txt
reading manifest file 'trezor_agent.egg-info/SOURCES.txt'
writing manifest file 'trezor_agent.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.11-x86_64/egg
creating build/bdist.macosx-10.11-x86_64/egg/trezor_agent
copying build/lib/trezor_agent/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent
copying build/lib/trezor_agent/__main__.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent
copying build/lib/trezor_agent/client.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent
creating build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device
copying build/lib/trezor_agent/device/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device
copying build/lib/trezor_agent/device/interface.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device
copying build/lib/trezor_agent/device/keepkey.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device
copying build/lib/trezor_agent/device/keepkey_defs.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device
copying build/lib/trezor_agent/device/ledger.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device
copying build/lib/trezor_agent/device/trezor.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device
copying build/lib/trezor_agent/device/trezor_defs.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device
copying build/lib/trezor_agent/formats.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent
creating build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg
copying build/lib/trezor_agent/gpg/__init__.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg
copying build/lib/trezor_agent/gpg/__main__.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg
copying build/lib/trezor_agent/gpg/agent.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg
copying build/lib/trezor_agent/gpg/client.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg
copying build/lib/trezor_agent/gpg/decode.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg
copying build/lib/trezor_agent/gpg/encode.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg
copying build/lib/trezor_agent/gpg/keyring.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg
copying build/lib/trezor_agent/gpg/protocol.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg
copying build/lib/trezor_agent/protocol.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent
copying build/lib/trezor_agent/server.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent
copying build/lib/trezor_agent/util.py -> build/bdist.macosx-10.11-x86_64/egg/trezor_agent
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/__main__.py to __main__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/client.py to client.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device/interface.py to interface.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device/keepkey.py to keepkey.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device/keepkey_defs.py to keepkey_defs.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device/ledger.py to ledger.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device/trezor.py to trezor.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/device/trezor_defs.py to trezor_defs.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/formats.py to formats.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/__main__.py to __main__.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/agent.py to agent.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/client.py to client.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/decode.py to decode.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/encode.py to encode.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/keyring.py to keyring.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/gpg/protocol.py to protocol.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/protocol.py to protocol.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/server.py to server.pyc
byte-compiling build/bdist.macosx-10.11-x86_64/egg/trezor_agent/util.py to util.pyc
creating build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying trezor_agent.egg-info/PKG-INFO -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying trezor_agent.egg-info/SOURCES.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying trezor_agent.egg-info/dependency_links.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying trezor_agent.egg-info/entry_points.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying trezor_agent.egg-info/requires.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying trezor_agent.egg-info/top_level.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/trezor_agent-0.8.2-py2.7.egg' and adding 'build/bdist.macosx-10.11-x86_64/egg' to it
removing 'build/bdist.macosx-10.11-x86_64/egg' (and everything under it)
Processing trezor_agent-0.8.2-py2.7.egg
Removing /usr/local/lib/python2.7/site-packages/trezor_agent-0.8.2-py2.7.egg
Copying trezor_agent-0.8.2-py2.7.egg to /usr/local/lib/python2.7/site-packages
trezor-agent 0.8.2 is already the active version in easy-install.pth
Installing trezor-gpg-unlock script to /usr/local/bin
Installing trezor-gpg-create script to /usr/local/bin
Installing trezor-agent script to /usr/local/bin
Installing trezor-gpg-agent script to /usr/local/bin

Installed /usr/local/lib/python2.7/site-packages/trezor_agent-0.8.2-py2.7.egg
Processing dependencies for trezor-agent==0.8.2
Searching for pillow>=3.4.0
Reading https://pypi.python.org/simple/pillow/
Downloading https://pypi.python.org/packages/8d/80/eca7a2d1a3c2dafb960f32f844d570de988e609f5fd17de92e1cf6a01b0a/Pillow-4.0.0.tar.gz#md5=d5af224b0fa2c66dacc9814785fef9e7
Best match: Pillow 4.0.0
Processing Pillow-4.0.0.tar.gz
Writing /tmp/easy_install-lcuS08/Pillow-4.0.0/setup.cfg
Running Pillow-4.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-lcuS08/Pillow-4.0.0/egg-dist-tmp-yXP2GJ
warning: no files found matching '*.sh'
no previously-included directories found matching 'docs/_static'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.editorconfig'
warning: no previously-included files found matching '.landscape.yaml'
warning: no previously-included files found matching 'appveyor.yml'
warning: no previously-included files found matching 'build_children.sh'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution


The headers or library files could not be found for zlib,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   http://pillow.readthedocs.io/en/latest/installation.html

Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    'trezor-gpg-unlock = trezor_agent.gpg.__main__:auto_unlock',
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 646, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 742, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 846, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1118, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1130, in obtain
    return installer(requirement)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 251, in run_setup
    raise
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 157, in save_modules
    yield saved
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 248, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 278, in run
    return func()
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 246, in runner
    _execfile(setup_script, ns)
  File "/usr/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-lcuS08/Pillow-4.0.0/setup.py", line 791, in <module>

setuptools.sandbox.UnpickleableException: RequiredDependencyException('\n\nThe headers or library files could not be found for zlib,\na required dependency when compiling Pillow from source.\n\nPlease see the install instructions at:\n   http://pillow.readthedocs.io/en/latest/installation.html\n\n',)
```

**Comment by romanz** [comment]
@harobed Unfortunately, I don't have a Mac OS X machine for creating an installation tutorial - but I'd be happy to merge any pull request for [https://github.com/romanz/trezor-agent/blob/master/README.md](README.md) describing the installation on Mac OS X...

**Comment by romanz** [comment]
@fruitloop Thanks for the information!

**Comment by romanz** [comment]
@harobed Regarding the `Pillow`-related error - please take a look at #90 (it could be resolved by using the latest `pip`, or maybe upgrading `setuptools` package: https://github.com/romanz/trezor-agent/commit/5bec0e8382dafc099506d42d82ac1d3ceb536e87)

**Comment by romanz** [comment]
@harobed Did running the following commands work for you?
```
$ sudo pip install -U setuptools pip
$ pip install --user Cython trezor_agent
```

**Comment by harobed** [comment]
@romanz installation success. Now I try to use ssh agent

**Comment by harobed** [comment]
trezor agent work perfectly! Thanks

**Comment by romanz** [comment]
Great, you're welcome :)
Please let me know if there is anything I can change in the installation instructions.

**Comment by rtacconi** [comment]
I managed to install it in a Mac but I cannot find the `trezor-agent` program. Do you know where it is installed?

**Comment by romanz** [comment]
@rtacconi AFAIK, it should be under [~/Library/Python/X.Y/bin](https://github.com/romanz/trezor-agent/blob/master/doc/INSTALL.md#troubleshooting).
Please let me know if the documentation is correct (since I don't use a Mac).
