### ISSUE TITLE
failure: Device not found on Mac OS

### ISSUE THREAD

**Issue by gabridome** [romanz/trezor-agent#95]
I have tried everything I have seen around either via virtualenv or directly, as a superuser or as me, from Github and with pip, with python3 and with python2.
The best result is "failure: Device not found" when I run:

    trezorctl -v get_features | head

Yes. I have plugged in my Ledger Nano S.
Yes the app is open.

- Mac OS Sierra 10.12.2 (16C67)
- Python 2.7.12 

```
$ pip install trezor
Requirement already satisfied: trezor in /usr/local/lib/python2.7/site-packages/trezor-0.7.8-py2.7.egg
Requirement already satisfied: ecdsa>=0.9 in /usr/local/lib/python2.7/site-packages (from trezor)
Requirement already satisfied: protobuf>=2.6.1 in /usr/local/Cellar/protobuf/3.1.0/libexec/lib/python2.7/site-packages (from trezor)
Requirement already satisfied: mnemonic>=0.8 in /usr/local/lib/python2.7/site-packages (from trezor)
Requirement already satisfied: setuptools>=19.0 in /usr/local/lib/python2.7/site-packages (from trezor)
Requirement already satisfied: hidapi>=0.7.99 in /usr/local/lib/python2.7/site-packages (from trezor)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python2.7/site-packages (from protobuf>=2.6.1->trezor)
Requirement already satisfied: pbkdf2 in /usr/local/lib/python2.7/site-packages (from mnemonic>=0.8->trezor)
Requirement already satisfied: appdirs>=1.4.0 in /usr/local/lib/python2.7/site-packages (from setuptools>=19.0->trezor)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python2.7/site-packages (from setuptools>=19.0->trezor)
Requirement already satisfied: pyparsing in /usr/local/lib/python2.7/site-packages (from packaging>=16.8->setuptools>=19.0->trezor)

$ pip install -U setuptools
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: appdirs>=1.4.0 in /usr/local/lib/python2.7/site-packages (from setuptools)
Requirement already up-to-date: six>=1.10.0 in /usr/local/lib/python2.7/site-packages (from setuptools)
Requirement already up-to-date: packaging>=16.8 in /usr/local/lib/python2.7/site-packages (from setuptools)
Requirement already up-to-date: pyparsing in /usr/local/lib/python2.7/site-packages (from packaging>=16.8->setuptools)

$ pip install -U pip
Requirement already up-to-date: pip in /usr/local/lib/python2.7/site-packages
```

**Comment by romanz** [comment]
Please install `trezor_agent` package (using `pip install trezor_agent`), and run:
```
$ trezor-agent -vv foobar
2017-01-24 19:40:24,789 DEBUG        parsed identity: {'user': None, 'path': None, 'port': None, 'proto': None, 'host': 'foobar'}         [interface.py:28]
2017-01-24 19:40:24,789 DEBUG        identity parts: ['ssh://', 'foobar']                                                                 [interface.py:44]
2017-01-24 19:40:24,789 INFO         identity #0: <ssh://foobar|nist256p1>                                                                [__main__.py:183]
2017-01-24 19:40:24,828 DEBUG        device not found: Trezor not connected                                                               [__init__.py:26]
2017-01-24 19:40:24,849 DEBUG        device not found: KeepKey not connected                                                              [__init__.py:26]
2017-01-24 19:40:24,861 DEBUG        identity parts: ['ssh://', 'foobar']                                                                 [interface.py:44]
2017-01-24 19:40:24,861 DEBUG        bip32 address string: b'\x00\x00\x00\x00ssh://foobar'                                                [interface.py:80]
2017-01-24 19:40:27,416 DEBUG        identity parts: ['ssh://', 'foobar']                                                                 [interface.py:44]
2017-01-24 19:40:27,416 DEBUG        fingerprint: 62:24:fe:3d:9e:7d:8a:6c:cc:c1:48:e2:3c:77:b4:10                                         [formats.py:185]
ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLPyr1VsvUY58Tiaxx0Gm0vAAA+1LvUpOpW3mUcw8Mg1R0boO7UQLUGnhiOptgLPEjcAKL8o9CHPliY2op09f4c= <ssh://foobar|nist256p1>
```
Does it work for you?
If something fails, please paste the error here.

**Comment by gabridome** [comment]
Thank you I will

Il mar 24 gen 2017, 18:41 Roman Zeyde <notifications@github.com> ha scritto:

**Comment by gabridome** [comment]
(v3) MacBook-di-Gabriele:~ gbd$ trezor-agent -vv foobar

2017-01-24 21:49:08,609 DEBUG        parsed identity: {'proto': None,
'host': 'foobar', 'port': None, 'user': None, 'path': None}
[interface.py:28]

2017-01-24 21:49:08,610 DEBUG        identity parts: ['ssh://', 'foobar']

[interface.py:44]

2017-01-24 21:49:08,610 INFO         identity #0: <ssh://foobar|nist256p1>

[__main__.py:183]

2017-01-24 21:49:08,671 DEBUG        device not found: Trezor not connected
                                                            [__init__.py:26]

Traceback (most recent call last):

  File "/tmp/v3/bin/trezor-agent", line 11, in <module>

    load_entry_point('trezor-agent==0.8.2', 'console_scripts',
'trezor-agent')()

  File
"/private/tmp/v3/lib/python3.4/site-packages/trezor_agent/__main__.py",
line 128, in wrapper

    return func(*args, **kwargs)

  File
"/private/tmp/v3/lib/python3.4/site-packages/trezor_agent/__main__.py",
line 203, in run_agent

    for pk in conn.public_keys():

  File
"/private/tmp/v3/lib/python3.4/site-packages/trezor_agent/__main__.py",
line 153, in public_keys

    conn = self.conn_factory()

  File
"/private/tmp/v3/lib/python3.4/site-packages/trezor_agent/__main__.py",
line 197, in <lambda>

    conn_factory=lambda: client_factory(device.detect()),

  File
"/private/tmp/v3/lib/python3.4/site-packages/trezor_agent/device/__init__.py",
line 23, in detect

    with device_type() as d:

  File
"/private/tmp/v3/lib/python3.4/site-packages/trezor_agent/device/interface.py",
line 110, in __enter__

    self.conn = self.connect()

  File
"/private/tmp/v3/lib/python3.4/site-packages/trezor_agent/device/trezor.py",
line 32, in connect

    for d in self._defs.HidTransport.enumerate():

  File
"/private/tmp/v3/lib/python3.4/site-packages/trezor_agent/device/keepkey.py",
line 25, in _defs

    from . import keepkey_defs

  File
"/private/tmp/v3/lib/python3.4/site-packages/trezor_agent/device/keepkey_defs.py",
line 5, in <module>

    from keepkeylib.client import CallException as Error

  File "/private/tmp/v3/lib/python3.4/site-packages/keepkeylib/client.py",
line 15, in <module>

    from . import mapping

  File "/private/tmp/v3/lib/python3.4/site-packages/keepkeylib/mapping.py",
line 1, in <module>

    from . import messages_pb2 as proto

  File
"/private/tmp/v3/lib/python3.4/site-packages/keepkeylib/messages_pb2.py",
line 12, in <module>

    import types_pb2

ImportError: No module named 'types_pb2'

**Comment by romanz** [comment]
It seems that you are using Python 3 here, and unfortunately Keepkey doesn't support it (https://github.com/keepkey/python-keepkey/issues/7).
Can you please try using Python 2?

**Comment by btchip** [comment]
Also make sure you run pip install ledgerblue before to use it with a Nano S

**Comment by gabridome** [comment]
Ahhh. Of course! I will downgrade exiting from virtualenv and will try
everything from almost scratch.
Thank you guys. I will keep you informed.

Il mer 25 gen 2017, 07:00 Nicolas Bacca <notifications@github.com> ha
scritto:

**Comment by gabridome** [comment]
Thank you guys.
Good news: everything works.
Bad news: I have done so many things that I don't know exactly what has
gone right.

The only hints I have is to try to stick with normal user instead of super
user (sudo) and stick with python 2. Probably also use the "brew" version
of python instead of the Apple's one.

I had to use pip2 to be sure I was using the right version too.
I solved when I began to see strange errors and they suggested me to use
the brew version of python (brew install python) instead of Apple's one.
From there everything start working.
When I will be back home I will try to repeat the process and to document
it.

**Comment by romanz** [comment]
ping :)

**Comment by gabridome** [comment]
I messed up on my office mac. The problem is to mix python shipped with mac
Xcode and the brew one.
I'm away from office for few days but I expect it will be difficult to
restore pip. :(

Il mar 21 feb 2017, 12:17 Roman Zeyde <notifications@github.com> ha scritto:

**Comment by romanz** [comment]
No problem :)

**Comment by talmai** [comment]
**Can I reopen this please? On my machine...**

$ trezor-agent -vv foobar

2017-11-06 12:11:35,208 DEBUG        parsed identity: {'path': None, 'host': 'foobar', 'proto': None, 'port': None, 'user': None}         [interface.py:30]
2017-11-06 12:11:35,208 DEBUG        identity parts: ['ssh://', 'foobar']                                                                 [interface.py:46]
2017-11-06 12:11:35,208 INFO         identity #0: <ssh://foobar|nist256p1>                                                                [__init__.py:201]
Traceback (most recent call last):
  File "/usr/local/bin/trezor-agent", line 11, in <module>
    sys.exit(ssh_agent())
  File "/usr/local/bin/trezor_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/Library/Python/2.7/site-packages/libagent/ssh/__init__.py", line 130, in wrapper
    return func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/libagent/ssh/__init__.py", line 221, in main
    for pk in conn.public_keys():
  File "/Library/Python/2.7/site-packages/libagent/ssh/__init__.py", line 165, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/Library/Python/2.7/site-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/Library/Python/2.7/site-packages/libagent/device/interface.py", line 118, in __enter__
    self.conn = self.connect()
  File "/Library/Python/2.7/site-packages/libagent/device/trezor.py", line 82, in connect
    raise interface.NotFoundError('{} not connected'.format(self))
libagent.device.interface.NotFoundError: Trezor not connected

**Any ideas?**
