### ISSUE TITLE
AssertionError in _parse_ed25519_pubkey

### ISSUE THREAD

**Issue by pafcu** [romanz/trezor-agent#97]
When I do e.g. `gpg --list-secret-keys` I don't get any keys listed, but gpg-agent.log shows
```
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/trezor_agent/gpg/__main__.py", line 110, in main_agent
    agent.handle_connection(conn)
  File "build/bdist.linux-x86_64/egg/trezor_agent/gpg/agent.py", line 150, in handle_connection
    if not have_key(keygrip=args[0]):
  File "build/bdist.linux-x86_64/egg/trezor_agent/util.py", line 202, in wrapper
    result = func(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/trezor_agent/gpg/agent.py", line 113, in have_key
    open_connection(keygrip_bytes=binascii.unhexlify(keygrip))
  File "build/bdist.linux-x86_64/egg/trezor_agent/gpg/agent.py", line 48, in open_connection
    keygrip=keygrip_bytes)
  File "build/bdist.linux-x86_64/egg/trezor_agent/gpg/decode.py", line 281, in load_by_keygrip
    packets = list(parse_packets(stream))
  File "build/bdist.linux-x86_64/egg/trezor_agent/gpg/decode.py", line 249, in parse_packets
    p = packet_type(util.Reader(io.BytesIO(packet_data)))
  File "build/bdist.linux-x86_64/egg/trezor_agent/gpg/decode.py", line 166, in _parse_pubkey
    keygrip = keygrip_func(parse_func(mpi))
  File "build/bdist.linux-x86_64/egg/trezor_agent/gpg/decode.py", line 67, in _parse_ed25519_pubkey
    assert prefix == 0x40
AssertionError
```
I think I got this to work earlier, so I'm not sure what is triggering it now.

**Comment by romanz** [comment]
Thanks for reporting this issue!

**Comment by romanz** [comment]
BTW, which GnuPG version are you using (`gpg2 --version`)?

**Comment by pafcu** [comment]
```
gpg (GnuPG) 2.1.18
libgcrypt 1.7.6
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/me/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by romanz** [comment]
Could you please run `gpg2 --export | gpg2 --list-packets -v` and paste the output here?
```
$ CURVE=ed25519 TIMESTAMP=1477727920 ./scripts/gpg-init "blah"
$ ./scripts/gpg-shell
$ gpg2 --export | gpg2 --list-packets -v
# off=0 ctb=98 tag=6 hlen=2 plen=51
:public key packet:
	version 4, algo 22, created 1477727920, expires 0
	pkey[0]: 092B06010401DA470F01 ed25519 (1.3.6.1.4.1.11591.15.1)
	pkey[1]: 40430A0A200370E75D745305E4A4F0FBA280287EB689F2D96C19771EE303DD3B22
	keyid: 378CECF156985BD7
# off=53 ctb=b4 tag=13 hlen=2 plen=4
:user ID packet: "blah"
# off=59 ctb=88 tag=2 hlen=2 plen=121
:signature packet: algo 22, keyid 378CECF156985BD7
	version 4, created 1477727920, md5len 0, sigclass 0x13
	digest algo 8, begin of digest 30 4b
	hashed subpkt 2 len 4 (sig created 2016-10-29)
	hashed subpkt 11 len 1 (pref-sym-algos: 9)
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 21 len 1 (pref-hash-algos: 8)
	hashed subpkt 22 len 1 (pref-zip-algos: 0)
	hashed subpkt 23 len 1 (key server preferences: 80)
	subpkt 16 len 8 (issuer key ID 378CECF156985BD7)
	subpkt 26 len 10 (policy: TREZOR-GPG)
	data: 904B4E2B0F3316E469F1784C6961E810D166F217FE87976EE494F1D0B4DD386D
	data: 8D3CC84D807892C10945A50E013AE8217175289B6B97C0D1D5EE3D31B12AC10F
# off=182 ctb=b8 tag=14 hlen=2 plen=56
:public sub key packet:
	version 4, algo 18, created 1477727920, expires 0
	pkey[0]: 0A2B060104019755010501 cv25519 (1.3.6.1.4.1.3029.1.5.1)
	pkey[1]: 407FC65058B2F8E88745F3181A18071517A2EB8F90B2D17DCED92B8BF8AAF97C74
	pkey[2]: 03010807
	keyid: 9D1F4373C93F016B
# off=240 ctb=88 tag=2 hlen=2 plen=109
:signature packet: algo 22, keyid 378CECF156985BD7
	version 4, created 1477727920, md5len 0, sigclass 0x18
	digest algo 8, begin of digest 03 36
	hashed subpkt 2 len 4 (sig created 2016-10-29)
	hashed subpkt 27 len 1 (key flags: 0C)
	subpkt 16 len 8 (issuer key ID 378CECF156985BD7)
	subpkt 26 len 10 (policy: TREZOR-GPG)
	data: 893F965FCA4540BEBB9BA2FAEEC94B1213BCE64EC25CE442B117BEA81F075F51
	data: CDA1E6A3ED5EAB8C181371CDB48C00EB89656078CE66ACB805762F9BAFFFBA04
```
Maybe something went wrong with the GnuPG identity public keys...

**Comment by pafcu** [comment]
This is for my existing, old key:

```
# off=0 ctb=98 tag=6 hlen=2 plen=82
:public key packet:
	version 4, algo 19, created 1485105188, expires 0
	pkey[0]: 082A8648CE3D030107 nistp256 (1.2.840.10045.3.1.7)
	pkey[1]: 04F038C0C7989C3AF74C6C38BBA1D64D4A73EC166804C9F927B4B4CF22F69DD418376CB242DE698220CDD50B81A5DD33D891AA02F8D8C341F805691570CA372C7C
	keyid: A59E3DA5EA8FE38F
# off=84 ctb=b4 tag=13 hlen=2 plen=51
:user ID packet: "Stefan Parviainen <stefan.parviainen@univ-rouen.fr>"
# off=137 ctb=88 tag=2 hlen=2 plen=121
:signature packet: algo 19, keyid A59E3DA5EA8FE38F
	version 4, created 1485105188, md5len 0, sigclass 0x13
	digest algo 8, begin of digest b2 91
	hashed subpkt 2 len 4 (sig created 2017-01-22)
	hashed subpkt 11 len 1 (pref-sym-algos: 9)
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 21 len 1 (pref-hash-algos: 8)
	hashed subpkt 22 len 1 (pref-zip-algos: 0)
	hashed subpkt 23 len 1 (keyserver preferences: 80)
	subpkt 16 len 8 (issuer key ID A59E3DA5EA8FE38F)
	subpkt 26 len 10 (policy: TREZOR-GPG)
	data: 6B7432720438102DF175729A0E3942F0AC676DDDF5348E1216E01F6881A1DB06
	data: 5F5E11802D6EC012A90D0C9E2A1FDE83EB93ADF7E5D1BD58E10FDB8DFEB34624
# off=260 ctb=89 tag=2 hlen=3 plen=284
:signature packet: algo 1, keyid 2EDBA674816C16C3
	version 4, created 1485105523, md5len 0, sigclass 0x10
	digest algo 8, begin of digest ec 03
	hashed subpkt 2 len 4 (sig created 2017-01-22)
	subpkt 16 len 8 (issuer key ID 2EDBA674816C16C3)
	data: 030683866524F83040D33BB43DBF9D7B4828CA0E28B58A160028669ADECAFC375B28F750CE4986E7CC33210843D2A8F36AFACCCA85E7FEC3047FBAF447C8AF983B652E4AA85FF7D8D638222221848AC88704F2BFDFD8A9BA6230F53B47C5A7487E1F3AED503C310C6820CD0077C8466C55530385BEF7D951F28185EF5777E7D37E2AE8F384CE9B872D1E16AE35D5D609F1057511E88BCB1F243E5B02A4D01DB88966BABCB5020F64E7E0400E53861646190B4FD8381F82BD03DF71CB170F3FC25CB1BEA731037A46771A2841AC256F17BC865D3463375B738204EE67C2841309EC8C424DD12F3D261B5CAC49C31ECA7C4FD30EB735CD55A31F800D252D6D7596
# off=547 ctb=b4 tag=13 hlen=2 plen=32
:user ID packet: "Stefan Parviainen <pafcu@iki.fi>"
# off=581 ctb=88 tag=2 hlen=2 plen=121
:signature packet: algo 19, keyid A59E3DA5EA8FE38F
	version 4, created 1485105228, md5len 0, sigclass 0x13
	digest algo 8, begin of digest 82 7b
	hashed subpkt 2 len 4 (sig created 2017-01-22)
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 11 len 4 (pref-sym-algos: 9 8 7 2)
	hashed subpkt 21 len 5 (pref-hash-algos: 8 9 10 11 2)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (keyserver preferences: 80)
	subpkt 16 len 8 (issuer key ID A59E3DA5EA8FE38F)
	data: 3767640B9A6C16EF4268234C0ED8B818B8A067E4D3FBDABD676CF5ABAE749451
	data: 2262070EFF722AD739D6D592EA76BDEEBE61022B5F2CEFFD3A32B2E004A1005F
# off=704 ctb=89 tag=2 hlen=3 plen=284
:signature packet: algo 1, keyid 2EDBA674816C16C3
	version 4, created 1485105524, md5len 0, sigclass 0x10
	digest algo 8, begin of digest 4e 84
	hashed subpkt 2 len 4 (sig created 2017-01-22)
	subpkt 16 len 8 (issuer key ID 2EDBA674816C16C3)
	data: 95955B3D33DBA37F86752D99298EF1E9388078D31ED8FBB2212CB3ABBDA5CC24693F4FC94EC4EAA360CD745D65ACB8871ACB569E4EEEC3C50D107F45C8A2A1094B31573CB3ED55B664F8C8B4A8A7CADB4258BA8A7311D32834CF264180CCEE64CF97A568B8A69C900C902D7168118076475AFFEDEDF3A0EA0C84C4F0BB85A7A4E63081475216F60C0C2071582B2072C1ACBBFBA1822577182E847A9905CAF9D314F13C11B57998AF19589C938EFA279B4852D9D93AC86F79111195C4FC8F9D40B536FC814CC9C911BB70DB49678D81F350756E9709DAAE01F9E197F4A426F7FAF89A12CD0EF0A7F30B896916F34E2B7D7BD14ECA7DC88BCEFC2058B9F8795B29
# off=991 ctb=b4 tag=13 hlen=2 plen=44
:user ID packet: "Stefan Parviainen <stefan.parviainen@iki.fi>"
# off=1037 ctb=88 tag=2 hlen=2 plen=120
:signature packet: algo 19, keyid A59E3DA5EA8FE38F
	version 4, created 1485105250, md5len 0, sigclass 0x13
	digest algo 8, begin of digest b0 b1
	hashed subpkt 2 len 4 (sig created 2017-01-22)
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 11 len 4 (pref-sym-algos: 9 8 7 2)
	hashed subpkt 21 len 5 (pref-hash-algos: 8 9 10 11 2)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (keyserver preferences: 80)
	subpkt 16 len 8 (issuer key ID A59E3DA5EA8FE38F)
	data: BAAE34BCA9E11D1DED13841367F307E14C10F459E2B70E6F2C4F02391B2EFFC9
	data: D88B294507C53F5759A9FB45BE0D24CD32247C3CA77D4FFA3B009A29156D71
# off=1159 ctb=89 tag=2 hlen=3 plen=284
:signature packet: algo 1, keyid 2EDBA674816C16C3
	version 4, created 1485105515, md5len 0, sigclass 0x10
	digest algo 8, begin of digest a1 68
	hashed subpkt 2 len 4 (sig created 2017-01-22)
	subpkt 16 len 8 (issuer key ID 2EDBA674816C16C3)
	data: 3C22333408D02167959794AC1392505CD0086F36CADD5790CCEF97823FF7E3992078A299A9BEC64DF94479C4378580F8122C067941AD59027DB935BF93547E121459493A68AC99616F8A06EAA95A10BBC3C6A02533339BE95C336E565F175338AD91643D029654C1405D4C3BC9BD490C94FDC04D8ED9BB67AE340AEB2CE5D91F3A1D5B0E17EF870C1C002DA6EDC059D6BB51CA4DD6E44F651D9D3CFD31A60E742989A0A4859BF6D8338AF391983C7BF1FF2C65A831D09F2587B24AD2326CD9194AC2519E6E3545DB58BF785BE3DD38BAF2250F87A76364BAEEDF135200FFEA54E5366D946D12967D77A77F00AA27A2EE859C46970E476C85B54A016B3EE6369C
# off=1446 ctb=b8 tag=14 hlen=2 plen=86
:public sub key packet:
	version 4, algo 18, created 1485105188, expires 0
	pkey[0]: 082A8648CE3D030107 nistp256 (1.2.840.10045.3.1.7)
	pkey[1]: 04D6C816E03BB1734049196BEFBEFE4D33E8E284107103BC1C993DE22CA15A2BA4A4E49BBED1E19DC4B241CB70C997E11D19DD284364E94E1641279ACBB2F827A3
	pkey[2]: 03010807
	keyid: B539F19ED9189709
# off=1534 ctb=88 tag=2 hlen=2 plen=109
:signature packet: algo 19, keyid A59E3DA5EA8FE38F
	version 4, created 1485105188, md5len 0, sigclass 0x18
	digest algo 8, begin of digest 6a 1d
	hashed subpkt 2 len 4 (sig created 2017-01-22)
	hashed subpkt 27 len 1 (key flags: 0C)
	subpkt 16 len 8 (issuer key ID A59E3DA5EA8FE38F)
	subpkt 26 len 10 (policy: TREZOR-GPG)
	data: CEE7F57613E59E571FCE9270608AE738A29A85B6685A2F2891DAA3BEC4B6CA7E
	data: 0A3B3600B94592FC56A31CC4C714988799FFCD3E9FEA9843304F97004AF75378
```

**Comment by romanz** [comment]
I haven't succeeded to reproduce this issue locally... :(
It seems like an issue with my GPG public key packet parser code.
Could you please attach the public GPG key from above (using `gpg2 --export -a`)?

**Comment by romanz** [comment]
Also, could you please attach the logs from `~/.gnupg/trezor/gpg-agent.log`?
It should contain the DEBUG-level message emitted by the parser, so hopefully it could be possible to understand what went wrong...

**Comment by pafcu** [comment]
Sorry. I did some more digging, and turns out that the problem is not _my_ key, but rather a key that I have imported. I sent you the problematic key by email.

**Comment by romanz** [comment]
Thanks for the information!
This key seems to have a subkey packet with an unexpected prefix (causing the assertion above).
Since it's not required for handling the TREZOR-based keys, it can be safely ignored - as done at https://github.com/romanz/trezor-agent/commit/6a7165298f28216e69b1bfac357a9c1f3533d0f7.

**Comment by pafcu** [comment]
Thanks, works now!
